# -*- coding: utf-8 -*-
"""SAQA 118792 AI Software Developer (NQF 5) - Lesson 10.

Covers KM-10 Governance, Legislation and Ethics (1 cr),
KM-11 Design Thinking and Innovation (1 cr),
KM-12 4IR and Future Skills (4 cr),
PM-10 Multidisciplinary Team (3 cr),
PM-11 Design Thinking Workshop (4 cr).
"""

LESSON_HTML = (
    "<h2>Governance, Ethics, Design Thinking, 4IR and Teamwork</h2>"
    "<p>This final lesson pulls together the <strong>non-technical pillars</strong> "
    "that turn a working AI prototype into a <em>responsible, useful product</em> "
    "in the South African context. You will learn the laws that govern data and AI, "
    "the human-centred design process used to invent new solutions, the wider 4IR "
    "landscape in which AI sits, and the team skills you need to ship real systems.</p>"

    "<h3>Part 1 &mdash; Governance, Legislation and Ethics</h3>"
    "<p>AI systems consume <strong>personal data</strong> and make decisions that "
    "affect people. In South Africa the main law is the <strong>Protection of "
    "Personal Information Act 4 of 2013 (POPIA)</strong>, fully enforceable since "
    "1 July 2021 and administered by the <strong>Information Regulator</strong>.</p>"

    "<h3>POPIA &mdash; eight conditions for lawful processing</h3>"
    "<ol>"
    "<li><strong>Accountability</strong> &mdash; the responsible party must ensure compliance.</li>"
    "<li><strong>Processing limitation</strong> &mdash; lawful, minimal, with consent or another legal basis.</li>"
    "<li><strong>Purpose specification</strong> &mdash; collect for a specific, explicitly defined purpose.</li>"
    "<li><strong>Further processing limitation</strong> &mdash; new uses must be compatible with the original purpose.</li>"
    "<li><strong>Information quality</strong> &mdash; data must be complete, accurate and up to date.</li>"
    "<li><strong>Openness</strong> &mdash; notify data subjects and keep a PAIA manual.</li>"
    "<li><strong>Security safeguards</strong> &mdash; technical and organisational controls; breach notification to the Regulator.</li>"
    "<li><strong>Data subject participation</strong> &mdash; right to access, correct and delete data.</li>"
    "</ol>"
    "<p><strong>Special personal information</strong> (race, health, biometrics, religion, sexual life, "
    "criminal behaviour, children's data) requires <em>extra</em> justification under sections 26&ndash;35. "
    "Cross-border transfers (s 72) need an adequate level of protection in the receiving country &mdash; "
    "this is the <strong>data sovereignty</strong> question that affects where you host an AI model.</p>"

    "<h3>POPIA vs GDPR vs ECTA</h3>"
    "<table><thead><tr><th>Aspect</th><th>POPIA (SA)</th><th>GDPR (EU)</th></tr></thead><tbody>"
    "<tr><td>Maximum fine</td><td>R10 million or 10 years</td><td>EUR 20 m or 4% global turnover</td></tr>"
    "<tr><td>Regulator</td><td>Information Regulator</td><td>National DPAs + EDPB</td></tr>"
    "<tr><td>Lawful bases</td><td>Consent, contract, legal duty, legitimate interest, public interest, vital interest</td><td>Same six bases</td></tr>"
    "<tr><td>DPIA required</td><td>For high-risk processing</td><td>Article 35 mandatory cases</td></tr>"
    "</tbody></table>"
    "<p>The <strong>Electronic Communications and Transactions Act 25 of 2002 (ECTA)</strong> "
    "governs electronic signatures, online contracts and intermediary liability, and complements POPIA.</p>"

    "<h3>Intellectual property and AI-generated outputs</h3>"
    "<p>Under the SA <em>Copyright Act 98 of 1978</em> a work needs a human author. Outputs purely "
    "generated by a model sit in a grey zone. Best practice: keep prompts, training-data licences and "
    "a human-in-the-loop review trail. Be careful with code suggestions from tools trained on public "
    "repositories &mdash; licences such as GPL can still apply.</p>"

    "<h3>Ethical issues in AI</h3>"
    "<ul>"
    "<li><strong>Bias and fairness</strong> &mdash; e.g. a credit-scoring model that under-serves rural applicants.</li>"
    "<li><strong>Transparency and explainability</strong> &mdash; can you justify a decision to a customer or the Regulator?</li>"
    "<li><strong>Accountability</strong> &mdash; who is liable when a model causes harm?</li>"
    "<li><strong>Safety</strong> &mdash; robustness against adversarial inputs, hallucinations, prompt injection.</li>"
    "<li><strong>Privacy</strong> &mdash; minimise data, anonymise, use differential privacy where possible.</li>"
    "<li><strong>Job displacement</strong> &mdash; design for augmentation, plan reskilling.</li>"
    "</ul>"

    "<h3>Global AI governance frameworks</h3>"
    "<ul>"
    "<li><strong>OECD AI Principles (2019)</strong> &mdash; inclusive growth, human-centred values, transparency, robustness, accountability.</li>"
    "<li><strong>EU AI Act (2024)</strong> &mdash; four risk tiers: <em>unacceptable</em> (banned), <em>high</em> (conformity assessment), <em>limited</em> (transparency obligations), <em>minimal</em>.</li>"
    "<li><strong>UNESCO Recommendation on the Ethics of AI (2021)</strong> &mdash; adopted by 193 states including South Africa.</li>"
    "<li><strong>SA National AI Policy Framework (2024)</strong> &mdash; positions AI for inclusive growth, jobs and public-service delivery.</li>"
    "</ul>"
    "<blockquote><strong>Privacy by Design</strong>: bake the seven Cavoukian principles "
    "(proactive, default, embedded, full-functionality, end-to-end, visibility, user-centric) "
    "into the architecture &mdash; not bolted on at the end.</blockquote>"

    "<h3>Part 2 &mdash; Design Thinking and Innovation</h3>"
    "<p>Design thinking is a <strong>human-centred</strong> problem-solving method popularised by "
    "Stanford d.school and IDEO. It has <strong>five phases</strong> and is iterative, not linear.</p>"
    "<ol>"
    "<li><strong>Empathise</strong> &mdash; interview users, shadow them, build empathy maps.</li>"
    "<li><strong>Define</strong> &mdash; synthesise findings into a sharp problem statement and personas.</li>"
    "<li><strong>Ideate</strong> &mdash; diverge widely with brainstorming, Crazy 8s, SCAMPER.</li>"
    "<li><strong>Prototype</strong> &mdash; build the cheapest thing that can be tested (paper, Figma, Wizard-of-Oz, MVP).</li>"
    "<li><strong>Test</strong> &mdash; put it in front of real users, observe, iterate.</li>"
    "</ol>"
    "<p>The <strong>Double Diamond</strong> (UK Design Council) overlays diverge/converge thinking: "
    "Discover &rarr; Define &rarr; Develop &rarr; Deliver.</p>"
    "<p>Key tools: <strong>persona</strong> (fictional user profile), <strong>journey map</strong> "
    "(steps, emotions, pain points), <strong>How-Might-We (HMW)</strong> questions, "
    "<strong>Crazy 8s</strong> (eight sketches in eight minutes), <strong>MVP</strong> "
    "(minimum viable product), <strong>A/B testing</strong> (compare two variants statistically). "
    "When applied to AI, design thinking keeps the <em>human in the centre</em> &mdash; we ask "
    "<em>should</em> we build this, not just <em>can</em> we.</p>"

    "<h3>Part 3 &mdash; 4IR and Future Skills</h3>"
    "<p>The <strong>Fourth Industrial Revolution (4IR)</strong>, coined by Klaus Schwab in 2016, "
    "is the fusion of physical, digital and biological worlds through cyber-physical systems. "
    "Nine commonly-cited pillars:</p>"
    "<table><thead><tr><th>#</th><th>Pillar</th><th>SA example</th></tr></thead><tbody>"
    "<tr><td>1</td><td>Artificial Intelligence</td><td>Capitec fraud-detection model</td></tr>"
    "<tr><td>2</td><td>Internet of Things (IoT)</td><td>Smart-metering at Eskom</td></tr>"
    "<tr><td>3</td><td>Robotics</td><td>Automotive lines in East London</td></tr>"
    "<tr><td>4</td><td>Big Data and analytics</td><td>SARS tax-risk profiling</td></tr>"
    "<tr><td>5</td><td>Cloud computing</td><td>Azure Joburg / AWS Cape Town regions</td></tr>"
    "<tr><td>6</td><td>AR / VR</td><td>Mining-skills training simulators</td></tr>"
    "<tr><td>7</td><td>Additive manufacturing (3D print)</td><td>CSIR medical implants</td></tr>"
    "<tr><td>8</td><td>Autonomous vehicles</td><td>Mine haul-trucks at Anglo</td></tr>"
    "<tr><td>9</td><td>Cybersecurity</td><td>SITA SOC for government</td></tr>"
    "</tbody></table>"
    "<p><strong>World Economic Forum Future of Jobs Report 2023</strong> &mdash; top skills for 2027:</p>"
    "<ul>"
    "<li>Analytical thinking</li>"
    "<li>Creative thinking</li>"
    "<li>AI and big-data literacy</li>"
    "<li>Leadership and social influence</li>"
    "<li>Resilience, flexibility and agility</li>"
    "<li>Curiosity and lifelong learning</li>"
    "<li>Technological literacy</li>"
    "<li>Empathy and active listening</li>"
    "</ul>"
    "<p>In South Africa, Stats SA reports youth unemployment above 45%. 4IR adoption threatens "
    "routine clerical and call-centre jobs but creates demand for data, cloud and AI roles. "
    "Reskilling pathways include SETA learnerships, MICT-SETA AI bootcamps, "
    "the National Skills Fund, and online MOOCs (Coursera, edX).</p>"

    "<h3>Part 4 &mdash; Multidisciplinary AI Teams</h3>"
    "<p>A production AI system is never built by one person. Typical roles:</p>"
    "<ul>"
    "<li><strong>Data Engineer</strong> &mdash; pipelines, ETL, warehouses.</li>"
    "<li><strong>Data Scientist</strong> &mdash; statistics, modelling, experimentation.</li>"
    "<li><strong>ML Engineer</strong> &mdash; turn notebooks into scalable services.</li>"
    "<li><strong>AI Developer</strong> (this course) &mdash; integrate models into applications.</li>"
    "<li><strong>Product Manager</strong> &mdash; owns the <em>why</em> and the roadmap.</li>"
    "<li><strong>UX / UI Designer</strong> &mdash; human-centred interface.</li>"
    "<li><strong>Domain Expert</strong> &mdash; clinician, lawyer, farmer; ensures realism.</li>"
    "<li><strong>QA Engineer</strong> &mdash; tests functional <em>and</em> fairness behaviour.</li>"
    "<li><strong>DevOps / MLOps</strong> &mdash; CI/CD, monitoring, model drift.</li>"
    "<li><strong>AI Ethicist / Compliance</strong> &mdash; bias audits, POPIA sign-off.</li>"
    "</ul>"
    "<h3>Agile delivery</h3>"
    "<p><strong>Scrum</strong> uses fixed-length sprints (2&ndash;3 weeks), a Product Owner, a "
    "Scrum Master and ceremonies (planning, daily stand-up, review, retrospective). "
    "<strong>Kanban</strong> is flow-based with WIP limits and continuous delivery &mdash; "
    "often a better fit for ML research and ops work where unpredictability is high. "
    "Hybrid &quot;Scrumban&quot; is common.</p>"
    "<h3>Communication and conflict</h3>"
    "<p>Use the <strong>SBI model</strong> for feedback (Situation, Behaviour, Impact). "
    "For conflict, the Thomas-Kilmann instrument names five styles: competing, avoiding, "
    "accommodating, compromising, <em>collaborating</em> &mdash; aim for collaborating. "
    "Remote/hybrid tools: MS Teams, Slack, Jira, Confluence, GitHub, Miro for whiteboarding, "
    "Loom for async demos. Write things down: a remote team without written decisions is a "
    "team that has the same argument every week.</p>"
)

QUESTIONS = [
    (
        "mc",
        "<p>Which South African statute is the <strong>primary</strong> law governing the "
        "processing of personal information by an AI system?</p>",
        [
            ("Protection of Personal Information Act 4 of 2013 (POPIA)", True),
            ("Electronic Communications and Transactions Act 25 of 2002 (ECTA)", False),
            ("Promotion of Access to Information Act 2 of 2000 (PAIA)", False),
            ("Copyright Act 98 of 1978", False),
        ],
        "POPIA is the dedicated data-protection statute administered by the Information Regulator. "
        "ECTA covers e-signatures and online contracts, PAIA covers access to records, and "
        "the Copyright Act covers IP.",
    ),
    (
        "mc",
        "<p>How many <em>conditions for lawful processing</em> of personal information does "
        "POPIA set out?</p>",
        [
            ("Five", False),
            ("Seven", False),
            ("Eight", True),
            ("Ten", False),
        ],
        "POPIA has eight conditions: accountability, processing limitation, purpose specification, "
        "further processing limitation, information quality, openness, security safeguards, and "
        "data subject participation.",
    ),
    (
        "mc",
        "<p>Which of the following is classified as <strong>special personal information</strong> "
        "under POPIA and therefore needs an extra lawful basis?</p>",
        [
            ("A customer's email address", False),
            ("A user's biometric fingerprint template", True),
            ("A company's VAT number", False),
            ("A product's stock-keeping unit (SKU)", False),
        ],
        "Section 26 lists biometrics, race, health, religion, sexual life, criminal behaviour "
        "and trade-union membership as special personal information. Email addresses are ordinary "
        "personal information.",
    ),
    (
        "mc",
        "<p>In design thinking, what is the <strong>main purpose</strong> of the "
        "<em>Empathise</em> phase?</p>",
        [
            ("To finalise the technical architecture", False),
            ("To deeply understand users' needs, context and pain points", True),
            ("To launch the minimum viable product to paying customers", False),
            ("To select the cloud provider", False),
        ],
        "Empathise is about building genuine understanding of the user through interviews, "
        "observation and empathy maps &mdash; before any solution is proposed.",
    ),
    (
        "mc",
        "<p>Which framework defines AI systems in <strong>four risk tiers</strong> "
        "(unacceptable, high, limited, minimal)?</p>",
        [
            ("OECD AI Principles", False),
            ("UNESCO Recommendation on the Ethics of AI", False),
            ("EU AI Act", True),
            ("ISO/IEC 27001", False),
        ],
        "The EU AI Act (2024) is the first comprehensive AI law and uses a risk-tiered approach. "
        "OECD and UNESCO documents are principle-based, not risk-tiered.",
    ),
    (
        "mc",
        "<p>Which role on a multidisciplinary AI team is <em>most</em> responsible for the "
        "<strong>CI/CD pipeline, model deployment and monitoring of model drift</strong> in production?</p>",
        [
            ("Data Scientist", False),
            ("Product Manager", False),
            ("MLOps / DevOps Engineer", True),
            ("UX Designer", False),
        ],
        "MLOps engineers operationalise models: containers, pipelines, monitoring, rollback. "
        "Data Scientists build models; Product Managers own the roadmap; UX designs the interface.",
    ),
    (
        "tf",
        "<p><strong>True or False:</strong> Under POPIA, transferring personal information "
        "of South African data subjects to a cloud region in another country is "
        "<em>always</em> prohibited.</p>",
        [
            ("True", False),
            ("False", True),
        ],
        "False. Section 72 permits cross-border transfers when the recipient country has "
        "adequate protection, the data subject consents, the transfer is necessary for a "
        "contract, or it benefits the data subject. It is regulated, not banned.",
    ),
    (
        "tf",
        "<p><strong>True or False:</strong> One of the World Economic Forum's top future "
        "skills for 2027 is <em>AI and big-data literacy</em>.</p>",
        [
            ("True", True),
            ("False", False),
        ],
        "True. The WEF Future of Jobs Report 2023 lists analytical thinking, creative thinking "
        "and AI/big-data literacy among the fastest-growing skills.",
    ),
]

PRACTICAL_HTML = (
    "<h2>Practical Lab \u2014 Design-Thinking Sprint for a Responsible AI Solution</h2>"
    "<p>In this half-day solo sprint you will run a compressed design-thinking cycle on a "
    "real South African challenge and pressure-test your idea against POPIA and ethics. "
    "Set a timer; the discipline of the clock is part of the method.</p>"

    "<h3>Scenario options (pick one)</h3>"
    "<ul>"
    "<li>AI chatbot that books clinic appointments in isiZulu and English for a rural Department of Health clinic.</li>"
    "<li>AI tutor that gives matric Mathematics learners worked-example feedback on cellphones.</li>"
    "<li>AI assistant that helps a small-scale farmer in the Free State diagnose maize-leaf disease from a phone photo.</li>"
    "</ul>"

    "<h3>Step 1 &mdash; Empathise (20 min)</h3>"
    "<p>Write a short <strong>user persona</strong> using this template:</p>"
    "<pre><code>Name:            Thandi Mokoena\n"
    "Age / role:      34, mother of two, works at Pick n Pay\n"
    "Location:        Tembisa, Gauteng\n"
    "Devices:         Entry-level Android, 2 GB data per month\n"
    "Goal:            Book a clinic slot without queueing from 04:00\n"
    "Pain points:     Long queues; data cost; isiZulu preferred\n"
    "Quote:           &quot;I lose a day&apos;s wages every time I visit the clinic.&quot;\n"
    "</code></pre>"

    "<h3>Step 2 &mdash; Define: three How-Might-We questions (10 min)</h3>"
    "<ol>"
    "<li>How might we let Thandi book a clinic slot in under two minutes on a low-end phone?</li>"
    "<li>How might we communicate in her home language without expensive translation?</li>"
    "<li>How might we avoid storing more health data than the clinic strictly needs?</li>"
    "</ol>"

    "<h3>Step 3 &mdash; Ideate: 8 ideas in 8 minutes (Crazy 8s)</h3>"
    "<p>Fold an A4 page into eight panels. Set a timer for one minute per panel. Sketch one "
    "idea per panel &mdash; no editing, no judging. Aim for variety: a WhatsApp bot, a USSD menu, "
    "a voice-call IVR, a missed-call callback, an offline-first app, a community-health-worker "
    "tablet, a printed QR poster, a Telegram channel. Pick the <em>one</em> idea you would "
    "test first.</p>"

    "<h3>Step 4 &mdash; Prototype: MVP sketch (30 min)</h3>"
    "<p>Sketch the chosen idea as a paper or Figma wireframe. Define the smallest version "
    "that delivers value:</p>"
    "<ul>"
    "<li><strong>In MVP:</strong> book a slot, confirm via SMS, cancel a slot.</li>"
    "<li><strong>Out of MVP:</strong> payments, medical-history capture, multi-clinic search.</li>"
    "</ul>"

    "<h3>Step 5 &mdash; POPIA checklist</h3>"
    "<table><thead><tr><th>Condition</th><th>Your answer</th></tr></thead><tbody>"
    "<tr><td>Lawful basis</td><td>e.g. consent captured at first message</td></tr>"
    "<tr><td>Data minimisation</td><td>Name + cellphone + clinic only; no diagnosis stored</td></tr>"
    "<tr><td>Purpose limitation</td><td>Used only to book / remind appointments</td></tr>"
    "<tr><td>Security</td><td>TLS in transit, AES-256 at rest, RBAC on admin panel</td></tr>"
    "<tr><td>Data subject rights</td><td>Reply STOP to delete; reply MY DATA to export</td></tr>"
    "<tr><td>Cross-border</td><td>Hosted in Azure South Africa North &mdash; no transfer</td></tr>"
    "</tbody></table>"

    "<h3>Step 6 &mdash; Three ethical risks and mitigations</h3>"
    "<ol>"
    "<li><strong>Language bias</strong> &mdash; mitigation: human-reviewed isiZulu training data and a fallback to a human agent on low-confidence intents.</li>"
    "<li><strong>Exclusion of non-smartphone users</strong> &mdash; mitigation: USSD fallback so feature-phone users are not left behind.</li>"
    "<li><strong>Hallucinated medical advice</strong> &mdash; mitigation: bot never gives medical advice; hard-coded scope limited to booking, with a disclaimer.</li>"
    "</ol>"

    "<h3>Step 7 &mdash; Multidisciplinary team needed</h3>"
    "<ul>"
    "<li>Product Manager (you, for the sprint)</li>"
    "<li>UX Designer (vernacular conversation flows)</li>"
    "<li>AI / NLP Developer</li>"
    "<li>Backend + MLOps Engineer</li>"
    "<li>Clinic nurse-manager (domain expert)</li>"
    "<li>Information Officer / POPIA compliance lead</li>"
    "<li>QA tester &mdash; functional <em>and</em> fairness</li>"
    "</ul>"

    "<h3>Step 8 &mdash; Reflection</h3>"
    "<ol>"
    "<li>Which How-Might-We question excited you most, and why?</li>"
    "<li>Which POPIA condition was hardest to satisfy?</li>"
    "<li>If you had one more week, which assumption would you test first with real users?</li>"
    "<li>What is one ethical risk you would escalate to the Information Officer before launch?</li>"
    "</ol>"

    "<blockquote>Deliverable: a single PDF or slide deck containing your persona, three HMW "
    "questions, eight idea sketches, MVP wireframe, POPIA checklist, three risks and mitigations, "
    "team list and reflection answers. Save it as <code>lesson10_sprint_&lt;yourname&gt;.pdf</code>.</blockquote>"
)


assert LESSON_HTML.startswith("<h2>Governance, Ethics, Design Thinking, 4IR and Teamwork</h2>")
assert len(LESSON_HTML) >= 2200, len(LESSON_HTML)
assert len(QUESTIONS) == 8
assert PRACTICAL_HTML.startswith("<h2>Practical Lab \u2014 Design-Thinking Sprint for a Responsible AI Solution</h2>")
assert len(PRACTICAL_HTML) >= 1500, len(PRACTICAL_HTML)

_mc = sum(1 for q in QUESTIONS if q[0] == "mc")
_tf = sum(1 for q in QUESTIONS if q[0] == "tf")
assert _mc >= 6 and _tf <= 2 and _mc + _tf == 8
for _qt, _qh, _opts, _fb in QUESTIONS:
    assert sum(1 for _o, _c in _opts if _c) == 1
    if _qt == "mc":
        assert len(_opts) == 4
    else:
        assert len(_opts) == 2
