# Auto-generated by _build_ai901.py
LESSON_HTML = """
<html-body>
<h2>Introduction: Implementing Text and Speech Solutions with Azure AI Foundry</h2>

<p>Azure AI Foundry provides a unified platform for building AI applications that understand and generate natural language through text and speech. In this lesson, you'll learn how to implement three core capabilities: analyzing text using Azure AI Language, enabling voice interaction through Azure AI Speech, and building multimodal applications that respond to audio prompts using large language models like GPT-4o. These services integrate seamlessly in Foundry Tools and the Foundry SDK, allowing you to create intelligent applications that understand context, sentiment, entities, and spoken intent.</p>

<h2>Text Analysis with Azure AI Language</h2>

<p>Azure AI Language enables your applications to understand text at scale. Whether you need to detect sentiment, extract key information, identify personally identifiable information (PII), or summarize long documents, the Azure AI Language client provides pre-built models that work out of the box.</p>

<h3>Text Analysis Methods Overview</h3>

<table>
<thead>
<tr>
<th>Analysis Method</th>
<th>Use Case</th>
<th>Output</th>
<th>Latency</th>
</tr>
</thead>
<tbody>
<tr>
<td>Sentiment Analysis</td>
<td>Classify customer feedback, reviews, social media posts</td>
<td>positive/neutral/negative with confidence scores</td>
<td>Low (~100ms)</td>
</tr>
<tr>
<td>Entity Recognition (NER)</td>
<td>Extract people, locations, organizations, products from text</td>
<td>Entity type, text span, confidence</td>
<td>Low (~150ms)</td>
</tr>
<tr>
<td>Key Phrase Extraction</td>
<td>Identify main topics and important phrases</td>
<td>Key phrases with relevance</td>
<td>Low (~100ms)</td>
</tr>
<tr>
<td>PII Detection</td>
<td>Find and redact sensitive data (email, phone, SSN, etc.)</td>
<td>Entity redactions with categories</td>
<td>Low (~150ms)</td>
</tr>
<tr>
<td>Summarization</td>
<td>Condense long documents or meeting transcripts</td>
<td>Extractive/abstractive summaries</td>
<td>Medium (~1-2s)</td>
</tr>
</tbody>
</table>

<h3>Building a Text Analysis Application</h3>

<p>The following code demonstrates how to use the Azure AI Language client to perform multiple analyses on a single text input:</p>

<pre><code class="language-python">from azure.ai.language.text import TextAnalysisClient
from azure.core.credentials import AzureKeyCredential

# Initialize the Azure AI Language client
endpoint = "https://&lt;resource-name&gt;.cognitiveservices.azure.com/"
api_key = "&lt;your-api-key&gt;"
client = TextAnalysisClient(endpoint, AzureKeyCredential(api_key))

text = \"\"\"
I absolutely love the new Azure AI Foundry platform. The documentation is clear, 
and the integration with Speech and Language services is seamless. 
However, I wish the pricing model were more transparent.
Contact us at support@contoso.com or call (555) 123-4567 for assistance.
\"\"\"

# Perform sentiment analysis
sentiment_result = client.analyze_sentiment(text, language="en")
print(f"Overall Sentiment: {sentiment_result.sentiment}")
print(f"Positive: {sentiment_result.confidence_scores.positive:.2%}")
print(f"Negative: {sentiment_result.confidence_scores.negative:.2%}")

# Extract named entities
entities_result = client.recognize_entities(text, language="en")
print("\nNamed Entities:")
for entity in entities_result.entities:
    print(f"  {entity.text} - {entity.category}")

# Extract key phrases
key_phrases_result = client.extract_key_phrases(text, language="en")
print("\nKey Phrases:")
for phrase in key_phrases_result.key_phrases:
    print(f"  {phrase}")

# Detect PII (Personally Identifiable Information)
pii_result = client.recognize_pii_entities(text, language="en")
print("\nPII Detected:")
for pii in pii_result.entities:
    print(f"  {pii.text} - {pii.category}")
    
# Summarization (extractive or abstractive)
summarization_result = client.summarize(text, language="en", kind="extractive")
print("\nSummary:")
for sentence in summarization_result.sentences:
    print(f"  {sentence.text}")
</code></pre>

<h2>Speech-to-Text and Text-to-Speech with Azure AI Speech</h2>

<p>Azure AI Speech enables real-time voice interaction through speech recognition and synthesis. You can capture spoken input from microphones or audio files, convert it to text, process it, and respond with natural-sounding speech using neural voices.</p>

<h3>Speech Service Features Comparison</h3>

<table>
<thead>
<tr>
<th>Feature</th>
<th>Real-Time STT</th>
<th>Batch Transcription</th>
<th>Neural TTS</th>
<th>Custom Voice</th>
</tr>
</thead>
<tbody>
<tr>
<td>Input Source</td>
<td>Microphone, streaming audio</td>
<td>Audio files (bulk processing)</td>
<td>Text string</td>
<td>Custom voice samples</td>
</tr>
<tr>
<td>Latency</td>
<td>100-500ms</td>
<td>Minutes to hours</td>
<td>100-200ms</td>
<td>Variable (pre-trained)</td>
</tr>
<tr>
<td>Language Support</td>
<td>99+ languages</td>
<td>99+ languages</td>
<td>200+ voices, 140+ languages</td>
<td>Limited to trained models</td>
</tr>
<tr>
<td>Cost Model</td>
<td>Per-hour pricing</td>
<td>Per-audio-minute pricing (lower)</td>
<td>Per-character pricing</td>
<td>Custom training + usage fees</td>
</tr>
<tr>
<td>Use Case</td>
<td>Call centers, voice commands, live meetings</td>
<td>Transcribing meeting recordings, archives</td>
<td>Chatbots, accessibility, notifications</td>
<td>Brand-consistent voice, premium experiences</td>
</tr>
</tbody>
</table>

<h3>Real-Time Speech-to-Text Implementation</h3>

<p>Capture speech from a microphone and convert it to text in real-time using the Azure AI Speech SDK:</p>

<pre><code class="language-python">import azure.cognitiveservices.speech as speechsdk

# Initialize Speech Configuration
speech_config = speechsdk.SpeechConfig(
    subscription="&lt;your-speech-key&gt;",
    region="eastus"
)
speech_config.speech_recognition_language = "en-US"

# Use the default microphone as audio source
audio_config = speechsdk.audio.AudioConfig(use_default_microphone=True)

# Create speech recognizer
recognizer = speechsdk.SpeechRecognizer(
    speech_config=speech_config,
    audio_config=audio_config
)

print("Speak into your microphone...")
speech_recognition_result = recognizer.recognize_once()

if speech_recognition_result.reason == speechsdk.ResultReason.RecognizedSpeech:
    print(f"Recognized: {speech_recognition_result.text}")
elif speech_recognition_result.reason == speechsdk.ResultReason.NoMatch:
    print("No speech detected")
elif speech_recognition_result.reason == speechsdk.ResultReason.Canceled:
    cancellation = speech_recognition_result.cancellation_details
    print(f"Error: {cancellation.reason}")

# Alternative: Recognize from audio file
audio_config_file = speechsdk.audio.AudioConfig(
    filename="path/to/audio.wav"
)
recognizer_file = speechsdk.SpeechRecognizer(
    speech_config=speech_config,
    audio_config=audio_config_file
)
result = recognizer_file.recognize_once()
print(f"File transcription: {result.text}")
</code></pre>

<h3>Text-to-Speech with Neural Voices</h3>

<p>Convert text to natural-sounding speech using neural voices available in Foundry. The following code demonstrates text-to-speech synthesis:</p>

<pre><code class="language-python">import azure.cognitiveservices.speech as speechsdk

# Initialize Speech Configuration
speech_config = speechsdk.SpeechConfig(
    subscription="&lt;your-speech-key&gt;",
    region="eastus"
)

# Set the voice (neural voice options include en-US-AriaNeural, en-US-GuyNeural, etc.)
speech_config.speech_synthesis_voice_name = "en-US-AriaNeural"

# Output to speaker
audio_config = speechsdk.audio.AudioConfig(use_default_speaker=True)

# Create speech synthesizer
synthesizer = speechsdk.SpeechSynthesizer(
    speech_config=speech_config,
    audio_config=audio_config
)

text = "Welcome to Azure AI Foundry. This message is being synthesized using a neural voice."

# Synthesize speech
speech_synthesis_result = synthesizer.speak_text_async(text).get()

if speech_synthesis_result.reason == speechsdk.ResultReason.SynthesizingAudioCompleted:
    print("Text-to-speech synthesis completed successfully.")
elif speech_synthesis_result.reason == speechsdk.ResultReason.Canceled:
    cancellation = speech_synthesis_result.cancellation_details
    print(f"Synthesis canceled: {cancellation.reason}")

# Save to file
output_config = speechsdk.audio.AudioConfig(filename="output.wav")
synthesizer_file = speechsdk.SpeechSynthesizer(
    speech_config=speech_config,
    audio_config=output_config
)
synthesizer_file.speak_text_async(text).get()
print("Audio saved to output.wav")

# List available neural voices
for voice in speechsdk.SpeechSynthesizer.get_voices_async().get().voices:
    print(f"{voice.name} - {voice.locale} ({voice.voice_type})")
</code></pre>

<h2>Multimodal Audio Interaction with GPT-4o in Foundry</h2>

<p>Azure AI Foundry supports multimodal models like GPT-4o that can accept audio input and generate audio or text output. This enables you to build conversational AI applications that respond directly to spoken prompts without separate speech recognition and synthesis steps.</p>

<h3>Implementing Multimodal Audio Responses</h3>

<p>Use the Foundry SDK to send audio to GPT-4o and receive audio output:</p>

<pre><code class="language-python">from azure.ai.inference import ChatCompletionsClient
from azure.core.credentials import AzureKeyCredential
import base64

# Initialize Foundry client
foundry_endpoint = "https://&lt;your-project&gt;.eastus.inference.ai.azure.com/"
foundry_key = "&lt;your-foundry-key&gt;"
client = ChatCompletionsClient(
    endpoint=foundry_endpoint,
    credential=AzureKeyCredential(foundry_key)
)

# Read audio file and encode as base64
with open("user_question.wav", "rb") as audio_file:
    audio_base64 = base64.b64encode(audio_file.read()).decode("utf-8")

# Send audio to gpt-4o-realtime-preview with audio output
messages = [
    {
        "role": "user",
        "content": [
            {
                "type": "input_audio",
                "input_audio": {
                    "data": audio_base64,
                    "format": "wav"
                }
            }
        ]
    }
]

response = client.complete(
    model="gpt-4o-realtime-preview",
    messages=messages,
    modalities=["text", "audio"],
    temperature=0.7
)

# Extract audio output if present
if response.choices[0].message.content:
    for content_block in response.choices[0].message.content:
        if hasattr(content_block, "audio"):
            # Save audio response
            audio_data = base64.b64decode(content_block.audio.data)
            with open("response.wav", "wb") as f:
                f.write(audio_data)
            print("Audio response saved to response.wav")
        elif hasattr(content_block, "text"):
            print(f"Text response: {content_block.text}")
</code></pre>

<h2>Integration: Building a Complete Application</h2>

<p>Combine text analysis, speech, and multimodal capabilities to create a sophisticated application. In a real scenario, you might capture voice input, analyze it for intent and sentiment, provide a spoken response, and log all interactions.</p>

<h3>Installation and Setup</h3>

<p>Install the required Azure AI SDK packages:</p>

<pre><code class="language-bash">pip install azure-ai-language-text azure-cognitiveservices-speech azure-ai-inference</code></pre>

<p>Set environment variables for your Azure credentials:</p>

<pre><code class="language-bash">export LANGUAGE_ENDPOINT="https://&lt;resource-name&gt;.cognitiveservices.azure.com/"
export LANGUAGE_KEY="&lt;your-language-key&gt;"
export SPEECH_KEY="&lt;your-speech-key&gt;"
export SPEECH_REGION="eastus"
export FOUNDRY_ENDPOINT="https://&lt;your-project&gt;.eastus.inference.ai.azure.com/"
export FOUNDRY_KEY="&lt;your-foundry-key&gt;"
</code></pre>

<h2>Best Practices and Considerations</h2>

<ul>
<li><strong>Choose the Right Service:</strong> Use Azure AI Language for text-only analysis of documents, emails, or social media. Use Azure AI Speech for real-time voice interaction or when you need custom voices. Use multimodal models like GPT-4o in Foundry when you want end-to-end voice conversations with reasoning capabilities.</li>
<li><strong>Cost Optimization:</strong> For large volumes of audio, batch transcription is significantly cheaper than real-time STT. For TTS, select standard voices unless brand consistency requires custom voices.</li>
<li><strong>Error Handling:</strong> Always check the reason field in SDK responses (RecognizedSpeech, NoMatch, Canceled) and implement retry logic with exponential backoff for API calls.</li>
<li><strong>Security:</strong> Store API keys in Azure Key Vault, not in code. Use managed identities in production environments. Redact PII before storing logs.</li>
<li><strong>Language Configuration:</strong> Always specify language codes explicitly (e.g., en-US, fr-FR) to avoid ambiguity and ensure accurate results.</li>
<li><strong>Audio Format Support:</strong> Azure AI Speech supports WAV, OGG, MP3, and other formats. Ensure audio is properly formatted and sampled at 16 kHz for optimal results.</li>
</ul>

<h2>Key Takeaways</h2>

<ul>
<li>Azure AI Language provides pre-built models for sentiment analysis, entity recognition, key phrase extraction, PII detection, and summarization.</li>
<li>Azure AI Speech enables real-time speech-to-text and text-to-speech with 200+ neural voices across 140+ languages.</li>
<li>Batch transcription is cost-effective for processing large audio archives, while real-time STT serves interactive applications.</li>
<li>Custom voices in Azure AI Speech provide brand-consistent speech output for premium experiences.</li>
<li>GPT-4o with multimodal audio in Azure AI Foundry enables direct audio-to-audio conversations without intermediate steps.</li>
<li>Choose between Azure AI Language and Speech based on your use case: use Language for text analysis, Speech for voice-only interaction, and multimodal models for conversational AI.</li>
<li>Always implement proper error handling, security practices (Key Vault), and language configuration for production applications.</li>
</ul>

<h2>Further Reading</h2>

<ul>
<li><a href="https://learn.microsoft.com/en-us/azure/ai-services/language-service/overview">Azure AI Language — Microsoft Learn</a></li>
<li><a href="https://learn.microsoft.com/en-us/azure/ai-services/speech-service/overview">Azure AI Speech — Microsoft Learn</a></li>
<li><a href="https://learn.microsoft.com/en-us/azure/ai-studio/how-to/develop-models-in-foundry">Developing Models in Azure AI Foundry — Microsoft Learn</a></li>
<li><a href="https://learn.microsoft.com/en-us/azure/ai-services/speech-service/text-to-speech">Text-to-Speech Documentation — Microsoft Learn</a></li>
<li><a href="https://learn.microsoft.com/en-us/azure/ai-services/speech-service/speech-to-text">Speech-to-Text Documentation — Microsoft Learn</a></li>
<li><a href="https://learn.microsoft.com/en-us/azure/ai-services/speech-service/batch-transcription">Batch Transcription — Microsoft Learn</a></li>
<li><a href="https://learn.microsoft.com/en-us/azure/ai-studio/reference/sdk-overview">Azure AI Foundry SDK Reference — Microsoft Learn</a></li>
</ul>
</html-body>
"""

QUESTIONS = [
    (
        "What does sentiment analysis in Azure AI Language classify text as?",
        [
            ("positive, neutral, or negative with confidence scores", True),
            ("only positive or negative categories", False),
            ("entities and their types only", False),
            ("key phrases and topics", False)
        ],
        10,
        "Sentiment analysis classifies text as positive, neutral, or negative and provides confidence scores for each class. This helps assess customer satisfaction and market sentiment."
    ),
    (
        "You are building a customer support application. You need to extract person names, organizations, and phone numbers from support tickets. Which Azure service should you use?",
        [
            ("Azure AI Language with Named Entity Recognition (NER)", True),
            ("Azure AI Speech with real-time STT", False),
            ("Azure AI Language Summarization only", False),
            ("GPT-4o multimodal audio endpoint", False)
        ],
        10,
        "Named Entity Recognition extracts entities like people, organizations, and contact information from text. This is the appropriate service for structured information extraction from support tickets."
    ),
    (
        "<pre><code class=\"language-python\">client = TextAnalysisClient(endpoint, AzureKeyCredential(key))\nresult = client.summarize(text, language=&#34;en&#34;, kind=&#34;extractive&#34;)</code></pre> In this code snippet, what does the &#34;extractive&#34; kind parameter do compared to &#34;abstractive&#34; summarization?",
        [
            ("Extractive selects key sentences from the original text; abstractive generates new sentences that may not appear in the source", True),
            ("Extractive generates entirely new text; abstractive uses only original sentences", False),
            ("Extractive is for audio files; abstractive is for text files", False),
            ("Extractive is faster but less accurate than abstractive", False)
        ],
        10,
        "Extractive summarization selects important sentences from the original text, while abstractive summarization uses language models to generate new sentences that summarize the content. Extractive is faster and more faithful to the source; abstractive is more concise and natural."
    ),
    (
        "Your application needs to transcribe hundreds of hours of meeting recordings. Which Azure AI Speech approach is most cost-effective?",
        [
            ("Batch transcription API for large audio file collections", True),
            ("Real-time speech-to-text with continuous streaming", False),
            ("Custom voice synthesis for each recording", False),
            ("GPT-4o with multimodal audio endpoint", False)
        ],
        10,
        "Batch transcription is designed for processing large volumes of audio files at lower cost per minute. Real-time STT is more expensive and meant for interactive applications. Batch transcription can process hundreds of hours efficiently with delays of minutes to hours."
    ),
    (
        "<pre><code class=\"language-python\">with open(&#34;user_audio.wav&#34;, &#34;rb&#34;) as f:\n    audio_b64 = base64.b64encode(f.read()).decode()\nmessages = [{&#34;role&#34;: &#34;user&#34;, &#34;content&#34;: [{&#34;type&#34;: &#34;input_audio&#34;, &#34;input_audio&#34;: {&#34;data&#34;: audio_b64, &#34;format&#34;: &#34;wav&#34;}}]}]\nresponse = client.complete(model=&#34;gpt-4o-realtime-preview&#34;, messages=messages)</code></pre> What is the advantage of using GPT-4o multimodal audio in Foundry versus separate speech-to-text and text-to-speech services?",
        [
            ("Multimodal audio processes voice end-to-end with reasoning, eliminating intermediate steps and enabling richer context handling", True),
            ("Multimodal audio is always cheaper than separate services", False),
            ("Multimodal audio supports more languages than separate services", False),
            ("Multimodal audio guarantees real-time latency under 100ms", False)
        ],
        10,
        "GPT-4o with multimodal audio capabilities enables end-to-end voice conversations where the model understands context and can reason across the entire conversation without separate STT/TTS steps. This results in more coherent responses and simpler application logic, though it may have different latency and cost characteristics than separate services."
    ),
    (
        "You want to detect and redact sensitive information like email addresses, credit card numbers, and social security numbers from user feedback. Which Azure AI Language feature should you use?",
        [
            ("Personally Identifiable Information (PII) Detection", True),
            ("Entity Recognition (NER) only", False),
            ("Sentiment Analysis", False),
            ("Key Phrase Extraction", False)
        ],
        10,
        "PII Detection is specifically designed to identify and categorize sensitive data like emails, phone numbers, SSNs, and credit card numbers. You can use it to automatically redact or mask this information before storing or processing user data."
    ),
    (
        "<pre><code class=\"language-python\">recognizer = speechsdk.SpeechRecognizer(speech_config, audio_config)\nresult = recognizer.recognize_once()\nif result.reason == speechsdk.ResultReason.RecognizedSpeech:\n    print(result.text)</code></pre> This code uses real-time speech-to-text. What would be the best scenario for this real-time approach compared to batch transcription?",
        [
            ("Interactive voice commands, customer support calls, and live meeting transcription where immediate response is needed", True),
            ("Processing large audio archives overnight", False),
            ("Transcribing 1000 hours of historical recordings", False),
            ("Reducing total transcription costs for bulk processing", False)
        ],
        10,
        "Real-time speech-to-text is designed for interactive scenarios where immediate results are required—like voice commands, live customer service calls, and real-time meeting captions. Batch transcription is better for non-urgent, high-volume scenarios where cost optimization is prioritized over speed."
    ),
    (
        "Your chatbot needs to provide responses in a customer's preferred voice. You plan to pre-record audio samples for training. Which Azure AI Speech feature enables this?",
        [
            ("Custom voice synthesis using speaker profile training", True),
            ("Neural voice selection from built-in options", False),
            ("Real-time speech recognition with voice identification", False),
            ("Batch transcription with voice signatures", False)
        ],
        10,
        "Custom voice in Azure AI Speech allows you to create a brand-consistent or personalized voice by training a speaker profile with your own audio samples. This goes beyond selecting a pre-built neural voice and creates a unique voice identity for your application."
    )
]
