# Auto-generated by _build_ai901.py
LESSON_HTML = """
<p><strong>Introduction:</strong> Understanding how generative AI models work is essential for selecting and deploying the right solutions in Azure AI Foundry. This lesson explores the core concepts behind large language models, examines the spectrum of available models and their capabilities, and provides hands-on guidance for configuring models in production deployments.</p>

<h2>How Generative AI Models Work</h2>

<h3>Tokens and Embeddings</h3>
<p><strong>Tokens</strong> are the fundamental units that language models process. A token represents a piece of text — typically a word, subword, or punctuation mark. For example, the phrase "Hello, world!" might be tokenized as ["Hello", ",", "world", "!"]. Models don't understand raw text; they convert text into numeric sequences (token IDs) that the neural network can process.</p>

<p><strong>Embeddings</strong> are numerical representations of tokens or entire sequences, typically dense vectors of 100–4,096 dimensions. These vectors encode semantic meaning: similar concepts produce similar embeddings, enabling the model to understand relationships. For instance, the embeddings for "king" and "queen" are close together, while "king" and "apple" are distant. Embedding models in Foundry produce vectors that power semantic search and retrieval systems.</p>

<blockquote><strong>Key distinction:</strong> Tokens are discrete units of text; embeddings are continuous vectors that encode meaning. Together, they form the data pipeline: text → tokens → embeddings → neural processing.</blockquote>

<h3>Transformers and Attention Mechanisms</h3>
<p><strong>Transformer architecture</strong> is the foundation of modern large language models (LLMs). At its core, a transformer uses an <strong>attention mechanism</strong> that enables the model to weigh the importance of every token in relation to every other token. This "attention" allows the model to understand context across long sequences — grasping that "bank" refers to a financial institution in one sentence and a riverbank in another.</p>

<p>Key components:</p>
<ul>
  <li><strong>Self-attention:</strong> Each token looks at all other tokens to understand its context.</li>
  <li><strong>Multi-head attention:</strong> Multiple parallel attention layers capture different types of relationships (syntax, semantics, etc.).</li>
  <li><strong>Feed-forward layers:</strong> Process and enrich the representations after attention.</li>
  <li><strong>Positional encoding:</strong> Encodes the order of tokens so the model knows sequence position.</li>
</ul>

<p>This architecture enables models to process tokens in parallel, making training and inference efficient compared to earlier sequential models.</p>

<h3>Training, Inference, and Foundation Models</h3>
<p><strong>Training</strong> is the phase where models learn patterns from vast amounts of text data (billions of tokens). During training, the model adjusts billions of parameters to minimize prediction error. A foundation model (or base model) is a large, general-purpose model trained on diverse internet-scale data — for example, GPT-4 or Llama 2. Foundation models learn broad linguistic knowledge and world facts, but are not specialized for any single task.</p>

<p><strong>Inference</strong> is the deployment phase: using a trained model to generate predictions on new input. Inference is where users submit prompts and receive completions. During inference, the model performs forward passes through its neural network to produce tokens one at a time (auto-regressive generation).</p>

<p>Key differences:</p>
<ul>
  <li><strong>Training:</strong> Requires massive compute, uses backpropagation to update parameters, computationally expensive, happens once (typically).</li>
  <li><strong>Inference:</strong> Uses fixed parameters, generates responses token-by-token, optimized for latency, happens continuously in production.</li>
</ul>

<h3>Fine-Tuning and Retrieval-Augmented Generation (RAG)</h3>
<p><strong>Fine-tuning</strong> adapts a foundation model to a specific domain or task by training it on a smaller, specialized dataset. For example, fine-tuning GPT-3.5 on medical terminology and case studies produces a model that excels at medical reasoning. Fine-tuning updates (a portion of) the model's parameters — fewer updates than full training, but more customization than prompt engineering.</p>

<p>When to use fine-tuning:</p>
<ul>
  <li>You have hundreds or thousands of task-specific examples.</li>
  <li>You need consistent formatting or specialized vocabulary.</li>
  <li>The foundation model lacks sufficient domain knowledge.</li>
  <li>Cost-per-token is critical (fine-tuned models run faster on smaller hardware).</li>
</ul>

<p><strong>Retrieval-Augmented Generation (RAG)</strong> is an alternative approach: instead of fine-tuning, you provide the model with relevant context from external sources (documents, databases) at inference time. The pipeline is:</p>
<ol>
  <li>User submits a query.</li>
  <li>System retrieves relevant documents from a knowledge base (using embeddings or keyword search).</li>
  <li>Retrieved documents are included in the prompt to the model.</li>
  <li>Model generates an answer grounded in the retrieved context.</li>
</ol>

<p>RAG advantages: no retraining, easily updatable knowledge, transparent sources. RAG disadvantages: may include irrelevant context, adds latency for retrieval.</p>

<table>
  <thead>
    <tr>
      <th>Aspect</th>
      <th>Fine-Tuning</th>
      <th>RAG</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><strong>Approach</strong></td>
      <td>Update model parameters on task data</td>
      <td>Inject context into prompts at runtime</td>
    </tr>
    <tr>
      <td><strong>Training required</strong></td>
      <td>Yes — compute and expertise needed</td>
      <td>No — only setup retrieval system</td>
    </tr>
    <tr>
      <td><strong>Knowledge updates</strong></td>
      <td>Requires retraining</td>
      <td>Update knowledge base anytime</td>
    </tr>
    <tr>
      <td><strong>Cost</strong></td>
      <td>Higher upfront; lower per-token after</td>
      <td>Higher per-token (retrieval overhead)</td>
    </tr>
    <tr>
      <td><strong>Best for</strong></td>
      <td>Specific domains with many examples</td>
      <td>Dynamic knowledge, compliance/transparency</td>
    </tr>
  </tbody>
</table>

<h2>Identifying Appropriate AI Models Based on Capabilities</h2>

<p>Azure AI Foundry provides access to a growing catalog of foundation models. Choosing the right model depends on your task, latency requirements, cost budget, and modality (text, image, speech, etc.).</p>

<h3>Model Families and Their Capabilities</h3>

<table>
  <thead>
    <tr>
      <th>Model Family</th>
      <th>Capability</th>
      <th>Modality</th>
      <th>Context Window</th>
      <th>Suggested Use Case</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><strong>GPT-4</strong></td>
      <td>Advanced reasoning, coding, analysis</td>
      <td>Text (also vision with GPT-4V/o)</td>
      <td>8K–128K tokens</td>
      <td>Complex problem-solving, code review, multi-step reasoning</td>
    </tr>
    <tr>
      <td><strong>GPT-3.5 Turbo</strong></td>
      <td>General-purpose chat, fast responses</td>
      <td>Text</td>
      <td>4K–16K tokens</td>
      <td>Customer support, content generation, low-latency applications</td>
    </tr>
    <tr>
      <td><strong>Llama 2 / Llama 3</strong></td>
      <td>Open-source, good general reasoning</td>
      <td>Text</td>
      <td>4K–8K tokens</td>
      <td>Organizations preferring open models, on-premises deployment</td>
    </tr>
    <tr>
      <td><strong>Mistral</strong></td>
      <td>Efficient reasoning, multilingual</td>
      <td>Text</td>
      <td>32K–200K tokens</td>
      <td>Long-context applications, RAG systems, cost-sensitive workloads</td>
    </tr>
    <tr>
      <td><strong>Phi-3 (Small)</strong></td>
      <td>Lightweight, edge-optimized</td>
      <td>Text</td>
      <td>4K–128K tokens</td>
      <td>Mobile apps, edge inference, real-time processing on constrained hardware</td>
    </tr>
    <tr>
      <td><strong>DALL·E 3</strong></td>
      <td>High-quality image generation</td>
      <td>Image (text-to-image)</td>
      <td>N/A</td>
      <td>Creative assets, product mockups, visual content generation</td>
    </tr>
    <tr>
      <td><strong>Whisper</strong></td>
      <td>Speech-to-text (ASR)</td>
      <td>Audio (speech input)</td>
      <td>N/A</td>
      <td>Transcription, voice commands, audio analysis</td>
    </tr>
  </tbody>
</table>

<h3>Text vs Chat Models</h3>
<p><strong>Text completion models</strong> (e.g., text-davinci-003) take a prompt and continue generating text. They are stateless and do not maintain conversation history automatically.</p>

<p><strong>Chat models</strong> (e.g., gpt-35-turbo, gpt-4) are fine-tuned for multi-turn conversation. They accept a structured message format (system, user, assistant) and are optimized for dialogue. Chat models are generally preferred for modern applications because they handle context and tone better.</p>

<h3>Small vs Large Models: Trade-offs</h3>
<p>Larger models (GPT-4, Llama 70B) are more capable but slower and costlier. Smaller models (Phi-3-small, Mistral-7B) are faster and cheaper but less sophisticated. The trend is toward increasingly effective smaller models:</p>

<ul>
  <li><strong>Large models:</strong> Better reasoning, fewer shots needed, handle rare edge cases. High latency, high cost, high memory.</li>
  <li><strong>Small models:</strong> Fast inference, low cost, small memory footprint. May require more prompt engineering or fine-tuning.</li>
</ul>

<p>Azure AI Foundry lets you experiment with multiple models side-by-side to find the optimal trade-off for your use case.</p>

<h2>Deployment Options and Configuration Parameters in Azure AI Foundry</h2>

<h3>Deployment Types</h3>

<table>
  <thead>
    <tr>
      <th>Deployment Type</th>
      <th>Quota Model</th>
      <th>Availability</th>
      <th>Best For</th>
      <th>Price Model</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><strong>Standard (Pay-As-You-Go)</strong></td>
      <td>Shared quota; hourly rate limits</td>
      <td>Shared infrastructure; variable latency</td>
      <td>Development, testing, low-traffic apps</td>
      <td>Per-token pricing; no commitment</td>
    </tr>
    <tr>
      <td><strong>Global Standard</strong></td>
      <td>Globally distributed; automatic load balancing</td>
      <td>Multi-region redundancy</td>
      <td>Production apps requiring high availability and low latency globally</td>
      <td>Per-token pricing with regional variations</td>
    </tr>
    <tr>
      <td><strong>Provisioned Throughput</strong></td>
      <td>Reserved capacity (tokens/minute)</td>
      <td>Dedicated resources; predictable latency</td>
      <td>High-volume, mission-critical applications with stable traffic</td>
      <td>Hourly reservation + per-token overage</td>
    </tr>
    <tr>
      <td><strong>Provisioned (Managed Compute)</strong></td>
      <td>Dedicated managed cluster</td>
      <td>Full control over hardware and scaling</td>
      <td>Enterprise deployments, custom compliance, private endpoints</td>
      <td>Infrastructure costs + per-token</td>
    </tr>
  </tbody>
</table>

<p><strong>Choosing a deployment type:</strong></p>
<ul>
  <li>Starting with a new model? Use <strong>Standard</strong>.</li>
  <li>Going global or need SLA? Use <strong>Global Standard</strong> or <strong>Provisioned Throughput</strong>.</li>
  <li>High volume and predictable traffic? Use <strong>Provisioned Throughput</strong>.</li>
  <li>Special compliance or performance needs? Consider <strong>Managed Compute</strong>.</li>
</ul>

<h3>Configuration Parameters</h3>

<p>When calling a deployed model in Azure AI Foundry, you configure parameters that control the model's behavior. Here's a practical guide:</p>

<table>
  <thead>
    <tr>
      <th>Parameter</th>
      <th>Range / Type</th>
      <th>Effect</th>
      <th>Typical Usage</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><strong>temperature</strong></td>
      <td>0.0 — 2.0</td>
      <td>Controls randomness. 0 = deterministic; 2 = maximum entropy.</td>
      <td>0.0–0.5 for factual tasks; 0.7–1.2 for creative content</td>
    </tr>
    <tr>
      <td><strong>top_p</strong></td>
      <td>0.0 — 1.0</td>
      <td>Nucleus sampling: only consider tokens in cumulative probability mass p. Limits diversity.</td>
      <td>0.9–1.0 for factual; 0.5–0.9 for balanced</td>
    </tr>
    <tr>
      <td><strong>max_tokens</strong></td>
      <td>1 — model context limit</td>
      <td>Maximum length of generated response in tokens.</td>
      <td>Set based on expected output length; lower = faster</td>
    </tr>
    <tr>
      <td><strong>frequency_penalty</strong></td>
      <td>-2.0 — 2.0</td>
      <td>Penalizes tokens proportional to frequency in generated text. Reduces repetition.</td>
      <td>0.5–1.0 to reduce repetition in long outputs</td>
    </tr>
    <tr>
      <td><strong>presence_penalty</strong></td>
      <td>-2.0 — 2.0</td>
      <td>Penalizes tokens that appear in the prompt. Encourages novel tokens.</td>
      <td>0.1–0.5 for creative diversity</td>
    </tr>
    <tr>
      <td><strong>stop_sequences</strong></td>
      <td>Array of strings</td>
      <td>Stop generation when any sequence is encountered.</td>
      <td>["END", "\n\n"] to control output length or structure</td>
    </tr>
  </tbody>
</table>

<h3>Example: Calling a Deployment with the Azure AI Inference SDK</h3>

<pre><code class="language-python">from azure.ai.inference import ChatCompletionsClient
from azure.core.credentials import AzureKeyCredential

# Initialize client for a Foundry deployment
client = ChatCompletionsClient(
    endpoint="https://your-foundry.inference.ai.azure.com",
    credential=AzureKeyCredential("your-api-key")
)

# Call a deployed model with configuration parameters
response = client.complete(
    model="gpt-4",  # deployment name in Foundry
    messages=[
        {"role": "system", "content": "You are a helpful AI assistant."},
        {"role": "user", "content": "Explain quantum entanglement in simple terms."}
    ],
    temperature=0.7,           # balanced randomness
    top_p=0.9,                 # nucleus sampling
    max_tokens=500,            # limit response length
    frequency_penalty=0.5,     # reduce repetition
    presence_penalty=0.0,      # no penalty for novel words
    stop_sequences=["END"]     # stop on this token
)

print(response.choices[0].message.content)
</code></pre>

<h3>Content Filters and Safety</h3>

<p>Azure AI Foundry deployments support content filters that detect and block harmful content (violence, sexual material, hate speech, self-harm). Filters can operate on input (user prompt) and output (model response).</p>

<p><strong>Content filter configuration:</strong></p>
<ul>
  <li><strong>Enabled:</strong> Actively monitor; block or warn based on severity threshold.</li>
  <li><strong>Severity thresholds:</strong> Low (permissive), Medium (balanced), High (strict).</li>
  <li><strong>Action:</strong> Block (return 400 error) or Warn (allow but log incident).</li>
</ul>

<p>When deploying a model in Foundry, you enable filters and set thresholds appropriate to your use case (e.g., stricter for public-facing apps, lenient for internal research).</p>

<h3>Example: JSON Deployment Configuration</h3>

<pre><code class="language-json">{
  "deployment": {
    "name": "gpt-4-prod",
    "model_id": "gpt-4-turbo",
    "deployment_type": "provisioned-throughput",
    "provisioned_throughput": {
      "tokens_per_minute": 40000,
      "auto_scale": true
    },
    "content_filter": {
      "enabled": true,
      "severity_threshold": "medium",
      "input_filter": true,
      "output_filter": true
    },
    "rate_limit": {
      "requests_per_minute": 200,
      "requests_per_day": 1000000
    },
    "monitoring": {
      "log_prompts": false,
      "log_completions": true,
      "alert_threshold_error_rate": 0.05
    }
  }
}
</code></pre>

<h3>Example: Parameter Selection for a Real Scenario</h3>

<pre><code class="language-python"># Scenario: Customer support chatbot
support_client = ChatCompletionsClient(
    endpoint="https://foundry.inference.ai.azure.com",
    credential=AzureKeyCredential("key")
)

# For support: factual, consistent responses
support_response = support_client.complete(
    model="gpt-35-turbo",
    messages=[
        {"role": "system", "content": "You are a customer support agent. Be concise and helpful."},
        {"role": "user", "content": "How do I reset my password?"}
    ],
    temperature=0.2,          # low randomness → consistent answers
    max_tokens=200,           # short, focused responses
    top_p=0.95,               # stick to likely continuations
    frequency_penalty=0.6,    # avoid repetitive phrases
    stop_sequences=["Thank you.", "Agent:"]  # natural stopping points
)

print(support_response.choices[0].message.content)
</code></pre>

<h2>Content Filters and Rate Limiting in Production</h2>

<p>Azure AI Foundry provides fine-grained control over how deployments behave:</p>

<ul>
  <li><strong>Rate limiting:</strong> Protect deployments by capping requests per minute/day. Essential to prevent abuse and control costs.</li>
  <li><strong>Content filtering:</strong> Block or warn on harmful input/output. Configurable severity levels.</li>
  <li><strong>Quotas:</strong> Enforce per-user or per-subscription limits on token usage.</li>
  <li><strong>Monitoring:</strong> Track response times, error rates, and filter hits to identify issues and optimize configurations.</li>
</ul>

<h2>Key Takeaways</h2>

<ul>
  <li><strong>Tokens and embeddings</strong> are the data representation layer: tokens are discrete text units; embeddings are semantic vectors.</li>
  <li><strong>Transformers and attention mechanisms</strong> enable models to understand long-range context and relationships between tokens.</li>
  <li><strong>Fine-tuning and RAG</strong> are complementary approaches: fine-tuning customizes the model; RAG injects knowledge at inference time.</li>
  <li><strong>Model selection</strong> depends on capability (reasoning, multimodal, speed), modality (text, image, speech), and context window. Use comparison tables to match models to workloads.</li>
  <li><strong>Deployment types</strong> (Standard, Global Standard, Provisioned Throughput) trade cost, performance, and availability. Start with Standard for prototyping; move to provisioned for production.</li>
  <li><strong>Configuration parameters</strong> (temperature, top_p, max_tokens, penalties) directly influence response quality and consistency. Lower temperature for factual; higher for creative.</li>
  <li><strong>Content filters and rate limits</strong> are essential for production safety and cost control. Always enable filters appropriate to your use case.</li>
</ul>

<h2>Further Reading</h2>

<ul>
  <li><a href="https://learn.microsoft.com/en-us/azure/ai-services/openai/concepts/models">Azure OpenAI Models</a> — Overview of available models and capabilities.</li>
  <li><a href="https://learn.microsoft.com/en-us/azure/ai-studio/concepts/models-endpoints">Azure AI Foundry: Models and Deployments</a> — Detailed deployment types and configuration.</li>
  <li><a href="https://learn.microsoft.com/en-us/azure/ai-services/openai/how-to/working-with-models">Working with Models in Azure OpenAI</a> — Practical guidance on model selection and use.</li>
  <li><a href="https://learn.microsoft.com/en-us/azure/ai-services/openai/concepts/tokens">Understanding Tokens</a> — In-depth token counting and representation.</li>
  <li><a href="https://learn.microsoft.com/en-us/azure/ai-services/content-safety/overview">Azure Content Safety</a> — Content filtering and compliance features.</li>
  <li><a href="https://learn.microsoft.com/en-us/azure/ai-services/openai/how-to/fine-tuning">Fine-tuning with Azure OpenAI</a> — Step-by-step fine-tuning workflows.</li>
  <li><a href="https://learn.microsoft.com/en-us/azure/search/vector-search-overview">Azure AI Search: Vector Search</a> — Building RAG systems with embeddings and retrieval.</li>
</ul>
"""

QUESTIONS = [
  (
    "What is the primary advantage of using <strong>embeddings</strong> over raw tokens in semantic search applications?",
    [
      ("Embeddings encode semantic meaning as dense vectors, allowing the system to find conceptually similar content even without exact token matches.", True),
      ("Embeddings eliminate the need for tokenization and reduce processing time by 90%.", False),
      ("Embeddings guarantee perfect accuracy in all search queries without false positives.", False),
      ("Embeddings are cheaper to compute than tokens and require no GPU memory.", False)
    ],
    10,
    "Correct! Embeddings capture semantic relationships (e.g., 'king' and 'queen' are close in vector space), enabling intelligent search. Incorrect answers overstate technical benefits or misrepresent embeddings' role."
  ),
  (
    "Which model would be most appropriate for a <strong>real-time customer support chatbot</strong> requiring low latency and consistent, factual responses?",
    [
      ("GPT-4 with temperature=1.5 — maximizes creative problem-solving.", False),
      ("GPT-3.5 Turbo with temperature=0.2 — fast, general-purpose, low randomness for consistency.", True),
      ("Llama 2 70B with top_p=0.5 — provides open-source reasoning without commercial restrictions.", False),
      ("DALL·E 3 — generates visual diagrams to enhance customer understanding.", False)
    ],
    10,
    "Correct! GPT-3.5 Turbo is optimized for speed and cost; temperature=0.2 ensures factual, repeatable answers. GPT-4 is overkill for support; DALL·E is for images; Llama 70B is slower."
  ),
  (
    "Compare fine-tuning and RAG. When should you choose <strong>RAG over fine-tuning</strong>?",
    [
      ("When your knowledge base changes frequently and you need real-time updates without retraining.", True),
      ("When you have 10,000+ labeled examples and want the model to learn domain-specific patterns permanently.", False),
      ("When minimizing inference latency is your only concern.", False),
      ("When you want to reduce the model's parameter count permanently.", False)
    ],
    10,
    "Correct! RAG injects knowledge at inference time, so the knowledge base can be updated instantly. Fine-tuning is better for static, learned patterns. Latency and parameter reduction are not primary motivations for choosing RAG."
  ),
  (
    "You are deploying a <strong>mission-critical summarization service</strong> for financial reports. The service must handle 50,000 requests daily with predictable latency and high availability. Which deployment type is best?",
    [
      ("Standard (Pay-As-You-Go) — simplest and cheapest to get started.", False),
      ("Global Standard — multi-region pay-per-token, best for spiky or globally distributed workloads.", False),
      ("Provisioned Throughput Units (PTU) — reserved capacity that guarantees predictable latency and cost for high-volume, stable traffic.", True),
      ("Managed Compute — required only when you self-host an open-source model on your own VMs.", False)
    ],
    10,
    "Provisioned Throughput Units (PTU) reserve dedicated capacity, giving you predictable latency and cost \u2014 ideal for steady, mission-critical traffic such as 50,000 requests per day. Standard offers no capacity guarantee, Global Standard is optimised for variable global demand, and Managed Compute is for self-hosted models."
  ),
  (
    "You want to generate <strong>highly creative marketing copy</strong> without repetitive phrasing. Which parameter adjustments would you make?",
    [
      ("Increase temperature to 0.9–1.2; set frequency_penalty to 0.6–1.0; reduce top_p to 0.7.", True),
      ("Set temperature to 0.1; maximize top_p to 1.0; disable penalties — forces diverse, unpredictable output.", False),
      ("Use only max_tokens to limit output length; all other parameters should remain at default.", False),
      ("Set frequency_penalty to -2.0 to encourage repetition for brand consistency.", False)
    ],
    10,
    "Correct! Higher temperature allows randomness; frequency_penalty penalizes repeated tokens. Lower top_p (nucleus sampling) focuses on likely continuations while excluding outliers. Incorrect options either ignore the relationship between parameters or misinterpret their effects."
  ),
  (
    "What does <strong>max_tokens</strong> control, and why is it important for cost management?",
    [
      ("max_tokens limits the length of the generated response; shorter responses consume fewer tokens, reducing API costs per request.", True),
      ("max_tokens specifies the size of the model's weight matrix; larger values improve reasoning accuracy.", False),
      ("max_tokens controls the context window size; setting it low prevents out-of-memory errors.", False),
      ("max_tokens enforces the rate limit; exceeding it triggers a 429 error for protection.", False)
    ],
    10,
    "Correct! Each generated token costs money; capping max_tokens controls per-request cost. Incorrect answers conflate max_tokens with model size, context windows, or rate limits — different concepts entirely."
  ),
  (
    "Your deployment has a content filter enabled at <strong>medium severity</strong> with both input and output filtering. A user's prompt contains mild profanity. What happens?",
    [
      ("The request is blocked immediately; a 400 error is returned to the user.", False),
      ("The prompt is flagged and logged, but the request proceeds if severity is below medium threshold.", True),
      ("The model generates a response, and the filter sanitizes the output before returning it.", False),
      ("The filter is disabled for this request; the model processes the prompt without restriction.", False)
    ],
    10,
    "Correct! Medium severity thresholds typically allow mild content but flag and log it. Blocks occur only for high-severity content. Filters don't sanitize mid-generation; they block or warn. Filters are always active when enabled. The exact behavior depends on the severity mapping configured in Foundry."
  ),
  (
    "You are building a <strong>code review assistant</strong> using the Azure AI Inference SDK. Write code that calls a deployed GPT-4 model with parameters optimized for accurate, detailed analysis without excessive length. Which Python snippet is correct?",
    [
      ("<pre><code class=\"language-python\">client.complete(\n    model=\"gpt-4\",\n    messages=[{\"role\": \"user\", \"content\": \"Review this code.\"}],\n    temperature=0.3,\n    max_tokens=1000,\n    top_p=0.95,\n    frequency_penalty=0.2\n)</code></pre>", True),
      ("<pre><code class=\"language-python\">client.complete(\n    model=\"gpt-4\",\n    messages=[{\"role\": \"user\", \"content\": \"Review this code.\"}],\n    temperature=1.8,\n    max_tokens=50,\n    top_p=0.3\n)</code></pre>", False),
      ("<pre><code class=\"language-python\">client.complete(\n    model=\"gpt-4\",\n    prompt=\"Review this code.\",\n    randomness=0.5,\n    output_length=1000\n)</code></pre>", False),
      ("<pre><code class=\"language-python\">client.complete(\n    model=\"gpt-4\",\n    messages=[{\"role\": \"user\", \"content\": \"Review this code.\"}],\n    temperature=0.0,\n    max_tokens=10000\n)</code></pre>", False)
    ],
    10,
    "Correct! Low temperature (0.3) for factual, focused analysis; max_tokens=1000 allows detailed output without runaway length; top_p=0.95 maintains quality. Incorrect: high temperature/low max_tokens contradicts the goal; 'prompt' and 'randomness' are wrong API parameters; temperature=0.0 with huge max_tokens may be repetitive."
  )
]
