# Auto-generated by _build_ai901.py
LESSON_HTML = """
<p><strong>Introduction:</strong> Azure AI Foundry serves as your unified platform for building enterprise-grade AI applications that combine multiple modalities. This lesson explores two critical capabilities within Foundry: leveraging multimodal vision models (like GPT-4o) for visual understanding and image generation with DALL·E 3 and gpt-image-1, plus extracting structured data from diverse content types using Azure AI Content Understanding. These tools enable you to build intelligent applications that see, understand, and interpret information at enterprise scale.</p>

<h2>Computer Vision and Image Generation with Foundry</h2>

<h3>Moving Beyond Traditional Computer Vision</h3>

<p>The evolution of AI has shifted from specialized APIs to <strong>multimodal foundation models</strong> that process both text and images in a single request. Instead of calling separate Computer Vision endpoints for object detection, OCR, or visual classification, you now send prompts with embedded images directly to models like GPT-4o, which understand context, reasoning, and visual nuance in ways classical APIs cannot.</p>

<table>
<thead>
<tr>
<th>Capability</th>
<th>Multimodal Models (GPT-4o in Foundry)</th>
<th>Classic Computer Vision API</th>
</tr>
</thead>
<tbody>
<tr>
<td>Input Modality</td>
<td>Text + image + context in one prompt</td>
<td>Image only or text separate from image</td>
</tr>
<tr>
<td>Reasoning</td>
<td>Natural language reasoning about visual content; contextual understanding</td>
<td>Structured feature extraction (tags, faces, text, objects)</td>
</tr>
<tr>
<td>Customization</td>
<td>Few-shot examples in prompt; system message instructions</td>
<td>Pre-trained models; limited customization without retraining</td>
</tr>
<tr>
<td>Use Cases</td>
<td>Visual Q&amp;A, document analysis with context, creative tasks, complex reasoning</td>
<td>Fast classification, real-time edge processing, production APIs</td>
</tr>
<tr>
<td>Cost Model</td>
<td>Pay per token (text + image tokens)</td>
<td>Per-request or per-image pricing</td>
</tr>
</tbody>
</table>

<h3>Vision Capabilities in Azure AI Foundry: GPT-4o and Image Generation</h3>

<p>Within Foundry, you deploy and invoke GPT-4o as a <strong>Chat Completion endpoint</strong> that natively accepts image content. The model interprets visual input, answers questions, describes scenes, extracts text (OCR), counts objects, and performs reasoning over images. You interact with it using the standard <code>openai</code> Python client or the Foundry SDK.</p>

<p>For <strong>generating</strong> images, Foundry integrates DALL·E 3 and gpt-image-1, allowing you to create new visual content from text descriptions. This enables use cases like product mockups, UI prototyping, and AI-generated assets for applications.</p>

<h3>Code Example 1: Analyzing an Image with GPT-4o via Foundry</h3>

<pre><code class="language-python">from openai import OpenAI
import base64

# Initialize client pointing to your Foundry deployment
client = OpenAI(
    api_key="your-foundry-api-key",
    base_url="https://your-resource.openai.azure.com/",
    api_version="2024-10-01-preview"
)

# Read and encode an image
with open("invoice.png", "rb") as img:
    image_data = base64.b64encode(img.read()).decode("utf-8")

# Send multimodal prompt: text + image
response = client.chat.completions.create(
    model="gpt-4o",  # Deployed in Foundry
    messages=[
        {
            "role": "user",
            "content": [
                {
                    "type": "text",
                    "text": "Extract the invoice number, date, and total amount from this image. Return as JSON."
                },
                {
                    "type": "image_url",
                    "image_url": {
                        "url": f"data:image/png;base64,{image_data}"
                    }
                }
            ]
        }
    ],
    max_tokens=512
)

print(response.choices[0].message.content)</code></pre>

<h3>Code Example 2: Generating Images with DALL·E 3 in Foundry</h3>

<pre><code class="language-python">from openai import OpenAI

client = OpenAI(
    api_key="your-foundry-api-key",
    base_url="https://your-resource.openai.azure.com/",
    api_version="2024-10-01-preview"
)

# Generate an image using DALL·E 3
response = client.images.generate(
    model="dall-e-3",  # or "gpt-image-1" for faster, more affordable generation
    prompt="A futuristic office with holographic displays, blue ambient lighting, minimalist design",
    size="1024x1024",
    quality="standard",  # or "hd" for higher quality
    n=1  # Number of images to generate
)

# Save the generated image
image_url = response.data[0].url
print(f"Generated image URL: {image_url}")

# Optionally download and save locally
import requests
img_response = requests.get(image_url)
with open("generated_image.png", "wb") as f:
    f.write(img_response.content)</code></pre>

<h3>Comparing Image Generation Models in Foundry</h3>

<table>
<thead>
<tr>
<th>Model</th>
<th>Quality</th>
<th>Speed</th>
<th>Cost</th>
<th>Best For</th>
</tr>
</thead>
<tbody>
<tr>
<td>DALL·E 3</td>
<td>Highest photorealism, strong composition and text rendering</td>
<td>Slower (30–60 sec)</td>
<td>Premium pricing</td>
<td>Professional visuals, marketing, UI mockups, detailed concepts</td>
</tr>
<tr>
<td>gpt-image-1</td>
<td>Very good, slightly more abstract, faster iteration</td>
<td>Fast (5–15 sec)</td>
<td>More affordable</td>
<td>Rapid prototyping, interactive apps, high-volume generation</td>
</tr>
<tr>
<td>Custom/Fine-tuned Models</td>
<td>Highly specific to training data</td>
<td>Depends on model</td>
<td>Variable; potential cost savings at scale</td>
<td>Domain-specific styles, branded assets</td>
</tr>
</tbody>
</table>

<h3>Building a Vision-Enabled Application</h3>

<p>When building a lightweight application with vision capabilities in Foundry, follow this architectural pattern:</p>

<ol>
<li><strong>Ingest images:</strong> Accept file uploads or URLs via a web interface or API.</li>
<li><strong>Validate and preprocess:</strong> Check image format, size, and orientation; optionally cache for cost efficiency.</li>
<li><strong>Invoke GPT-4o:</strong> Send the image and a carefully crafted prompt to the deployed model in your Foundry hub.</li>
<li><strong>Parse and store:</strong> Extract structured output (JSON) and store results in a database or cache.</li>
<li><strong>Generate imagery:</strong> For output, use DALL·E 3 or gpt-image-1 if user interaction requires new visuals.</li>
<li><strong>Monitor and iterate:</strong> Track token usage, latency, and error rates; adjust prompts and model versions as needed.</li>
</ol>

<blockquote>
<strong>Pro tip:</strong> Multimodal models charge based on <strong>image tokens</strong>, not just image count. A high-resolution image costs more tokens than a thumbnail. Resize images before sending when precise pixels are not needed; Foundry will automatically optimize the token cost for you when using the Vision enhancements feature.
</blockquote>

<h2>Information Extraction with Azure AI Content Understanding</h2>

<h3>What Is Azure AI Content Understanding?</h3>

<p>Azure AI Content Understanding is a specialized service within Foundry (accessed via Foundry Tools) that automates the extraction and structuring of information from unstructured or semi-structured content across <strong>documents, images, audio, and video</strong>. Rather than writing custom parsing logic, you describe the information you want to extract, and Content Understanding applies pre-built or custom analyzer templates to identify and return that data in structured form.</p>

<p>This is distinct from GPT-4o vision: where multimodal models excel at reasoning and contextual understanding, Content Understanding excels at <strong>high-volume, consistent field extraction</strong> across forms, invoices, receipts, transcribed audio, and video metadata.</p>

<h3>Modalities and Analyzer Templates</h3>

<p>Content Understanding routes your content to the appropriate analyzer based on modality and your extraction goals:</p>

<table>
<thead>
<tr>
<th>Modality</th>
<th>Content Type</th>
<th>Analyzer Template</th>
<th>Typical Output</th>
</tr>
</thead>
<tbody>
<tr>
<td>Documents</td>
<td>PDF, DOCX, TXT, images of forms</td>
<td>Form/Invoice/Receipt analyzer</td>
<td>Key-value pairs (e.g., Invoice Number, Date, Line Items)</td>
</tr>
<tr>
<td>Documents</td>
<td>Structured forms (e.g., W-2, tax forms)</td>
<td>Template-based analyzer</td>
<td>Mapped fields per form schema</td>
</tr>
<tr>
<td>Images</td>
<td>Screenshots, diagrams, photos</td>
<td>Image content analyzer</td>
<td>Objects, text (OCR), layout structure</td>
</tr>
<tr>
<td>Audio</td>
<td>MP3, WAV, speech recordings</td>
<td>Audio transcription + entity extraction</td>
<td>Transcribed text, identified speakers, key phrases</td>
</tr>
<tr>
<td>Video</td>
<td>MP4, MOV, live streams</td>
<td>Video frame analysis + audio transcription</td>
<td>Scene descriptions, speech text, timestamps</td>
</tr>
</tbody>
</table>

<h3>Code Example 3: Extracting Fields from an Invoice Using Content Understanding</h3>

<pre><code class="language-python">from azure.ai.projects import AIProjectClient
from azure.identity import DefaultAzureCredential

# Initialize Foundry project client
client = AIProjectClient.from_connection_string(
    conn_str="your-foundry-connection-string"
)

# Define the analyzer configuration for invoice extraction
analyzer_config = {
    "template_name": "invoice",
    "fields_to_extract": [
        "invoice_number",
        "invoice_date",
        "vendor_name",
        "total_amount",
        "line_items",
        "payment_terms"
    ]
}

# Process a document (file path or URL)
result = client.content_understanding.analyze_document(
    input_path="s3://bucket/invoice_2024.pdf",  # or local path
    analyzer=analyzer_config
)

# Extract and display results
print("Extracted Data:")
for field, value in result.extracted_fields.items():
    print(f"  {field}: {value}")

# Access confidence scores
if result.confidence_scores:
    print("\nConfidence Scores:")
    for field, confidence in result.confidence_scores.items():
        print(f"  {field}: {confidence:.2%}")</code></pre>

<h3>Code Example 4: Analyzing Images and Audio with Content Understanding</h3>

<pre><code class="language-python">from azure.ai.projects import AIProjectClient

client = AIProjectClient.from_connection_string(
    conn_str="your-foundry-connection-string"
)

# EXAMPLE 1: Analyze an image for object detection and text extraction
image_result = client.content_understanding.analyze_image(
    input_path="product_photo.jpg",
    extract_text=True,
    extract_objects=True
)

print("Image Analysis:")
print(f"  Detected text: {image_result.extracted_text}")
print(f"  Objects: {image_result.detected_objects}")

# EXAMPLE 2: Analyze audio for transcription and key entities
audio_result = client.content_understanding.analyze_audio(
    input_path="meeting_recording.mp3",
    language="en-US",
    extract_entities=True
)

print("\nAudio Analysis:")
print(f"  Transcription: {audio_result.transcription}")
print(f"  Detected entities: {audio_result.entities}")
print(f"  Duration: {audio_result.duration_seconds}s")</code></pre>

<h3>Code Example 5: Sample Content Understanding Analyzer Response Schema</h3>

<pre><code class="language-json">{
  "analyzer_id": "invoice-v2",
  "document_id": "doc_12345",
  "processing_status": "success",
  "extracted_fields": {
    "invoice_number": {
      "value": "INV-2024-0891",
      "confidence": 0.98,
      "bounding_box": {"top": 50, "left": 100, "width": 150, "height": 30}
    },
    "invoice_date": {
      "value": "2024-05-15",
      "confidence": 0.96
    },
    "total_amount": {
      "value": 2450.50,
      "confidence": 0.94,
      "currency": "USD"
    },
    "line_items": [
      {
        "description": "Consulting services",
        "quantity": 1,
        "unit_price": 2000.00,
        "line_total": 2000.00,
        "confidence": 0.91
      },
      {
        "description": "Travel reimbursement",
        "quantity": 1,
        "unit_price": 450.50,
        "line_total": 450.50,
        "confidence": 0.88
      }
    ]
  },
  "warnings": [],
  "processing_time_ms": 1240
}</code></pre>

<h3>Designing an Information Extraction Workflow</h3>

<p>A robust application combining Foundry tools might follow this flow:</p>

<blockquote>
<strong>Scenario:</strong> You're building a document automation system for an insurance company. Claims arrive as PDF forms, emails with attachments, and photos taken by mobile agents in the field.
</blockquote>

<ol>
<li><strong>Intake:</strong> Accept PDFs, images, and audio files via REST API or batch upload.</li>
<li><strong>Route by modality:</strong> Detect file type (PDF → document analyzer, JPG → image analyzer, MP3 → audio analyzer).</li>
<li><strong>Extract with Content Understanding:</strong> Use the appropriate analyzer to pull structured fields (claim ID, date, claimant name, damage description, amount).</li>
<li><strong>Validate with GPT-4o:</strong> For ambiguous or complex fields, optionally send the extracted data + original image to GPT-4o in a multimodal prompt for verification or reasoning.</li>
<li><strong>Enrich and store:</strong> Combine extracted data with external lookups, store in database, trigger downstream workflows.</li>
<li><strong>Audit trail:</strong> Log confidence scores, original content, and extracted JSON for compliance and debugging.</li>
</ol>

<h3>When to Choose Which Tool</h3>

<p><strong>Use GPT-4o multimodal vision when:</strong></p>
<ul>
<li>You need flexible, context-aware visual reasoning rather than rigid field extraction.</li>
<li>The content varies significantly (e.g., unstructured emails with mixed images and text).</li>
<li>You want to ask complex questions about an image ("Is this person wearing safety equipment?" or "Summarize this whiteboard photo").</li>
<li>You're prototyping and can tolerate longer processing times for higher accuracy.</li>
</ul>

<p><strong>Use Content Understanding when:</strong></p>
<ul>
<li>You have high-volume, repetitive content (thousands of invoices, forms, applications).</li>
<li>You need <strong>confidence scores</strong> and structured, auditable output.</li>
<li>Processing speed and cost predictability are critical.</li>
<li>Content spans multiple modalities (some docs, some images, some audio).</li>
<li>You need field-level extraction with bounding boxes or spatial metadata.</li>
</ul>

<h3>Building a Capstone Application: End-to-End Workflow</h3>

<p>Imagine an <strong>AI-powered receipt analyzer application</strong> for expense management:</p>

<ol>
<li><strong>User uploads receipt image.</strong></li>
<li><strong>Content Understanding image analyzer</strong> extracts merchant, date, items, and total.</li>
<li><strong>Validation step:</strong> If confidence on any field &lt; 85%, invoke GPT-4o to review the original image and confirm or correct the extracted values.</li>
<li><strong>Categorization:</strong> Using extracted merchant name and items, classify the expense (Travel, Meals, Office Supplies, etc.).</li>
<li><strong>Storage:</strong> Save structured JSON and original image; trigger approval workflow.</li>
<li><strong>Analytics:</strong> Aggregate across all receipts to identify spending patterns.</li>
</ol>

<p>This hybrid approach—Content Understanding for fast, confident extraction + GPT-4o for validation and reasoning—creates a robust, production-grade system.</p>

<h3>Deployment and Scalability</h3>

<p>Both capabilities scale within Azure AI Foundry through <strong>managed endpoints</strong> and <strong>serverless APIs</strong>. Content Understanding runs asynchronously, supporting batch processing of thousands of documents. GPT-4o endpoints auto-scale based on traffic. You pay only for consumed tokens and processing time, making both cost-effective for enterprise workloads.</p>

<h2>Key Takeaways</h2>

<ul>
<li>GPT-4o multimodal models in Foundry provide flexible, reasoning-based visual understanding; send text + images in a single prompt for Q&amp;A, analysis, and creative tasks.</li>
<li>Image generation models (DALL·E 3 and gpt-image-1) enable creating new visuals; choose DALL·E 3 for premium quality, gpt-image-1 for speed and cost efficiency.</li>
<li>Content Understanding is purpose-built for high-volume, consistent field extraction across documents, images, audio, and video with confidence scores and audit trails.</li>
<li>Use multimodal models for context-aware reasoning; use Content Understanding for structured, repeatable extraction from unstructured data.</li>
<li>Hybrid workflows combining both tools (Content Understanding for extraction, GPT-4o for validation) yield robust, production-grade systems.</li>
<li>Scalability in Foundry is managed automatically; focus on prompt design, analyzer templates, and business logic.</li>
</ul>

<h2>Further Reading</h2>

<ul>
<li><a href="https://learn.microsoft.com/en-us/azure/ai-services/content-understanding/overview">Azure AI Content Understanding overview — Microsoft Learn</a></li>
<li><a href="https://learn.microsoft.com/en-us/azure/ai-services/openai/how-to/gpt-4-vision">GPT-4o multimodal vision capabilities — Microsoft Learn</a></li>
<li><a href="https://learn.microsoft.com/en-us/azure/ai-services/openai/how-to/dall-e">DALL·E image generation in Azure AI Foundry — Microsoft Learn</a></li>
<li><a href="https://learn.microsoft.com/en-us/azure/ai-studio/how-to/create-project">Getting started with Azure AI Foundry — Microsoft Learn</a></li>
<li><a href="https://learn.microsoft.com/en-us/azure/ai-services/content-understanding/analyzer-templates">Content Understanding analyzer templates and field mappings — Microsoft Learn</a></li>
</ul>
"""

QUESTIONS = [
  (
    "When using GPT-4o in Azure AI Foundry to analyze an invoice image, what is the primary advantage over using the classic Computer Vision API?",
    [
      ("GPT-4o can apply natural language reasoning and context to interpret the image, extract text with reasoning, and answer follow-up questions about the invoice—all in a single interaction.", True),
      ("GPT-4o is significantly cheaper and processes images faster than the Computer Vision API.", False),
      ("GPT-4o automatically detects and corrects errors in handwritten fields without additional prompts.", False),
      ("GPT-4o can directly connect to your accounting system and post journal entries.", False)
    ],
    10,
    "Multimodal models like GPT-4o excel at contextual reasoning and flexible interpretation. While the classic Computer Vision API is optimized for fast, structured extraction, GPT-4o allows you to ask complex, conversational questions about visual content. In this scenario, you could ask 'Is this a valid invoice?' or 'What are the payment terms?' in the same prompt."
  ),
  (
    "You are generating product mockup images for a design review. Which image generation model should you choose, and why?",
    [
      ("gpt-image-1, because it is the fastest and most cost-effective for rapid iteration and prototyping.", True),
      ("DALL·E 3, because it always produces the highest photorealism regardless of cost.", False),
      ("Custom fine-tuned model, because only proprietary models can generate product mockups.", False),
      ("A combination of both models equally, because one cannot generate mockups alone.", False)
    ],
    10,
    "For rapid prototyping and design iteration, gpt-image-1 is the pragmatic choice: it generates visuals in 5–15 seconds at a more affordable price point. DALL·E 3 is better reserved for final, production-ready marketing visuals where photorealism and precision text rendering are critical. Fine-tuning is only needed for very specialized, domain-specific styles."
  ),
  (
    "A developer is building a lightweight expense report application using Azure AI Foundry. The app receives receipt images from multiple formats and needs to extract merchant, date, items, and total amount. The developer must decide between using Content Understanding or prompting GPT-4o multimodal vision. Which is the better primary choice?",
    [
      ("Content Understanding, because it is purpose-built for high-volume, consistent field extraction with confidence scores and audit trails; GPT-4o can still be used as a validation layer for low-confidence results.", True),
      ("GPT-4o multimodal, because it is more intelligent and will always produce correct results without extra configuration.", False),
      ("Both equally, because they produce identical output in the same processing time.", False),
      ("Neither—build a custom OCR parser using Tesseract and OpenCV instead.", False)
    ],
    10,
    "Content Understanding is optimized for production workflows requiring scalability, confidence metrics, and audit compliance. While GPT-4o multimodal excels at reasoning, Content Understanding was designed exactly for repetitive, structured field extraction from documents and images. The hybrid approach—Content Understanding as the primary extractor + GPT-4o for validation when confidence is low—is the enterprise best practice."
  ),
  (
    "In a Content Understanding analyzer, you are extracting invoice fields. The confidence score for the total amount is 0.78. What does this mean, and what is a reasonable next step?",
    [
      ("It means Content Understanding is 78% confident in the extracted value. A next step could be to pass the low-confidence field and original image to GPT-4o for verification or manual review.", True),
      ("It means the model has extracted 78% of the invoice fields correctly and all remaining fields are incorrect.", False),
      ("It means the invoice image quality is too low and should be rejected outright.", False),
      ("It means you must pay an extra fee to Content Understanding to increase the confidence to 90%.", False)
    ],
    10,
    "Confidence scores are per-field, not per-invoice. A score of 0.78 on the total amount indicates moderate confidence—the extraction is likely correct but could benefit from secondary validation. Hybrid workflows send borderline extractions to GPT-4o for reasoning-based confirmation or flag for manual review. This approach minimizes errors while keeping throughput high."
  ),
  (
    "You need to extract structured data from a collection of audio files: interviews, meeting recordings, and lectures. Which Content Understanding analyzer should you use, and what will the output include?",
    [
      ("Audio analyzer; output will include transcribed text, identified speakers, detected entities (names, organizations, dates), and optional timestamps for key phrases.", True),
      ("Image analyzer, because audio must first be converted to visual spectrograms.", False),
      ("Document analyzer, because audio must be saved as a text transcript file first.", False),
      ("Video analyzer, because audio is a component of video content.", False)
    ],
    10,
    "The audio analyzer in Content Understanding processes MP3, WAV, and other audio formats directly. It transcribes speech, identifies speakers, and extracts entities. You do not need to pre-convert to images or documents. Video analyzer is a separate path for video files that include both audio transcription and frame-level visual analysis."
  ),
  (
    "<pre><code class=\"language-python\">from azure.ai.projects import AIProjectClient\nclient = AIProjectClient.from_connection_string(conn_str=\"...\")\nresult = client.content_understanding.analyze_image(\n    input_path=\"screenshot.png\",\n    extract_text=True,\n    extract_objects=True\n)\nprint(result.extracted_text)\nprint(result.detected_objects)</code></pre>\n    <p>In the code above, what modality and analyzer type is being used, and what are two typical outputs you would expect?</p>",
    [
      ("Image modality using the image content analyzer; expected outputs are extracted text (OCR) and detected objects (entities, regions).", True),
      ("Document modality using the form analyzer; outputs are key-value pairs and field mappings.", False),
      ("Audio modality using the transcription analyzer; outputs are speakers and entities.", False),
      ("Video modality using the frame analyzer; outputs are scene descriptions and timestamps.", False)
    ],
    10,
    "The <code>analyze_image()</code> method targets the image modality. Setting <code>extract_text=True</code> invokes OCR to pull visible text; <code>extract_objects=True</code> detects visual objects and returns their metadata. This is distinct from document analysis (forms, invoices) and audio/video analysis. The output object contains <code>extracted_text</code> (raw OCR) and <code>detected_objects</code> (coordinates, labels, confidence)."
  ),
  (
    "A company has a mix of receipts (images), invoices (PDFs), and voice call recordings from customers. They want to extract key information from all three modalities using Azure AI Content Understanding and store results in a centralized database. What is the best architectural approach?",
    [
      ("Use a single routing layer that detects the file type (image, PDF, audio) and invokes the corresponding Content Understanding analyzer (image, document, audio); store all results in a unified schema with modality metadata.", True),
      ("Process images with GPT-4o vision, PDFs with a custom PDF parser, and audio with a third-party transcription service; avoid Content Understanding.", False),
      ("Use only the document analyzer for all three modalities by converting images to PDF and audio to text first.", False),
      ("Manually review each file type separately and enter data into Excel before storing in the database.", False)
    ],
    10,
    "Content Understanding is multi-modal by design. The best practice is to build a dispatcher that identifies the input format and routes to the appropriate analyzer (image, document, or audio). Each analyzer returns a <code>result</code> object with extracted fields and confidence scores. Store all results in a common database schema that includes a 'modality' column and the full extraction payload. This approach maximizes throughput, auditability, and scalability."
  ),
  (
    "You are designing a hybrid system that combines Content Understanding and GPT-4o for tax form processing. A Content Understanding document analyzer extracts fields from Form 1040 with overall 92% confidence, but one field (dependent count) has 0.71 confidence. Describe the next processing step and the advantage of this hybrid approach.",
    [
      ("The low-confidence field should be passed to GPT-4o multimodal (image + extracted JSON) with a prompt asking GPT-4o to verify the dependent count. Advantage: High-confidence fields proceed to the database immediately (fast), while only borderline fields receive expensive GPT-4o reasoning—reducing cost while maintaining accuracy.", True),
      ("Reject the entire form because one field is below 90% confidence; start over with manual review.", False),
      ("Pass only the dependent count image crop to GPT-4o and ignore all other extracted fields.", False),
      ("Use only Content Understanding and ignore the confidence score; all extracted fields are equally valid.", False)
    ],
    10,
    "The hybrid approach leverages Content Understanding's speed and efficiency for high-confidence extraction, then uses GPT-4o's reasoning ability as a selective validation layer for low-confidence fields. By passing GPT-4o both the original image and the extraction attempt, GPT-4o can reason about context ('Is the dependent count 2 or 5 based on the visual evidence?'). This balances cost, accuracy, and throughput—a production best practice in Foundry."
  )
]
