# Auto-generated by _build_ai901.py
LESSON_HTML = """
<html>
<body>
<h2>Introduction: Why Identify AI Workloads?</h2>
<p>Before deploying an AI solution in Azure, you must understand the different categories of AI workloads and match business problems to the right services. The Microsoft Azure AI platform provides specialized services for distinct workload types — from analyzing sentiment in customer reviews, to extracting handwritten text from documents, to generating images from natural language descriptions. This lesson maps real business scenarios to Azure AI products and technical capabilities.</p>

<h2>Common AI Workload Categories</h2>
<p>Modern AI falls into six primary workload categories, each solving different business challenges:</p>

<table>
<thead>
<tr>
<th style="text-align: left;">Workload Category</th>
<th style="text-align: left;">Primary Business Problem</th>
<th style="text-align: left;">Core Azure Service(s)</th>
<th style="text-align: left;">Example Use Case</th>
</tr>
</thead>
<tbody>
<tr>
<td><strong>Text Analysis</strong></td>
<td>Extract meaning, sentiment, entities from unstructured text</td>
<td>Azure AI Language</td>
<td>Analyze customer support tickets for sentiment and issues</td>
</tr>
<tr>
<td><strong>Speech Recognition &amp; Synthesis</strong></td>
<td>Convert speech to text or generate natural-sounding audio</td>
<td>Azure AI Speech</td>
<td>Build voice-enabled customer service bots or transcribe calls</td>
</tr>
<tr>
<td><strong>Computer Vision</strong></td>
<td>Extract information from images: objects, text, faces, scenes</td>
<td>Azure AI Vision</td>
<td>Digitize receipts, inspect product quality, moderate images</td>
</tr>
<tr>
<td><strong>Information Extraction</strong></td>
<td>Automatically extract structured data from documents, images, media</td>
<td>Document Intelligence, Content Understanding, Video Indexer</td>
<td>Extract invoice line items, video search by content</td>
</tr>
<tr>
<td><strong>Generative AI</strong></td>
<td>Generate new content: text, code, images, summaries</td>
<td>Azure OpenAI, Microsoft Foundry (DALL·E 3, GPT-4o)</td>
<td>Customer service chatbots, content creation, code generation</td>
</tr>
<tr>
<td><strong>Agentic AI</strong></td>
<td>Autonomous agents that plan, reason, and take actions over time</td>
<td>Azure OpenAI with function-calling, orchestration frameworks</td>
<td>Research bots, autonomous IT operations, multi-step problem solving</td>
</tr>
</tbody>
</table>

<h2>Text Analysis Workloads</h2>
<p>Text analysis is one of the most widely deployed AI workload types. Azure AI Language provides APIs to extract meaning, structure, and intent from unstructured text. Common techniques include:</p>

<table>
<thead>
<tr>
<th style="text-align: left;">Technique</th>
<th style="text-align: left;">Definition</th>
<th style="text-align: left;">Output Type</th>
<th style="text-align: left;">Business Example</th>
</tr>
</thead>
<tbody>
<tr>
<td><strong>Sentiment Analysis</strong></td>
<td>Classifies text as positive, negative, neutral, or mixed and assigns a confidence score</td>
<td>Label + score (0.0–1.0)</td>
<td>Monitor brand perception in social media</td>
</tr>
<tr>
<td><strong>Entity Detection</strong></td>
<td>Identifies named entities (people, organizations, locations, products, dates, etc.)</td>
<td>Entity type + span + confidence</td>
<td>Extract company names from contracts</td>
</tr>
<tr>
<td><strong>Keyword Extraction</strong></td>
<td>Identifies the most important phrases that summarize document content</td>
<td>Ranked list of keywords + scores</td>
<td>Auto-tag articles or support tickets</td>
</tr>
<tr>
<td><strong>Text Summarization</strong></td>
<td>Generates a concise, abstractive or extractive summary of longer text</td>
<td>Summarized text (single or multi-sentence)</td>
<td>Condense meeting notes, legal documents, research papers</td>
</tr>
</tbody>
</table>

<p><strong>Azure AI Language Example:</strong> A customer service platform ingests 10,000 support tickets daily. Using sentiment analysis, the system routes negative-sentiment tickets to senior agents and flags emerging complaint patterns.</p>

<pre><code class="language-python">
from azure.ai.language.text import TextAnalyticsClient
from azure.core.credentials import AzureKeyCredential

endpoint = "https://&lt;resource-name&gt;.cognitiveservices.azure.com/"
api_key = "&lt;your-api-key&gt;"

client = TextAnalyticsClient(endpoint=endpoint, credential=AzureKeyCredential(api_key))

# Sentiment Analysis
text = "The product quality is excellent, but shipping was delayed."
documents = [{"id": "1", "language": "en", "text": text}]

sentiment_results = client.analyze_sentiment(documents)[0]
print(f"Sentiment: {sentiment_results.sentiment}")
print(f"Scores: positive={sentiment_results.confidence_scores.positive:.2f}, "
      f"negative={sentiment_results.confidence_scores.negative:.2f}")

# Entity Recognition
entity_results = client.recognize_entities(documents)[0]
for entity in entity_results.entities:
    print(f"Entity: {entity.text}, Type: {entity.category}, Confidence: {entity.confidence_score:.2f}")
</code></pre>

<h2>Speech Recognition &amp; Synthesis Workloads</h2>
<p>Azure AI Speech enables two-way human-computer voice interaction. It uses the Whisper model for automatic speech recognition (ASR) and neural voice synthesis for text-to-speech (TTS).</p>

<blockquote>
<strong>Key Capabilities:</strong>
<ul>
<li><strong>Speech-to-Text (STT):</strong> Real-time transcription of audio streams, or batch processing of stored audio files. Supports 100+ languages.</li>
<li><strong>Text-to-Speech (TTS):</strong> Converts text to natural-sounding speech. Includes custom voice training for brand consistency.</li>
<li><strong>Speech Translation:</strong> Transcribe audio in one language and translate to another in near real-time.</li>
<li><strong>Speaker Recognition:</strong> Identify or verify speakers by voice biometrics.</li>
<li><strong>Real-time vs. Batch:</strong> Real-time APIs (latency &lt;1 second) for live conversations; batch APIs for cost-effective bulk processing.</li>
</ul>
</blockquote>

<p><strong>Azure AI Speech Example:</strong> A financial services call center uses real-time speech-to-text to generate live transcripts, sentiment analysis to detect customer frustration, and flags calls for quality review.</p>

<pre><code class="language-python">
import azure.cognitiveservices.speech as speechsdk

# Initialize the speech configuration
speech_config = speechsdk.SpeechConfig(
    subscription="&lt;your-api-key&gt;", 
    region="eastus"
)
audio_config = speechsdk.audio.AudioConfig(use_default_microphone=True)

# Speech Recognition (STT)
recognizer = speechsdk.SpeechRecognizer(speech_config=speech_config, audio_config=audio_config)
print("Say something...")
result = recognizer.recognize_once()

if result.reason == speechsdk.ResultReason.RecognizedSpeech:
    print(f"Recognized: {result.text}")
elif result.reason == speechsdk.ResultReason.NoMatch:
    print("No speech detected")

# Text-to-Speech (TTS)
speech_config.speech_synthesis_voice_name = "en-US-AriaNeural"
synthesizer = speechsdk.SpeechSynthesizer(speech_config=speech_config)
text = "Hello, how can I assist you today?"
result = synthesizer.speak_text(text)

if result.reason == speechsdk.ResultReason.SynthesizingAudioCompleted:
    print("Speech synthesis succeeded")
</code></pre>

<h2>Computer Vision Workloads</h2>
<p>Azure AI Vision analyzes images to extract objects, text, people, and scene understanding. Common capabilities include:</p>

<blockquote>
<strong>Azure AI Vision Services:</strong>
<ul>
<li><strong>Image Analysis:</strong> Describe image content, detect objects, extract tags, identify activities</li>
<li><strong>Optical Character Recognition (OCR):</strong> Extract text from images (receipts, invoices, documents)</li>
<li><strong>Object Detection:</strong> Localize and classify specific items in images with bounding boxes</li>
<li><strong>Face Detection:</strong> Identify and attribute faces (age, emotion, landmarks)</li>
<li><strong>Image Tagging &amp; Categorization:</strong> Auto-generate descriptive tags for image search and organization</li>
<li><strong>Image Generation (DALL·E 3):</strong> Generate high-quality images from natural language prompts</li>
</ul>
</blockquote>

<p><strong>Azure AI Vision Example:</strong> A retail company uses image analysis to monitor store displays. Computer vision detects out-of-stock shelves, misplaced products, and competitor pricing, then alerts store managers in real-time.</p>

<pre><code class="language-json">
{
  "modelVersion": "2024-02-01",
  "metadata": {
    "width": 1920,
    "height": 1080
  },
  "imageType": {
    "isAdultContent": false,
    "isGoryContent": false,
    "isRacyContent": false
  },
  "objects": [
    {
      "rectangle": {
        "x": 450,
        "y": 200,
        "w": 300,
        "h": 400
      },
      "object": "person",
      "confidence": 0.98
    }
  ],
  "description": {
    "tags": ["person", "smiling", "indoor", "desk", "computer"],
    "captions": [{
      "text": "a person sitting at a desk working on a laptop",
      "confidence": 0.85
    }]
  },
  "readResult": {
    "content": "Project Timeline\nPhase 1: Planning\nPhase 2: Implementation",
    "blocks": [...]
  }
}
</code></pre>

<h2>Information Extraction Workloads</h2>
<p>Information extraction automates the process of pulling structured data from unstructured sources — documents, images, audio, and video. Multiple Azure services target different modalities:</p>

<table>
<thead>
<tr>
<th style="text-align: left;">Modality</th>
<th style="text-align: left;">Extraction Task</th>
<th style="text-align: left;">Azure Service(s)</th>
<th style="text-align: left;">Example</th>
</tr>
</thead>
<tbody>
<tr>
<td><strong>Text</strong></td>
<td>Extract structured fields (names, addresses, amounts) from unstructured text</td>
<td>Azure AI Language (entity recognition)</td>
<td>Extract dates and products from emails</td>
</tr>
<tr>
<td><strong>Documents (Images/PDFs)</strong></td>
<td>Extract tables, forms, fields, signatures from invoices, contracts, receipts</td>
<td>Document Intelligence</td>
<td>Auto-populate CRM from business card photos</td>
</tr>
<tr>
<td><strong>Images</strong></td>
<td>Read text, identify objects, extract metadata from photographs</td>
<td>Azure AI Vision (OCR, object detection)</td>
<td>Digitize handwritten notes into searchable text</td>
</tr>
<tr>
<td><strong>Audio</strong></td>
<td>Transcribe speech, extract key moments, identify speakers</td>
<td>Azure AI Speech (STT) + summarization</td>
<td>Auto-generate meeting minutes from calls</td>
</tr>
<tr>
<td><strong>Video</strong></td>
<td>Extract scenes, transcripts, objects, topics, speakers over time</td>
<td>Video Indexer, Azure AI Content Understanding</td>
<td>Search video library by content or spoken keywords</td>
</tr>
</tbody>
</table>

<p><strong>Real Scenario:</strong> An insurance company receives 500+ claim forms daily (photos, scanned documents, voice recordings). They use Document Intelligence to extract claim IDs and amounts from images, Azure AI Speech to transcribe claimant interviews, and Azure AI Language to extract entities and sentiment. All data flows into a structured database for automated claim routing.</p>

<h2>Generative AI Workloads</h2>
<p>Generative AI models create new content from prompts. In Azure, these capabilities are available through Azure OpenAI (GPT-4, GPT-3.5-Turbo) and Microsoft Foundry (DALL·E 3, GPT-4o, custom models).</p>

<blockquote>
<strong>Common Generative Scenarios:</strong>
<ul>
<li><strong>Conversational AI:</strong> Customer service chatbots, intelligent assistants</li>
<li><strong>Content Generation:</strong> Write emails, summaries, marketing copy</li>
<li><strong>Code Generation:</strong> Auto-complete, code suggestions, debugging assistance</li>
<li><strong>Image Generation:</strong> Create marketing visuals, design mockups</li>
<li><strong>Question Answering:</strong> Retrieve and synthesize answers from documents (Retrieval-Augmented Generation / RAG)</li>
</ul>
</blockquote>

<h2>Agentic AI Workloads</h2>
<p>Agentic AI systems use reasoning and planning to break down complex problems into steps, call tools (APIs, databases), and execute actions autonomously. Unlike traditional chatbots that respond to individual queries, agents persist across multiple interactions and refine strategies based on feedback.</p>

<blockquote>
<strong>Agentic Capabilities:</strong>
<ul>
<li><strong>Reasoning:</strong> Plan multi-step solutions before executing</li>
<li><strong>Tool Use:</strong> Call external APIs, query databases, fetch real-time data</li>
<li><strong>Reflection:</strong> Evaluate outcomes and retry on failure</li>
<li><strong>Memory:</strong> Recall prior interactions to improve future decisions</li>
<li><strong>Autonomy:</strong> Execute tasks without human intervention (within guard rails)</li>
</ul>
</blockquote>

<p><strong>Azure Agentic Implementation:</strong> Azure OpenAI with function-calling + orchestration frameworks (LangChain, AutoGen, Semantic Kernel). Example: An IT operations agent monitors system metrics, detects anomalies, drafts incident tickets, calls runbooks, and escalates unresolved issues to humans.</p>

<h2>Matching Workloads to Azure Services</h2>
<p>Azure provides a comprehensive portfolio of AI services. When designing a solution, ask: <em>What type of data (text, speech, image, video) do I have, and what do I need to extract or generate?</em></p>

<blockquote>
<strong>Decision Framework:</strong>
<ul>
<li><strong>Unstructured text → sentiment, entities, key phrases:</strong> Azure AI Language</li>
<li><strong>Audio (speech) → transcripts, translation:</strong> Azure AI Speech</li>
<li><strong>Images → objects, text, faces, descriptions:</strong> Azure AI Vision</li>
<li><strong>Documents (forms, invoices) → structured fields:</strong> Document Intelligence</li>
<li><strong>Video → scenes, speakers, transcripts, topics:</strong> Video Indexer or Content Understanding</li>
<li><strong>Need new content (text, code, images):</strong> Azure OpenAI or Microsoft Foundry</li>
<li><strong>Complex multi-step reasoning &amp; tool use:</strong> Agentic AI (Azure OpenAI with functions)</li>
</ul>
</blockquote>

<h2>Practical Integration Pattern</h2>
<p>Most enterprise solutions combine multiple workload types. Example: <strong>An intelligent document processing pipeline</strong></p>
<ol>
<li>Ingest: User uploads a PDF invoice</li>
<li>Extract structure: Document Intelligence reads tables, amounts, dates</li>
<li>Enrich: Azure AI Language extracts vendor name and product categories</li>
<li>Generate: Azure OpenAI summarizes the invoice and suggests account coding</li>
<li>Act: If high-value or duplicate detected, create a task for human review</li>
</ol>

<h2>Key Takeaways</h2>
<ul>
<li>Azure AI workloads fall into six categories: text analysis, speech, computer vision, information extraction, generative AI, and agentic AI.</li>
<li>Each category addresses specific business problems and maps to dedicated Azure services.</li>
<li>Text analysis uses Azure AI Language for sentiment, entities, keywords, and summaries.</li>
<li>Speech recognition and synthesis are powered by Azure AI Speech (Whisper + neural voices).</li>
<li>Computer vision via Azure AI Vision extracts objects, text, and scene understanding from images.</li>
<li>Information extraction spans multiple modalities (text, documents, images, audio, video) using specialized services like Document Intelligence and Video Indexer.</li>
<li>Generative AI (Azure OpenAI, Microsoft Foundry) creates new text, code, and images.</li>
<li>Agentic AI enables autonomous reasoning and multi-step task execution with tool use and reflection.</li>
<li>Real-world solutions integrate multiple workload types into end-to-end pipelines.</li>
</ul>

<h2>Further Reading</h2>
<ul>
<li><a href="https://learn.microsoft.com/en-us/azure/ai-services/what-are-ai-services" target="_blank">What are Azure AI Services? — Microsoft Learn</a></li>
<li><a href="https://learn.microsoft.com/en-us/azure/ai-services/language/" target="_blank">Azure AI Language — Microsoft Learn</a></li>
<li><a href="https://learn.microsoft.com/en-us/azure/ai-services/speech-service/" target="_blank">Azure AI Speech — Microsoft Learn</a></li>
<li><a href="https://learn.microsoft.com/en-us/azure/ai-services/computer-vision/" target="_blank">Azure AI Vision — Microsoft Learn</a></li>
<li><a href="https://learn.microsoft.com/en-us/azure/ai-services/document-intelligence/" target="_blank">Document Intelligence — Microsoft Learn</a></li>
<li><a href="https://learn.microsoft.com/en-us/azure/ai-services/video-indexer/" target="_blank">Video Indexer — Microsoft Learn</a></li>
<li><a href="https://learn.microsoft.com/en-us/azure/openai/concepts/models" target="_blank">Azure OpenAI Models — Microsoft Learn</a></li>
<li><a href="https://learn.microsoft.com/en-us/azure/ai-services/agents" target="_blank">Azure AI Agents Framework — Microsoft Learn</a></li>
</ul>
</body>
</html>
"""

QUESTIONS = [
  (
    "Which Azure service is best suited to extract sentiment and named entities from customer review text?",
    [
      ("Azure AI Language", True),
      ("Azure AI Vision", False),
      ("Azure AI Speech", False),
      ("Document Intelligence", False)
    ],
    10,
    "Azure AI Language provides text analysis capabilities including sentiment analysis and entity recognition. Azure AI Vision analyzes images, Azure AI Speech handles audio, and Document Intelligence extracts structured fields from documents."
  ),
  (
    "A financial services company needs to transcribe phone calls from customers and translate them to Spanish for processing. Which Azure service should they use?",
    [
      ("Azure AI Speech with speech translation", True),
      ("Azure AI Language for translation only", False),
      ("Video Indexer", False),
      ("Azure OpenAI embeddings", False)
    ],
    10,
    "Azure AI Speech supports both speech-to-text (transcription) and speech translation, converting spoken audio from one language to another. Azure AI Language performs text translation but does not handle audio input. Video Indexer is for video analysis, not phone calls."
  ),
  (
    "Your company receives hundreds of invoices daily as scanned images and PDF files. You need to automatically extract line items, totals, and vendor names. Which service is most appropriate?",
    [
      ("Document Intelligence", True),
      ("Azure AI Vision object detection", False),
      ("Azure AI Language entity recognition", False),
      ("Azure OpenAI GPT-4", False)
    ],
    10,
    "Document Intelligence is purpose-built to extract structured data (tables, fields, signatures) from documents like invoices. While Azure AI Vision can read text via OCR, Document Intelligence is optimized for form and invoice extraction. Azure AI Language and Azure OpenAI are not designed for document structure extraction."
  ),
  (
    "A retail company wants to monitor store displays by analyzing photographs to detect missing products, out-of-stock shelves, and competitor pricing cards. Which Azure service provides this capability?",
    [
      ("Azure AI Vision with object detection and OCR", True),
      ("Azure AI Language with entity recognition", False),
      ("Azure AI Speech for audio analysis", False),
      ("Video Indexer for streaming feeds", False)
    ],
    10,
    "Azure AI Vision offers object detection (to identify products and shelves) and OCR (to read pricing cards and labels). This combination enables retail monitoring scenarios. Azure AI Language handles text analysis, not image analysis. Azure AI Speech analyzes audio, not images."
  ),
  (
    "Which of the following best describes the difference between generative AI and agentic AI workloads?",
    [
      ("Generative AI creates content from prompts; agentic AI plans multi-step actions, uses tools, and operates autonomously", True),
      ("Agentic AI only works with images while generative AI works with text", False),
      ("Generative AI is for chatbots; agentic AI is only for video analysis", False),
      ("Both are identical; agentic AI is just another name for generative AI", False)
    ],
    10,
    "Generative AI systems respond to individual prompts and generate new content (text, code, images). Agentic AI systems reason across multi-step problems, call external tools (APIs, databases), maintain memory, and execute actions autonomously. Both can use language models, but agentic systems add reasoning, planning, and tool use."
  ),
  (
    "Your company wants to build a customer support chatbot that answers questions by searching internal knowledge articles and synthesizing responses. This is an example of which AI workload type?",
    [
      ("Generative AI with retrieval-augmented generation (RAG)", True),
      ("Speech recognition workload", False),
      ("Computer vision workload", False),
      ("Agentic AI with autonomous decision-making", False)
    ],
    10,
    "This scenario combines generative AI (the chatbot generates responses) with information retrieval (searches knowledge articles). This pattern is called Retrieval-Augmented Generation (RAG) and is a common generative AI use case. While agentic AI could also apply, the description emphasizes content synthesis rather than autonomous multi-step planning."
  ),
  (
    "An e-learning platform ingests recorded lectures (video files) and needs to extract transcripts, identify key topics discussed, and make videos searchable by spoken content. What combination of Azure services should be used?",
    [
      ("Azure AI Speech for transcription + Video Indexer for topic extraction and indexing", True),
      ("Azure AI Vision for video analysis only", False),
      ("Document Intelligence for document extraction", False),
      ("Azure OpenAI for image generation", False)
    ],
    10,
    "Azure AI Speech transcribes audio to text. Video Indexer further analyzes video content, identifies topics, speakers, and emotions, and enables rich search. This combination delivers full video-to-searchable-content capability. Azure AI Vision is for image analysis, not video. Document Intelligence extracts structured fields from documents, not video insights."
  ),
  (
    "A healthcare organization needs an autonomous agent to monitor patient admission data, detect high-risk cases, call a triage API, retrieve relevant clinical guidelines, and send alerts to physicians. Which AI approach is most suitable?",
    [
      ("Agentic AI with function-calling and orchestration to automate multi-step workflows", True),
      ("Simple text analysis with keyword matching", False),
      ("Speech recognition for transcribing doctor notes only", False),
      ("Static image classification rules", False)
    ],
    10,
    "This scenario requires autonomous reasoning (detect risk), tool use (call triage API, retrieve guidelines), and coordination of multiple steps — hallmarks of agentic AI with function-calling. Simple text analysis lacks reasoning. Speech recognition and image classification are narrow workloads not suited to complex orchestration."
  )
]
