# Auto-generated by _build_az900.py
LESSON_HTML = """
<h2>Lesson 7: Azure Identity, Access, and Security</h2>

<h3>Introduction</h3>
<p>Identity, access, and security form the foundation of any cloud infrastructure. In Azure, Microsoft provides comprehensive identity and access management through <strong>Microsoft Entra ID</strong> (formerly Azure AD), combined with defense-in-depth strategies and advanced security monitoring. This lesson covers the key concepts, technologies, and best practices for securing Azure environments.</p>

<h3>Directory Services: Microsoft Entra ID and Microsoft Entra Domain Services</h3>
<p>Microsoft Entra ID is Azure's cloud-based identity platform that provides authentication and authorization for cloud applications, users, and devices. It serves as a central identity provider for both Microsoft 365 and thousands of SaaS applications. Microsoft Entra Domain Services (previously Azure AD Domain Services), by contrast, provides managed domain services like LDAP, Kerberos, and NTLM for legacy applications that require traditional Active Directory features without maintaining your own on-premises infrastructure.</p>

<table>
  <thead>
    <tr>
      <th>Feature</th>
      <th>Microsoft Entra ID</th>
      <th>Microsoft Entra Domain Services</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>Primary Use</td>
      <td>Cloud-native identity and access management; SaaS and Azure resources</td>
      <td>Legacy application support requiring Kerberos/NTLM; domain-joined scenarios</td>
    </tr>
    <tr>
      <td>Authentication Protocol</td>
      <td>OAuth 2.0, OpenID Connect, SAML</td>
      <td>Kerberos, NTLM, LDAP</td>
    </tr>
    <tr>
      <td>Management Model</td>
      <td>Fully managed cloud service</td>
      <td>Managed domain service; replicas deployed in virtual networks</td>
    </tr>
    <tr>
      <td>User Sync</td>
      <td>Standalone or synced from on-premises AD</td>
      <td>Automatically synced from Microsoft Entra ID</td>
    </tr>
    <tr>
      <td>Typical Scenario</td>
      <td>Multi-tenant cloud applications, Microsoft 365, conditional access</td>
      <td>Windows Server VMs needing domain services, SQL Server authentication</td>
    </tr>
    <tr>
      <td>Group Policy</td>
      <td>Not supported directly; policy managed via Intune</td>
      <td>Supported; Group Policy Objects work traditionally</td>
    </tr>
  </tbody>
</table>

<p><strong>Use Case Example:</strong> A company migrating legacy applications to Azure while adopting cloud-native SaaS would use Entra ID for cloud apps and Entra Domain Services for VMs running applications like SQL Server that require Kerberos authentication.</p>

<h3>Authentication Methods</h3>
<p>Azure supports multiple authentication methods to balance security with user experience:</p>

<p><strong>Single Sign-On (SSO):</strong> Users authenticate once and gain access to multiple applications without re-entering credentials. Entra ID enables SSO across Microsoft 365, third-party SaaS applications, and custom applications integrated with OAuth/SAML.</p>

<p><strong>Multifactor Authentication (MFA):</strong> Requires two or more verification methods:
</p>
<ul>
  <li>Something you know (password)</li>
  <li>Something you have (phone, hardware key)</li>
  <li>Something you are (biometric)</li>
</ul>

<p><strong>Passwordless Authentication Methods:</strong> These eliminate the need for passwords, reducing phishing attacks and credential compromise:
</p>
<ul>
  <li><strong>Microsoft Authenticator App:</strong> Users receive notifications on their mobile device to approve/deny authentication requests, or use it to generate time-based codes.</li>
  <li><strong>FIDO2 Security Keys:</strong> Hardware devices (USB, NFC, Bluetooth) that use cryptographic keys for authentication, resistant to phishing and credential theft.</li>
  <li><strong>Windows Hello for Business:</strong> Biometric (facial recognition, fingerprint) or PIN-based authentication on Windows devices, synchronized with Entra ID.</li>
</ul>

<p><strong>Implementation Example:</strong> An organization requires MFA for all administrative accounts. Users authenticate with their password (something you know) plus approval via the Authenticator app (something you have), ensuring that stolen credentials alone cannot compromise admin accounts.</p>

<h3>External Identities</h3>
<p>Entra ID supports multiple scenarios for collaborating with external users:</p>

<p><strong>B2B Collaboration (Business-to-Business):</strong> Invite external users from partner organizations to your Entra ID tenant with guest accounts. Guests retain their home organization credentials and are audited in your tenant logs. Useful for vendor management, contractor access, and cross-company project teams.</p>

<p><strong>B2C (Business-to-Consumer):</strong> Azure AD B2C is a separate service allowing you to manage customer identities for consumer-facing applications. Customers can sign up with email, social accounts (Google, Facebook), or local credentials without needing an enterprise Entra ID tenant.</p>

<p><strong>Cross-Tenant Access:</strong> Define trust policies between multiple Entra ID tenants. Organizations can establish inbound and outbound collaboration rules, specifying which external users can access which resources and under what conditions (e.g., require MFA, specific device compliance).</p>

<h3>Microsoft Entra Conditional Access</h3>
<p>Conditional Access applies policies that enforce access controls based on signals and conditions, moving beyond simple allow/deny to risk-based decisions.</p>

<p><strong>Signals:</strong> Contextual factors evaluated at sign-in:
</p>
<ul>
  <li>User risk (leaked credentials, impossible travel)</li>
  <li>Device state (compliant, managed, risk level)</li>
  <li>Location (trusted locations, geolocation anomalies)</li>
  <li>Application being accessed</li>
  <li>Real-time risk detection</li>
</ul>

<p><strong>Conditions and Controls:</strong> Policies specify conditions (e.g., "if user outside trusted location") and remediation actions (require MFA, block access, require compliant device).</p>

<p><strong>Example Policy (JSON representation):</strong></p>
<pre><code class="language-json">{
  "displayName": "High-Risk Sign-In Remediation",
  "conditions": {
    "userRiskLevels": ["high"],
    "clientAppTypes": ["browser", "mobileAppsAndDesktopClients"]
  },
  "grantControls": {
    "operator": "AND",
    "builtInControls": ["mfa", "compliantDevice"]
  },
  "sessionControls": {
    "signInFrequency": {
      "value": 1,
      "type": "hours"
    }
  }
}
</code></pre>

<p>This policy requires MFA and a compliant device for high-risk sign-ins, and forces re-authentication every hour for that session.</p>

<h3>Azure Role-Based Access Control (RBAC)</h3>
<p>RBAC in Azure defines who can do what on Azure resources through role assignments.</p>

<p><strong>Roles:</strong> Predefined or custom sets of permissions. Built-in roles include:
</p>
<ul>
  <li><strong>Owner:</strong> Full control, can grant permissions to others.</li>
  <li><strong>Contributor:</strong> Create and manage resources but cannot grant access.</li>
  <li><strong>Reader:</strong> View resources only.</li>
  <li><strong>Specific roles:</strong> Virtual Machine Contributor, SQL Server Contributor, etc., grant permissions scoped to specific resource types.</li>
</ul>

<p><strong>Scopes and Hierarchy:</strong> Roles are assigned at different scopes; permissions inherit downward:
</p>
<ul>
  <li><strong>Management Group:</strong> Top level, applies to multiple subscriptions.</li>
  <li><strong>Subscription:</strong> Applies to all resource groups and resources within.</li>
  <li><strong>Resource Group:</strong> Applies to all resources in the group.</li>
  <li><strong>Resource:</strong> Most granular scope (specific VM, database, storage account).</li>
</ul>

<p><strong>Assignment Example (Azure CLI):</strong></p>
<pre><code class="language-bash">az role assignment create \
  --assignee user@contoso.com \
  --role "Contributor" \
  --scope "/subscriptions/12345678-1234-1234-1234-123456789012/resourceGroups/myRG"
</code></pre>

<p>This grants the Contributor role to the user for the myRG resource group and all resources within it.</p>

<p><strong>Inheritance:</strong> A role assigned at subscription scope automatically applies to all child resource groups and resources, unless a more restrictive role is assigned at a lower scope. This hierarchical inheritance simplifies permission management at scale.</p>

<h3>Zero Trust Principles</h3>
<p>Zero Trust is a security model that assumes no implicit trust; every access request is validated regardless of origin.</p>

<p><strong>Core Principles:</strong></p>
<ul>
  <li><strong>Verify Explicitly:</strong> Always authenticate and authorize using all available data points (user identity, device state, location, application sensitivity, anomalies).</li>
  <li><strong>Least Privilege Access:</strong> Grant minimum permissions required for the task and only for the necessary duration. Remove unnecessary roles immediately after task completion.</li>
  <li><strong>Assume Breach:</strong> Design security assuming adversaries have already penetrated the network. Implement microsegmentation, encryption, monitoring, and incident response capabilities.</li>
</ul>

<p><strong>Azure Implementation:</strong> Microsoft Entra Conditional Access enforces verify-explicitly policies, RBAC with specific role assignments implements least privilege, and Microsoft Defender for Cloud detects breaches in progress, supporting the assume-breach mindset.</p>

<h3>Defense-in-Depth Model</h3>
<p>Defense-in-depth employs multiple security layers to ensure that if one fails, others still protect the system. Azure services map to each layer:</p>

<table>
  <thead>
    <tr>
      <th>Layer</th>
      <th>Focus</th>
      <th>Azure Services &amp; Controls</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>Physical</td>
      <td>Datacenter and hardware security</td>
      <td>Azure datacenters with biometric access, surveillance, and redundancy</td>
    </tr>
    <tr>
      <td>Identity</td>
      <td>User and resource authentication/authorization</td>
      <td>Microsoft Entra ID, MFA, RBAC, Conditional Access</td>
    </tr>
    <tr>
      <td>Perimeter</td>
      <td>Network boundary protection; DDoS and attack filtering</td>
      <td>Azure DDoS Protection, Web Application Firewall (WAF)</td>
    </tr>
    <tr>
      <td>Network</td>
      <td>Segmentation and traffic control within the network</td>
      <td>Network Security Groups (NSGs), Azure Firewall, Virtual Network subnets</td>
    </tr>
    <tr>
      <td>Compute</td>
      <td>Virtual machine and application security</td>
      <td>Endpoint Protection, security patches, host-based firewalls, Azure Security Center assessments</td>
    </tr>
    <tr>
      <td>Application</td>
      <td>Code and API security</td>
      <td>Secure coding practices, API gateways, dependency scanning, Key Vault for secrets</td>
    </tr>
    <tr>
      <td>Data</td>
      <td>Data protection at rest and in transit</td>
      <td>Transparent Data Encryption (TDE), Azure Storage encryption, Azure SQL encryption, TLS 1.2+</td>
    </tr>
  </tbody>
</table>

<p><strong>Practical Example:</strong> Securing a web application involves physical security (data center), identity (Entra ID authentication), perimeter (WAF blocking malicious requests), network (NSGs allowing only necessary traffic), compute (patched VMs, host firewall), application (validated input, API security), and data (encrypted database, HTTPS).</p>

<h3>Microsoft Defender for Cloud</h3>
<p>Microsoft Defender for Cloud combines Cloud Security Posture Management (CSPM) and Cloud Workload Protection (CWP) to protect Azure resources and hybrid environments.</p>

<p><strong>Cloud Security Posture Management (CSPM):</strong> Continuously assesses your cloud infrastructure against security best practices and compliance standards. Defender for Cloud scans resources, identifies misconfigurations (e.g., public storage accounts, overly permissive NSGs), and provides remediation guidance.</p>

<p><strong>Cloud Workload Protection (CWP):</strong> Provides runtime threat detection and response for virtual machines, containers, and applications. Detects suspicious process execution, lateral movement, and data exfiltration attempts.</p>

<p><strong>Secure Score:</strong> A metric (0–100) representing your security posture. Each completed recommendation increases your score. Organizations track progress over time and prioritize high-impact improvements.</p>

<p><strong>Recommendations:</strong> Defender for Cloud generates prioritized security recommendations based on:
</p>
<ul>
  <li>Resource configuration assessment</li>
  <li>Best practices comparison</li>
  <li>Threat intelligence</li>
  <li>Regulatory compliance frameworks (CIS, PCI DSS, HIPAA)</li>
</ul>

<p><strong>Example Recommendations:</strong></p>
<ul>
  <li>Enable MFA for subscriptions with owner permissions</li>
  <li>Restrict management port access via just-in-time (JIT)</li>
  <li>Enable encryption for storage accounts</li>
  <li>Apply system updates to virtual machines</li>
</ul>

<p>Organizations use Defender for Cloud dashboards to track security posture, respond to alerts (e.g., suspicious sign-in, malware detected), and ensure compliance audits succeed.</p>

<h3>Integration and Best Practices</h3>
<p>An effective Azure security strategy integrates all components:</p>
<ul>
  <li>Use Microsoft Entra ID for centralized identity management across cloud and hybrid scenarios.</li>
  <li>Enforce MFA and passwordless authentication to reduce credential attacks.</li>
  <li>Implement Conditional Access policies for risk-aware access decisions.</li>
  <li>Use RBAC with least-privilege principles and regularly audit role assignments.</li>
  <li>Apply the Zero Trust model: verify always, trust never.</li>
  <li>Layer defenses using perimeter, network, compute, application, and data protections.</li>
  <li>Monitor security posture continuously with Microsoft Defender for Cloud and act on recommendations.</li>
</ul>
"""

QUESTIONS = [
    (
        "multiple_choice",
        "Your organization is running legacy applications that require Kerberos authentication on Windows Server VMs in Azure. Which Azure directory service should you deploy?",
        [
            ("Microsoft Entra ID for centralized cloud identity management", 0),
            ("Microsoft Entra Domain Services to provide managed domain services", 1),
            ("Azure Active Directory Premium to enable advanced features", 0),
            ("Microsoft Entra External Identities for guest user management", 0),
        ],
        "Microsoft Entra Domain Services is specifically designed for legacy applications requiring Kerberos, NTLM, and domain-join capabilities. Entra ID is cloud-native and does not natively support these protocols."
    ),
    (
        "multiple_choice",
        "You want to require users to prove two different verification factors when accessing sensitive applications. Which Azure security feature should you implement?",
        [
            ("Single Sign-On to reduce login attempts", 0),
            ("Passwordless authentication with Windows Hello", 0),
            ("Multifactor Authentication combining something you know and something you have", 1),
            ("Microsoft Entra Domain Services for stronger identity verification", 0),
        ],
        "MFA requires at least two verification methods (something you know like a password, something you have like a phone or security key, or something you are like biometric). Passwordless and SSO are different authentication mechanisms."
    ),
    (
        "multiple_choice",
        "A partner company needs to access specific resources in your Azure subscription while retaining their own organization credentials. Which external identity solution is most appropriate?",
        [
            ("Azure AD B2C for consumer identity management", 0),
            ("Microsoft Entra B2B collaboration for guest access", 1),
            ("Cross-tenant RBAC for permanent access", 0),
            ("Microsoft Entra Domain Services for domain integration", 0),
        ],
        "B2B collaboration allows partner users to be added as guests using their home organization credentials. B2C is for customer identities, not partner organizations."
    ),
    (
        "multiple_choice",
        "Your security policy requires that high-risk sign-ins require multifactor authentication and the user must use a compliant device. Which Azure feature enforces these conditions automatically?",
        [
            ("Azure RBAC role assignments", 0),
            ("Microsoft Entra Conditional Access policies based on signals and controls", 1),
            ("Microsoft Defender for Cloud recommendations", 0),
            ("Windows Hello for Business authentication", 0),
        ],
        "Conditional Access applies policies based on risk signals (like high-risk sign-ins) and enforces controls (MFA, device compliance). RBAC controls resource permissions, not access conditions."
    ),
    (
        "multiple_choice",
        "You assigned the Contributor role to a user at the Subscription scope. Which Azure resources will this role automatically apply to?",
        [
            ("Only resources explicitly listed in the assignment", 0),
            ("All resource groups and resources within the subscription through permission inheritance", 1),
            ("Only resources in the default resource group", 0),
            ("Resources at the same scope only, not child scopes", 0),
        ],
        "RBAC roles assigned at a parent scope (subscription) automatically inherit to all child scopes (resource groups and individual resources) unless overridden by a more restrictive role at a lower scope."
    ),
    (
        "multiple_choice",
        "Which principle of Zero Trust security requires that every access request be validated using all available information regardless of where the request originates?",
        [
            ("Least Privilege Access", 0),
            ("Assume Breach", 0),
            ("Verify Explicitly", 1),
            ("Defense in Depth", 0),
        ],
        "Verify Explicitly is the core Zero Trust principle that mandates continuous authentication and authorization using identity, device state, location, and threat intelligence—never assuming trust based on network location or prior authentication."
    ),
    (
        "multiple_choice",
        "Your organization implements multiple security layers: identity verification with Entra ID, network segmentation with NSGs, encrypted data storage, and patched VMs. Which security model does this approach represent?",
        [
            ("Single point of defense", 0),
            ("Defense-in-Depth with multiple protective layers", 1),
            ("Zero Trust only", 0),
            ("Microsoft Defender for Cloud exclusively", 0),
        ],
        "Defense-in-Depth employs multiple security layers (physical, identity, perimeter, network, compute, application, data) so that if one layer is compromised, others continue to provide protection."
    ),
    (
        "multiple_choice",
        "Microsoft Defender for Cloud shows your Secure Score as 65 out of 100 and lists several recommendations for improvement. What does this metric represent?",
        [
            ("The percentage of your budget spent on security tools", 0),
            ("Your current security posture and priority improvements to strengthen defenses", 1),
            ("The number of active threats currently detected in your environment", 0),
            ("Your compliance status with a specific regulatory framework", 0),
        ],
        "Secure Score is a metric (0–100) representing your cloud security posture based on resource assessment and completed recommendations. Higher scores indicate better security hygiene and fewer misconfigurations."
    ),
]
