# Auto-generated by _build_az900.py
LESSON_HTML = """
<h2>Lesson 5: Azure Compute and Networking Services</h2>

<h3>Introduction</h3>
<p>Azure compute and networking services form the foundation of cloud infrastructure. In this lesson, you will learn how to select appropriate compute options, configure virtual machines and their supporting resources, explore application hosting alternatives, and design virtual networks with connectivity and security in mind. Mastering these services is critical for the AZ-900 exam, as they represent 35-40% of the skills measured.</p>

<h3>1. Comparing Compute Types: Containers, Virtual Machines, and Functions</h3>
<p>Choosing the right compute model depends on your application architecture, scalability needs, and operational overhead tolerance. Azure offers three primary compute paradigms, each suited to different workloads.</p>

<table>
<thead>
<tr><th>Aspect</th><th>Virtual Machines</th><th>Containers</th><th>Functions (Serverless)</th></tr>
</thead>
<tbody>
<tr><td>Definition</td><td>Full OS instance with complete control</td><td>Lightweight, isolated application environment</td><td>Event-driven code execution</td></tr>
<tr><td>Use Case</td><td>Complex apps, legacy systems, full OS required</td><td>Microservices, consistent deployment</td><td>Event processing, scheduled tasks, APIs</td></tr>
<tr><td>Scalability</td><td>Scale Sets for horizontal growth</td><td>Kubernetes or container orchestration</td><td>Automatic, built-in auto-scaling</td></tr>
<tr><td>Cost Model</td><td>Per-hour based on VM size and duration</td><td>Per-container resource consumption</td><td>Per-execution and memory-second</td></tr>
<tr><td>Management Overhead</td><td>High (patching, OS updates, monitoring)</td><td>Medium (image updates, orchestration)</td><td>Low (fully managed by Azure)</td></tr>
<tr><td>Cold Start</td><td>Minutes</td><td>Seconds</td><td>Milliseconds to seconds</td></tr>
<tr><td>Execution Time</td><td>Unlimited</td><td>Unlimited (depending on orchestrator)</td><td>Limited (typically 5-10 minutes max)</td></tr>
</tbody>
</table>

<p><strong>When to Choose Each:</strong></p>
<ul>
<li><strong>Virtual Machines:</strong> Deploy legacy applications, applications requiring specific OS-level configurations, databases, or enterprise software that cannot containerize.</li>
<li><strong>Containers:</strong> Build cloud-native applications with microservices architecture, ensure consistency across development, testing, and production environments, and leverage modern DevOps practices.</li>
<li><strong>Functions:</strong> Implement event-driven workflows, respond to storage changes, process messages from queues, or create lightweight REST APIs with minimal infrastructure management.</li>
</ul>

<h3>2. Virtual Machine Options in Azure</h3>
<p>Azure provides multiple VM deployment models and management tools to accommodate various organizational and workload requirements.</p>

<p><strong>Azure Virtual Machines (VMs):</strong> Single compute instances offering complete operating system control. You select the VM size (based on CPU cores, RAM, and GPU), the image (Windows Server, Linux distributions, custom images), and storage configuration. VMs support both managed and unmanaged disks; managed disks are recommended for simplified management and better availability.</p>

<p><strong>Virtual Machine Scale Sets (VMSS):</strong> Automatically manage groups of identical VMs. Scale Sets distribute load across multiple instances, support scheduled or metric-based auto-scaling policies, and integrate with Azure Load Balancer or Application Gateway. Ideal for stateless applications experiencing variable demand.</p>

<p><strong>Availability Sets:</strong> Logical grouping of VMs ensuring they are deployed across fault domains and update domains. This reduces downtime during planned maintenance and protects against hardware failures. Typically used for non-clustered applications requiring high availability without the complexity of Scale Sets.</p>

<p><strong>Azure Virtual Desktop (AVD):</strong> Remote desktop virtualization platform enabling secure access to Windows or Linux desktops and applications. Users connect from any device; Azure manages infrastructure, patching, and multi-session capabilities. Optimizes licensing costs through Windows 10/11 Enterprise and Microsoft 365 support.</p>

<h3>3. Resources Required for Virtual Machines</h3>
<p>Deploying a VM requires provisioning and configuring multiple supporting resources:</p>

<ul>
<li><strong>VM Size:</strong> Determines CPU cores, RAM, disk I/O performance, and network bandwidth. Sizes range from micro instances (testing) to specialized GPU instances (AI workloads). Each size family (general purpose, compute optimized, memory optimized, storage optimized, GPU) targets specific workload patterns.</li>
<li><strong>OS Image:</strong> Base operating system template (Windows Server, Ubuntu, CentOS, RHEL, etc.) or custom images built in your organization. Images include pre-installed software, security baselines, and configurations.</li>
<li><strong>Storage/Disks:</strong> OS disk (boot drive), data disks (application storage), and temporary disks. Azure managed disks offer SSD and HDD options with automatic failover and backup. Premium SSD disks provide higher IOPS for performance-critical workloads.</li>
<li><strong>Network Interface Card (NIC):</strong> Connects the VM to a virtual network. Each NIC has a private IP address; public IP addresses are optional and enable internet access. NICs support multiple IP addresses for hosting multiple services.</li>
<li><strong>Network Security Group (NSG):</strong> Virtual firewall controlling inbound and outbound traffic using allow/deny rules. Rules are processed in priority order. NSGs are essential for enforcing least-privilege network access.</li>
<li><strong>Virtual Network (VNet) and Subnet:</strong> VNets define IP address space; subnets partition that space and apply policies like NSGs. VMs must be deployed into a subnet.</li>
<li><strong>Storage Account (optional):</strong> For diagnostic logs, boot diagnostics, or unmanaged disks. Modern deployments use managed disks and Application Insights, reducing reliance on storage accounts.</li>
<li><strong>Scaling Configuration:</strong> For Scale Sets, define minimum, maximum, and desired instance counts, auto-scale rules based on metrics (CPU, memory), or scheduled scaling policies.</li>
</ul>

<h3>4. Application Hosting Options</h3>
<p>Beyond VMs, Azure provides specialized platforms for different application architectures.</p>

<p><strong>Azure App Service (Web Apps):</strong> Platform-as-a-Service (PaaS) for hosting web applications, REST APIs, and mobile back-ends. Supports ASP.NET, Node.js, Python, Java, and more. Features include built-in CI/CD integration, authentication, SSL certificates, auto-scaling, and staging slots for zero-downtime deployments. Developers focus on code while Azure manages infrastructure patching and scaling.</p>

<p><strong>Azure Container Instances (ACI):</strong> Simplest way to run containers in Azure without managing orchestration. Ideal for short-lived tasks, batch processing, or event-driven workloads. Billing is per second of container execution. No scaling orchestration; use for individual tasks or small workloads.</p>

<p><strong>Azure Kubernetes Service (AKS):</strong> Managed Kubernetes cluster for production-grade container orchestration. Handles rolling updates, self-healing, load balancing, and persistent storage integration. Requires Kubernetes knowledge but offers maximum flexibility for complex microservices architectures.</p>

<p><strong>Azure Container Apps:</strong> Managed Kubernetes alternative built for microservices and event-driven workloads. Combines ACI simplicity with Kubernetes capabilities. Auto-scales based on HTTP requests or event sources. Lower operational complexity than AKS while retaining powerful container management.</p>

<p><strong>Comparison and Selection Guidance:</strong></p>
<ul>
<li><strong>App Service:</strong> Choose for traditional web applications, .NET framework apps, or when you need turn-key hosting with minimal Kubernetes knowledge.</li>
<li><strong>ACI:</strong> Choose for one-off containers, batch jobs, or testing container workloads without cluster overhead.</li>
<li><strong>AKS:</strong> Choose for enterprise microservices requiring complex orchestration, multiple replicas, rolling deployments, and multi-team management.</li>
<li><strong>Container Apps:</strong> Choose for microservices with event-driven triggers or HTTP endpoints when AKS complexity is unnecessary.</li>
<li><strong>VMs:</strong> Choose when application-level requirements demand full OS control or legacy compatibility.</li>
</ul>

<p><strong>Example: App Service Configuration (YAML):</strong></p>
<pre><code class="language-yaml">apiVersion: v1
kind: AppServiceConfig
metadata:
  name: my-web-app
spec:
  runtime:
    name: dotnet
    version: "6.0"
  tier: Standard
  capacity: 2
  scaling:
    minInstances: 2
    maxInstances: 10
  autoscaleRule:
    metric: CpuPercentage
    threshold: 75
    scaleOutCount: 2
    scaleOutCooldown: 5m
  slots:
    - name: staging
      enabled: true
</code></pre>

<p><strong>Azure CLI Example: Creating a VM:</strong></p>
<pre><code class="language-bash">az vm create \
  --resource-group myResourceGroup \
  --name myVM \
  --image UbuntuLTS \
  --size Standard_B2s \
  --admin-username azureuser \
  --generate-ssh-keys \
  --nsg-rule SSH \
  --public-ip-sku Standard
</code></pre>

<h3>5. Virtual Networking: Architecture and Connectivity</h3>
<p>Azure Virtual Networks (VNets) provide isolated network environments where you deploy resources and control communication.</p>

<p><strong>Virtual Networks (VNets) and Subnets:</strong> VNets define an address space (e.g., 10.0.0.0/16). Subnets partition this space (e.g., 10.0.1.0/24 for the web tier, 10.0.2.0/24 for the database tier) and serve as deployment boundaries. NSGs and route tables apply at the subnet level, enabling granular network policies.</p>

<p><strong>VNet Peering:</strong> Direct connection between two VNets enabling traffic to flow as if on the same network. Peering can be regional (same Azure region) or global (different regions). Uses Microsoft backbone, not the public internet. Regional peering is free; global peering incurs minimal charges. No bandwidth limitations; provides consistent low-latency communication.</p>

<p><strong>Azure DNS:</strong> Managed DNS hosting for domain name resolution. Supports public and private DNS zones. Private zones resolve only from VNets (hybrid DNS for on-premises lookups). No need to manage DNS infrastructure; Azure handles redundancy and failover.</p>

<p><strong>VPN Gateway (Site-to-Site and Point-to-Site):</strong> Encrypts traffic over the public internet between your corporate network and Azure.</p>
<ul>
<li><strong>Site-to-Site (S2S) VPN:</strong> Persistent connection between on-premises data center and Azure VNet. Requires on-premises VPN device. Useful for hybrid environments where multiple users/applications need access. Bandwidth typically 1-4 Gbps.</li>
<li><strong>Point-to-Site (P2S) VPN:</strong> Secure connection from individual client machines to Azure VNet. Uses protocols like OpenVPN or SSTP. Suitable for remote workers accessing corporate resources. Each connection is independent.</li>
</ul>

<p><strong>ExpressRoute:</strong> Private, dedicated network connection from on-premises to Azure, Microsoft 365, or Dynamics 365. Does not traverse the public internet. Provides consistent throughput, lower latency, and better security than internet-based VPNs. Available in various bandwidth tiers (50 Mbps to 100 Gbps). Higher cost but critical for mission-critical workloads requiring SLA guarantees.</p>

<h3>6. Public and Private Endpoints</h3>
<p>Controlling data exposure is essential for security. Azure provides public and private endpoint models.</p>

<p><strong>Public Endpoints:</strong> Resources like storage accounts, databases, or APIs accessible from the internet. Security relies on authentication (access keys, managed identities, API keys) and NSG rules. Suitable for public-facing services; requires careful credential management to prevent unauthorized access.</p>

<p><strong>Private Link and Private Endpoints:</strong> Creates private connectivity to Azure services within your VNet. Traffic never traverses the public internet; uses private IP addresses. Supported for storage accounts, SQL databases, Key Vault, App Service, Cognitive Services, and more. Enables secure service consumption without exposing resources to the internet. Clients connect as if the service exists within their VNet.</p>

<table>
<thead>
<tr><th>Service/Feature</th><th>Internet Exposure</th><th>Encryption</th><th>Best For</th><th>Cost</th></tr>
</thead>
<tbody>
<tr><td>Public Endpoint</td><td>Internet-accessible via FQDN or IP</td><td>HTTPS/TLS for transport; authentication required</td><td>Public APIs, web apps, content delivery</td><td>No additional cost (standard resources)</td></tr>
<tr><td>Private Endpoint (Private Link)</td><td>VNet-only; no internet exposure</td><td>Private channel; traffic stays within Azure backbone</td><td>Databases, storage, Key Vault, internal services</td><td>Minimal per-endpoint charge (~$0.01/hour)</td></tr>
<tr><td>VPN Gateway (S2S)</td><td>Encrypted tunnel over internet</td><td>IPSec encryption; strong security</td><td>Hybrid connectivity, on-premises integration</td><td>Per hour + data egress</td></tr>
<tr><td>VPN Gateway (P2S)</td><td>Encrypted tunnel from client device</td><td>SSTP or OpenVPN encryption</td><td>Remote worker access, temporary connectivity</td><td>Per connection + data egress</td></tr>
<tr><td>ExpressRoute</td><td>Private dedicated circuit, no internet</td><td>Physical isolation; no encryption needed (inherently secure)</td><td>Mission-critical, hybrid workloads, high throughput</td><td>Premium; based on bandwidth tier</td></tr>
</tbody>
</table>

<p><strong>Architecture Scenario:</strong> A healthcare organization stores patient records in Azure SQL Database. Using a private endpoint ensures data never crosses the public internet. On-premises clinics connect via ExpressRoute, while remote doctors use P2S VPN. Web-facing API endpoints use public connectivity with managed identities for authentication. NSGs and firewall rules enforce least-privilege access at each layer.</p>

<h3>Summary</h3>
<p>Azure compute and networking services provide multiple pathways to architect scalable, secure, and manageable cloud solutions. Select VMs for full OS control, containers for cloud-native workloads, or serverless functions for event-driven simplicity. Combine specialized hosting options like App Service or AKS for different application types. Design virtual networks with subnets, peering, and NSGs for isolation and security. Leverage Private Link for secure service consumption, VPN Gateways for hybrid connectivity, and ExpressRoute for dedicated, high-performance links to on-premises infrastructure. Mastering these services enables you to build robust cloud architectures aligned with organizational requirements.</p>
"""

QUESTIONS = [
    (
        "multiple_choice",
        "Your organization needs to run a batch image processing job that completes in 30 seconds. You want to avoid managing infrastructure and paying for idle time. Which compute option best fits this requirement?",
        [
            ("Azure Virtual Machines with auto-shutdown", 0),
            ("Azure Container Instances", 1),
            ("Azure App Service", 0),
            ("Azure Kubernetes Service", 0),
        ],
        "Azure Container Instances bills per second of execution, making it cost-effective for short-lived tasks. VMs incur charges whether running or stopped. App Service is for persistent web applications. AKS adds orchestration overhead unsuitable for single jobs."
    ),
    (
        "multiple_choice",
        "You are deploying a web application that must survive server failures within the same Azure region. The application is stateless and traffic varies significantly throughout the day. Which resource combination ensures both high availability and cost efficiency?",
        [
            ("Single VM with a public IP and manual restart", 0),
            ("Virtual Machine Scale Set configured with auto-scaling rules", 1),
            ("Two VMs in an Availability Set with manual management", 0),
            ("Azure App Service on the Free tier", 0),
        ],
        "A Virtual Machine Scale Set automatically manages multiple instances across fault domains, scales based on demand, and replaces failed instances. Availability Sets require manual traffic management. Single VMs have no redundancy. Free tier App Service may be insufficient for variable traffic."
    ),
    (
        "multiple_choice",
        "Your organization operates an on-premises data center 50 kilometers from an Azure region. The company requires consistent, low-latency, dedicated bandwidth for mission-critical applications with SLA guarantees. Which connectivity option is most appropriate?",
        [
            ("Site-to-Site VPN through a commercial internet provider", 0),
            ("Point-to-Site VPN for employee remote access", 0),
            ("Azure ExpressRoute", 1),
            ("Public endpoint with DDoS protection", 0),
        ],
        "ExpressRoute provides a private, dedicated connection with guaranteed bandwidth and SLA support. S2S and P2S VPNs use the public internet, introducing variability. Public endpoints lack the isolation and performance guarantees required."
    ),
    (
        "multiple_choice",
        "You are containerizing a microservices application and need automatic scaling based on HTTP request volume, built-in Kubernetes features, but without the complexity of managing a Kubernetes control plane. Which service best matches these requirements?",
        [
            ("Azure App Service", 0),
            ("Azure Container Instances", 0),
            ("Azure Container Apps", 1),
            ("Azure Virtual Machines with Docker", 0),
        ],
        "Azure Container Apps provides managed Kubernetes scaling for HTTP-triggered workloads without control plane management. App Service is for traditional web apps. ACI lacks orchestration. VMs require manual management."
    ),
    (
        "multiple_choice",
        "Your organization stores financial records in Azure SQL Database and wants to ensure data never traverses the public internet, even encrypted. Which networking feature enables this?",
        [
            ("Firewall rules allowing only internal IPs", 0),
            ("Private endpoint and Private Link", 1),
            ("Network Security Group with restrictive rules", 0),
            ("Site-to-Site VPN to the database", 0),
        ],
        "Private Link creates a private endpoint within your VNet, ensuring traffic uses Azure's backbone. NSG rules and firewalls still allow internet paths. S2S VPN is for network-to-network connectivity, not database access."
    ),
    (
        "multiple_choice",
        "You are deploying web and database tiers in the same virtual network. The web tier must accept inbound internet traffic on port 443; the database must only communicate with the web tier on port 3306. How should you configure network security?",
        [
            ("Single NSG allowing all inbound traffic for simplicity", 0),
            ("Separate NSGs per subnet: web tier allows port 443 from internet, database tier allows port 3306 only from web subnet", 1),
            ("Database in a separate VNet with peering to the web tier", 0),
            ("All traffic through a VPN Gateway", 0),
        ],
        "Separate NSGs per subnet implement least-privilege network access. A single permissive NSG violates security principles. Peering doesn't replace NSGs. VPN Gateways are for external connectivity, not internal segmentation."
    ),
    (
        "multiple_choice",
        "You have two virtual networks in different Azure regions that must communicate with low latency and no bandwidth charges. Which solution is most cost-effective?",
        [
            ("Global VNet peering", 1),
            ("ExpressRoute with global reach", 0),
            ("Site-to-Site VPN", 0),
            ("Public endpoints with firewall rules", 0),
        ],
        "Global VNet peering connects regions with minimal charge and Microsoft backbone latency. ExpressRoute is premium and charges for data. S2S VPN uses the internet. Public endpoints without VNets bypass network isolation."
    ),
    (
        "multiple_choice",
        "Your organization needs to host a legacy Windows application requiring full OS-level customization and complex dependencies. Containerization is not feasible. Which hosting option is most suitable?",
        [
            ("Azure App Service with a custom runtime", 0),
            ("Azure Container Instances", 0),
            ("Azure Virtual Machines", 1),
            ("Azure Functions with a Windows runtime", 0),
        ],
        "Azure Virtual Machines provide complete OS control required for legacy applications with complex dependencies. App Service has platform constraints. Containers are ruled out. Functions have execution time limits and are for event-driven workloads."
    ),
]
