# Auto-generated by _build_az900.py
LESSON_HTML = """
<h2>Lesson 3: Cloud Concepts</h2>

<h3>What is Cloud Computing?</h3>
<p>Cloud computing is the delivery of computing services—including servers, storage, databases, networking, software, analytics, and intelligence—over the Internet (the "cloud") to offer faster innovation, flexible resources, and economies of scale. Rather than owning and maintaining physical infrastructure, organizations can access these services on-demand from cloud providers.</p>
<p>Key characteristics of cloud computing include:</p>
<ul>
<li><strong>On-demand self-service:</strong> Resources can be provisioned without human interaction with the service provider.</li>
<li><strong>Broad network access:</strong> Services are available over the network and accessed through standard mechanisms.</li>
<li><strong>Resource pooling:</strong> Provider resources are pooled to serve multiple consumers using a multi-tenant model.</li>
<li><strong>Rapid elasticity:</strong> Resources can be quickly provisioned and released to scale rapidly outward and inward.</li>
<li><strong>Measured service:</strong> Resource usage is monitored, controlled, and reported transparently.</li>
</ul>

<h3>The Shared Responsibility Model</h3>
<p>The shared responsibility model defines which security and compliance tasks are handled by the cloud provider versus the customer. Understanding this division is critical for designing secure cloud solutions.</p>

<table>
<thead>
<tr>
<th>Responsibility Area</th>
<th>On-Premises</th>
<th>IaaS</th>
<th>PaaS</th>
<th>SaaS</th>
</tr>
</thead>
<tbody>
<tr>
<td><strong>Physical Security</strong></td>
<td>Customer</td>
<td>Provider</td>
<td>Provider</td>
<td>Provider</td>
</tr>
<tr>
<td><strong>Network &amp; Connectivity</strong></td>
<td>Customer</td>
<td>Shared</td>
<td>Provider</td>
<td>Provider</td>
</tr>
<tr>
<td><strong>Operating System</strong></td>
<td>Customer</td>
<td>Customer</td>
<td>Provider</td>
<td>Provider</td>
</tr>
<tr>
<td><strong>Middleware &amp; Runtime</strong></td>
<td>Customer</td>
<td>Customer</td>
<td>Provider</td>
<td>Provider</td>
</tr>
<tr>
<td><strong>Applications</strong></td>
<td>Customer</td>
<td>Customer</td>
<td>Customer</td>
<td>Provider</td>
</tr>
<tr>
<td><strong>Data &amp; Access Control</strong></td>
<td>Customer</td>
<td>Customer</td>
<td>Customer</td>
<td>Shared</td>
</tr>
<tr>
<td><strong>Identity &amp; Directory</strong></td>
<td>Customer</td>
<td>Customer</td>
<td>Shared</td>
<td>Shared</td>
</tr>
</tbody>
</table>

<p><blockquote><strong>Note:</strong> In all cloud models, the customer is always responsible for the data they store, who can access it, and compliance with regulatory requirements. The cloud provider is always responsible for the physical infrastructure and network perimeter security.</blockquote></p>

<h3>Cloud Models: Public, Private, and Hybrid</h3>

<p><strong>Public Cloud:</strong> Resources are owned and operated by a third-party cloud provider and delivered over the public Internet. Multiple organizations share the same infrastructure.</p>
<ul>
<li><strong>Use cases:</strong> Startups and small businesses needing scalability without capital investment; development and testing environments; web applications and APIs; content delivery; big data analysis.</li>
<li><strong>Advantages:</strong> Lower costs, no capital expenditure, high scalability, automatic updates.</li>
<li><strong>Disadvantages:</strong> Less control over infrastructure, potential security concerns, shared resources.</li>
</ul>

<p><strong>Private Cloud:</strong> Cloud infrastructure is maintained on a company's own premises or hosted by a third party exclusively for that organization. Resources are not shared with other organizations.</p>
<ul>
<li><strong>Use cases:</strong> Organizations with strict regulatory compliance requirements; enterprises needing complete control over their environment; mission-critical applications requiring predictable performance.</li>
<li><strong>Advantages:</strong> Greater security and control, customization, compliance flexibility.</li>
<li><strong>Disadvantages:</strong> Higher costs, requires in-house expertise, limited scalability advantages.</li>
</ul>

<p><strong>Hybrid Cloud:</strong> Combines public and private cloud resources with orchestration between them, allowing data and applications to move between environments.</p>
<ul>
<li><strong>Use cases:</strong> Burst capacity needs; phased cloud migration; applications requiring both on-premises legacy systems and cloud services; disaster recovery and business continuity.</li>
<li><strong>Advantages:</strong> Flexibility to leverage both environments, cost optimization, business continuity.</li>
<li><strong>Disadvantages:</strong> Complexity in management, potential security concerns between environments.</li>
</ul>

<h3>Consumption-Based Model and Cloud Pricing</h3>

<p>The consumption-based model is a key advantage of cloud computing. Instead of purchasing and maintaining expensive infrastructure that may be underutilized, you pay only for the resources you consume.</p>

<p><strong>Pay-As-You-Go:</strong> You pay for resources as you use them, with no long-term commitment. This model is ideal for unpredictable workloads and provides maximum flexibility. However, costs can be higher per unit of consumption compared to reserved capacity.</p>

<p><strong>Reserved Instances:</strong> You commit to using a service for a specified period (typically 1 or 3 years) in exchange for a significant discount (up to 70% off on-demand prices). This is suitable for predictable, consistent workloads.</p>

<p><strong>Spot Pricing:</strong> Available on unused cloud provider capacity at steep discounts (up to 90% off). However, instances can be terminated with minimal notice, making this suitable only for fault-tolerant, flexible workloads.</p>

<p><strong>Savings Plans:</strong> Commitment-based pricing that offers flexibility across compute services. You commit to a certain amount of spending for one or three years and receive discounts on that usage.</p>

<p><strong>Azure Hybrid Benefit:</strong> Allows you to use existing on-premises software licenses (particularly Microsoft licenses) in Azure, reducing your cloud costs significantly. This is valuable for organizations with existing Microsoft licensing agreements.</p>

<h3>Serverless Computing</h3>

<p>Serverless is a cloud computing execution model where the cloud provider automatically manages the infrastructure, scaling, and resource allocation. Developers focus solely on writing code without managing servers.</p>

<p>Key characteristics:</p>
<ul>
<li>Event-driven execution: Code runs in response to specific events or triggers.</li>
<li>Automatic scaling: Scales from zero to thousands of concurrent executions automatically.</li>
<li>Pay-per-execution: You pay only for the actual compute time used, typically measured in milliseconds.</li>
<li>No server management: No need to provision, patch, or maintain servers.</li>
<li>Stateless: Functions are typically stateless, though state can be managed via external services.</li>
</ul>

<p><strong>Example:</strong> Azure Functions, a serverless compute service, can automatically run code in response to HTTP requests, timer triggers, or messages from Azure services—all without managing any servers.</p>

<h3>Benefits of Cloud Computing</h3>

<p><strong>High Availability and Scalability</strong></p>
<ul>
<li><strong>High Availability:</strong> Cloud services ensure that applications remain available even if individual components fail. Azure provides Service Level Agreements (SLAs) guaranteeing 99.9% to 99.99% uptime depending on the service.</li>
<li><strong>Vertical Scaling:</strong> Adding more power (CPU, RAM) to existing resources to handle increased load. Suitable for single-server applications.</li>
<li><strong>Horizontal Scaling:</strong> Adding more instances of resources to distribute load. Provides better fault tolerance and is ideal for distributed applications.</li>
</ul>

<p><strong>Reliability and Predictability</strong></p>
<ul>
<li><strong>Performance Predictability:</strong> Cloud providers guarantee consistent performance through SLAs and built-in redundancy. Auto-scaling ensures performance remains predictable even as demand fluctuates.</li>
<li><strong>Cost Predictability:</strong> With consumption-based pricing and tools like Azure Cost Management, costs are predictable and trackable. You can forecast expenses based on usage patterns and adjust accordingly.</li>
</ul>

<p><strong>Security and Governance</strong></p>
<ul>
<li>Cloud providers invest heavily in physical security, network monitoring, and threat detection.</li>
<li>Azure provides compliance with numerous standards (ISO, HIPAA, SOC 2, PCI-DSS) and regulatory frameworks.</li>
<li>Centralized identity and access management through Azure Active Directory ensures consistent security policies.</li>
<li>Encryption options for data in transit and at rest protect sensitive information.</li>
<li>Audit logs and monitoring services provide visibility into who accesses what resources and when.</li>
</ul>

<p><strong>Manageability</strong></p>
<ul>
<li><strong>Management of the cloud:</strong> Azure provides web portal, CLI tools, and APIs for managing cloud resources with minimal effort.</li>
<li><strong>Management in the cloud:</strong> Deploy and manage applications, patch updates, configure backups—all through cloud-based tools rather than on-premises administration.</li>
</ul>

<h3>Cloud Service Types: IaaS, PaaS, and SaaS</h3>

<p>Cloud services are categorized by the level of responsibility and control transferred to the provider:</p>

<table>
<thead>
<tr>
<th>Service Type</th>
<th>Definition</th>
<th>Customer Manages</th>
<th>Provider Manages</th>
<th>Example Azure Services</th>
<th>Use Cases</th>
</tr>
</thead>
<tbody>
<tr>
<td><strong>IaaS</strong> (Infrastructure as a Service)</td>
<td>Computing resources delivered over the Internet: compute, storage, networking. You rent IT infrastructure on a pay-as-you-go basis.</td>
<td>Operating system, middleware, runtime, applications, data</td>
<td>Physical infrastructure, virtualization, servers, storage, networking</td>
<td>Azure Virtual Machines, Azure App Service (in IaaS tier), Azure Storage, Virtual Networks</td>
<td>Web hosting, development and testing, high-performance computing, storage and backup, application development</td>
</tr>
<tr>
<td><strong>PaaS</strong> (Platform as a Service)</td>
<td>A complete development and deployment environment in the cloud. Build, test, and deploy applications without managing underlying infrastructure.</td>
<td>Applications, data</td>
<td>Operating system, middleware, runtime, infrastructure</td>
<td>Azure App Service, Azure SQL Database, Azure Cosmos DB, Azure Functions, Azure Logic Apps</td>
<td>Rapid application development, API development and management, microservices architectures, business analytics and intelligence</td>
</tr>
<tr>
<td><strong>SaaS</strong> (Software as a Service)</td>
<td>Fully managed cloud applications delivered via web browser. No installation or maintenance required on client machines.</td>
<td>Configuration and user management</td>
<td>Everything: application, data, infrastructure, updates, security</td>
<td>Microsoft 365, Dynamics 365, Azure DevOps Services, GitHub</td>
<td>Email and collaboration, business applications, customer relationship management, project management, communication</td>
</tr>
</tbody>
</table>

<h3>Working with Azure: Practical Example</h3>

<p>Here is an example of deploying a virtual machine using Azure CLI, an IaaS approach:</p>

<pre><code class="language-bash"># Create a resource group
az group create --name myResourceGroup --location eastus

# Create a virtual machine
az vm create \
  --resource-group myResourceGroup \
  --name myVM \
  --image UbuntuLTS \
  --size Standard_B2s \
  --admin-username azureuser \
  --generate-ssh-keys

# Open port 80 for web traffic
az vm open-port --resource-group myResourceGroup --name myVM --port 80

# Get the public IP address
az vm show --resource-group myResourceGroup --name myVM -d --query publicIps --output tsv
</code></pre>

<p>In contrast, deploying a web application using PaaS (Azure App Service) requires no infrastructure management—you simply deploy your code, and Azure handles scaling, updates, and infrastructure.</p>
"""

QUESTIONS = [
    (
        "multiple_choice",
        "Your organization is planning a migration to the cloud. You need to ensure that your on-premises Microsoft SQL Server licenses can be reused in Azure to reduce costs. Which pricing model should you utilize?",
        [
            ("Pay-as-you-go pricing for all Azure services", 0),
            ("Azure Hybrid Benefit", 1),
            ("Spot instances for database workloads", 0),
            ("Reserved instances for one year only", 0),
        ],
        "Azure Hybrid Benefit allows organizations to use existing on-premises software licenses (particularly Microsoft licenses) in Azure, providing significant cost reductions. This is the specific mechanism designed for reusing existing licenses in the cloud."
    ),
    (
        "multiple_choice",
        "Your company runs a predictable, mission-critical application that requires consistent performance and complete control over the infrastructure. The application must meet strict regulatory compliance requirements that your cloud provider cannot guarantee. Which cloud model is most appropriate?",
        [
            ("Public cloud hosted with the largest provider", 0),
            ("Hybrid cloud using both public and private resources", 0),
            ("Private cloud", 1),
            ("Community cloud with other compliant organizations", 0),
        ],
        "Private cloud is maintained exclusively for your organization and provides complete control over infrastructure and customization. It is ideal for mission-critical applications with strict regulatory requirements and is the only model that guarantees full control and compliance customization."
    ),
    (
        "multiple_choice",
        "You are designing a serverless application using Azure Functions. Your function processes data whenever a file is uploaded to Azure Blob Storage. Which characteristics best describe the billing model you will experience?",
        [
            ("You pay a fixed monthly fee regardless of executions", 0),
            ("You pay based on the number of executions and compute time consumed, with automatic scaling to handle variable load", 1),
            ("You pay only if the function exceeds one million executions per month", 0),
            ("You must purchase reserved capacity in advance to use serverless services", 0),
        ],
        "Serverless computing uses a consumption-based billing model where you pay per execution and compute time (typically per millisecond). The service automatically scales from zero to handle demand without purchasing reserved capacity, making it cost-effective for variable workloads."
    ),
    (
        "multiple_choice",
        "Your organization is implementing a web application with unpredictable traffic spikes. You want to ensure high availability and the ability to handle traffic spikes efficiently. Which scaling approach, combined with cloud benefits, best addresses this requirement?",
        [
            ("Vertical scaling to add more CPU to each server", 0),
            ("Purchasing additional on-premises servers in advance", 0),
            ("Horizontal scaling with automatic load distribution across multiple instances", 1),
            ("Manual scaling triggered by system administrators daily", 0),
        ],
        "Horizontal scaling adds more instances to distribute the load and is ideal for unpredictable traffic spikes. Combined with cloud auto-scaling capabilities, it provides automatic elasticity and high availability without manual intervention or purchasing excess capacity in advance."
    ),
    (
        "multiple_choice",
        "A startup is deploying an e-commerce platform and needs rapid development with minimal infrastructure management. The team wants to focus on business logic rather than server administration, patching, or scaling infrastructure. Which service type best fits this requirement?",
        [
            ("Infrastructure as a Service (IaaS)", 0),
            ("Platform as a Service (PaaS)", 1),
            ("Software as a Service (SaaS)", 0),
            ("On-premises infrastructure", 0),
        ],
        "PaaS provides a complete development and deployment environment where the cloud provider manages all infrastructure, runtime, and middleware. The development team can focus entirely on applications and business logic, making it ideal for startups wanting to accelerate time-to-market."
    ),
    (
        "multiple_choice",
        "You are comparing cloud service models regarding security responsibilities. Under the shared responsibility model in a SaaS offering (such as Microsoft 365), which element is the cloud provider primarily responsible for securing?",
        [
            ("User email data and personal files stored in the service", 0),
            ("User credentials and authentication mechanisms for accessing the service", 0),
            ("The underlying application infrastructure, servers, and network perimeter", 1),
            ("User access permissions and who can view shared documents", 0),
        ],
        "In SaaS, the provider is responsible for the application infrastructure, servers, networks, and physical security. Users retain responsibility for data protection (access control, encryption keys for sensitive data) and identity governance (managing who accesses the service and shared resources)."
    ),
    (
        "multiple_choice",
        "Your organization requires the ability to use existing on-premises resources for some workloads while leveraging cloud services for others, with orchestration between environments for temporary burst capacity during peak seasons. Which cloud model provides this capability?",
        [
            ("Public cloud exclusively", 0),
            ("Private cloud exclusively", 0),
            ("Hybrid cloud", 1),
            ("Community cloud with other organizations", 0),
        ],
        "Hybrid cloud combines public and private resources with orchestration between them. This enables organizations to maintain on-premises systems while leveraging cloud services for burst capacity, scalability, and disaster recovery without fully committing to the public cloud."
    ),
    (
        "multiple_choice",
        "A developer needs to deploy a custom machine learning model that requires significant compute resources for model training on variable schedules. The model processes customer data that is sensitive. Cost must be minimized, but data security is non-negotiable. Which combination of cloud model and service type is most appropriate?",
        [
            ("Public cloud with SaaS to ensure third-party security management", 0),
            ("Private cloud with IaaS for complete control and cost optimization through careful resource management", 1),
            ("Public cloud with spot instances to minimize cost without concern for data residency", 0),
            ("Hybrid cloud with only public cloud resources for model training", 0),
        ],
        "Private cloud with IaaS provides complete control over sensitive customer data and infrastructure compliance while allowing efficient resource management to optimize costs. A private cloud ensures data stays within your control and meets security requirements, while IaaS provides the flexibility to manage compute resources for variable machine learning workloads."
    ),
]
