"""Build PL-300 (Power BI) Lessons 3-8 + quizzes from agent outputs.
Mirrors _build_az900.py.
"""
import ast
import importlib
import re
import sys
from pathlib import Path

from app import app, db, Course, Lesson, Quiz, Question, QuestionOption

WORKSPACE = Path(__file__).resolve().parent
AGENT = Path(r"c:\Users\hp\AppData\Roaming\Code\User\workspaceStorage\25f723a0a07d7e81c8ab2371048eef31\GitHub.copilot-chat\chat-session-resources\7cdafd4c-d586-4bc9-9b47-be8b70ffb17b")

SPEC = [
    (3, "Prepare the Data",
     "Practise connecting to sources, storage modes, query folding and shaping data in Power Query.",
     AGENT / "toolu_vrtx_01R47RtVTaBDG9qtzzq3ZKdz__vscode-1779227169249" / "content.txt"),
    (4, "Model the Data",
     "Practise star schema, relationships, calculated columns vs measures and date tables.",
     AGENT / "toolu_vrtx_01JVSJNxyeWTvMWoigAGKKre__vscode-1779227169250" / "content.txt"),
    (5, "DAX Fundamentals",
     "Check your understanding of DAX: filter context, CALCULATE, iterators, variables and time intelligence.",
     AGENT / "toolu_vrtx_01GbueNYRYTT9EfmbNnLpKe3__vscode-1779227169251" / "content.txt"),
    (6, "Visualize and Analyze the Data",
     "Practise choosing visuals, interactions, drillthrough, bookmarks and AI visuals.",
     AGENT / "toolu_vrtx_011Q8WJ1vZxzxCwqmion8U3z__vscode-1779227169252" / "content.txt"),
    (7, "Deploy and Maintain Power BI Assets",
     "Practise workspaces, gateways, scheduled refresh, deployment pipelines and Power BI apps.",
     AGENT / "toolu_vrtx_01XN5wXpJCY1tRJxsryFjQQn__vscode-1779227169253" / "content.txt"),
    (8, "Security, Governance, and Performance",
     "Practise licensing, row-level security, sensitivity labels and performance tuning.",
     AGENT / "toolu_vrtx_01HKFG2KzRman9MbTQRf5Dsv__vscode-1779227169254" / "content.txt"),
]

COURSE_TITLE_LIKE = 'PL-300%'
FINAL_EXAM_TITLE = 'Lesson 3: Exam'
DATA_MODULE_PREFIX = '_pl300_data_l'


def parse_agent_output(text: str):
    m_q = re.search(r'^\s*===QUESTIONS===\s*$', text, flags=re.MULTILINE)
    m_e = re.search(r'^\s*===END===\s*$', text, flags=re.MULTILINE)
    m_l = re.search(r'^\s*===LESSON_HTML===\s*$', text, flags=re.MULTILINE)
    if not (m_l and m_q and m_e):
        raise ValueError("missing markers")
    lesson_html = text[m_l.end():m_q.start()].strip()
    lesson_html = re.sub(r'\n?\s*===LESSON_HTML===\s*$', '', lesson_html).strip()
    questions_src = text[m_q.end():m_e.start()].strip()
    questions = ast.literal_eval(questions_src)
    if not isinstance(questions, list) or len(questions) != 8:
        raise ValueError(f"expected 8 questions, got {len(questions) if hasattr(questions,'__len__') else '?'}")
    for i, q in enumerate(questions):
        if not (isinstance(q, tuple) and len(q) == 4):
            raise ValueError(f"q{i}: expected 4-tuple")
        _, _, opts, _ = q
        if len(opts) != 4 or sum(int(o[1]) for o in opts) != 1:
            raise ValueError(f"q{i}: need 4 options with exactly 1 correct")
    return lesson_html, questions_src


CODE_BLOCK_RE = re.compile(
    r'(<pre><code class="language-[a-zA-Z0-9_-]+">)(.*?)(</code></pre>)',
    flags=re.DOTALL,
)


def escape_code_blocks(html: str) -> str:
    def _esc(m):
        inner = m.group(2)
        inner = inner.replace('&', '&amp;').replace('<', '&lt;').replace('>', '&gt;')
        return m.group(1) + inner + m.group(3)
    return CODE_BLOCK_RE.sub(_esc, html)


def write_data_modules():
    for num, _topic, _qdesc, path in SPEC:
        text = path.read_text(encoding='utf-8')
        lesson_html, questions_src = parse_agent_output(text)
        safe_html = lesson_html.replace('"""', '\\"\\"\\"')
        out = WORKSPACE / f"{DATA_MODULE_PREFIX}{num}.py"
        body = (
            '# Auto-generated by _build_pl300.py\n'
            f'LESSON_HTML = """\n{safe_html}\n"""\n\n'
            f'QUESTIONS = {questions_src}\n'
        )
        out.write_text(body, encoding='utf-8')
        modname = out.stem
        if modname in sys.modules:
            importlib.reload(sys.modules[modname])
        else:
            importlib.import_module(modname)
        print(f"wrote {out.name}  (lesson {len(lesson_html)} chars, {len(questions_src)} qsrc chars)")


def upsert():
    with app.app_context():
        course = Course.query.filter(Course.title.like(COURSE_TITLE_LIKE)).first()
        if not course:
            print(f'{COURSE_TITLE_LIKE} course not found.')
            return

        final = Lesson.query.filter_by(course_id=course.id, title=FINAL_EXAM_TITLE).first()
        if final:
            final.order = 999
            db.session.flush()
            print(f'parked final exam lesson {final.id} at order 999')
        else:
            print('NOTE: Final Exam lesson not found by title.')

        next_order = 4
        for num, topic, qdesc, _path in SPEC:
            modname = f'{DATA_MODULE_PREFIX}{num}'
            data = importlib.reload(sys.modules[modname]) if modname in sys.modules else importlib.import_module(modname)
            lesson_html = escape_code_blocks(data.LESSON_HTML)
            questions = data.QUESTIONS

            ltitle = f'Lesson {num}: {topic}'
            qtitle = f'Lesson {num} Quiz \u2014 {topic}'

            lesson = Lesson.query.filter_by(course_id=course.id, title=ltitle).first()
            if lesson:
                lesson.content = lesson_html
                lesson.content_type = 'lesson'
                lesson.order = next_order
                lesson.points = 1.0
                print(f'updated content lesson {lesson.id} ({ltitle}) order={next_order}')
            else:
                lesson = Lesson(
                    title=ltitle, content=lesson_html, course_id=course.id,
                    content_type='lesson', order=next_order, points=1.0,
                )
                db.session.add(lesson)
                db.session.flush()
                print(f'inserted content lesson {lesson.id} ({ltitle}) order={next_order}')
            next_order += 1

            quiz = Quiz.query.filter_by(course_id=course.id, title=qtitle).first()
            if not quiz:
                quiz = Quiz(course_id=course.id, title=qtitle, description=qdesc)
                db.session.add(quiz)
                db.session.flush()
                print(f'  inserted quiz {quiz.id}')
            else:
                quiz.description = qdesc
                for q in list(quiz.questions):
                    db.session.delete(q)
                db.session.flush()
                print(f'  rebuilt quiz {quiz.id}')

            for qtype, qhtml, opts, feedback in questions:
                q = Question(
                    quiz_id=quiz.id, question_type=qtype, question_html=qhtml,
                    points=1.0, feedback=feedback,
                )
                db.session.add(q)
                db.session.flush()
                for i, (ohtml, correct) in enumerate(opts):
                    db.session.add(QuestionOption(
                        question_id=q.id, option_html=ohtml,
                        is_correct=bool(correct), order=i,
                    ))

            exam = Lesson.query.filter_by(
                course_id=course.id, title=qtitle, content_type='exam',
            ).first()
            if exam:
                exam.quiz_id = quiz.id
                exam.order = next_order
                exam.points = 1.0
                print(f'  updated exam lesson {exam.id} order={next_order}')
            else:
                exam = Lesson(
                    title=qtitle, content='', course_id=course.id,
                    content_type='exam', quiz_id=quiz.id,
                    order=next_order, points=1.0,
                )
                db.session.add(exam)
                db.session.flush()
                print(f'  inserted exam lesson {exam.id} order={next_order}')
            next_order += 1

        if final:
            final.order = next_order
            print(f'restored final exam lesson {final.id} to order {next_order}')

        db.session.commit()
        print('done.')


if __name__ == '__main__':
    print('--- Writing data modules ---')
    write_data_modules()
    print('--- Upserting into DB ---')
    upsert()
