"""Build DP-300 (Azure DBA) Lessons 3-8 + quizzes from agent outputs."""
import ast
import importlib
import re
import sys
from pathlib import Path

from app import app, db, Course, Lesson, Quiz, Question, QuestionOption

WORKSPACE = Path(__file__).resolve().parent
AGENT = Path(r"c:\Users\hp\AppData\Roaming\Code\User\workspaceStorage\25f723a0a07d7e81c8ab2371048eef31\GitHub.copilot-chat\chat-session-resources\7cdafd4c-d586-4bc9-9b47-be8b70ffb17b")

SPEC = [
    (3, "Plan and Implement Data Platform Resources",
     "Practise choosing Azure SQL deployment options, service tiers and sizing.",
     AGENT / "toolu_vrtx_016ampcYNjjvYY1WZdazFXdf__vscode-1779227169258" / "content.txt"),
    (4, "Implement a Secure Environment",
     "Practise authentication, RBAC, firewalls, encryption (TDE / Always Encrypted), masking and auditing.",
     AGENT / "toolu_vrtx_01PrvUNh813aCiDcu1cP4hT2__vscode-1779227169259" / "content.txt"),
    (5, "Monitor, Configure, and Optimize Database Resources",
     "Practise Azure Monitor, Query Store, DMVs, index/statistics tuning and intelligent performance features.",
     AGENT / "toolu_vrtx_01N5tmtLEpxsxWHKPjLenXv7__vscode-1779227169260" / "content.txt"),
    (6, "Configure and Manage Automation of Tasks",
     "Practise SQL Agent, Elastic Jobs, Azure Automation, DACPACs and CI/CD for databases.",
     AGENT / "toolu_vrtx_01LJD98hXeccSXZoNKLGLbnU__vscode-1779227169261" / "content.txt"),
    (7, "Plan and Implement High Availability and Disaster Recovery",
     "Practise RPO/RTO, AGs, failover groups, geo-replication, PITR and zone redundancy.",
     AGENT / "toolu_vrtx_01TkyEBTdH1dZWC5fMeFmGhS__vscode-1779227169262" / "content.txt"),
    (8, "Perform Administrative and Data Movement Tasks",
     "Practise routine DBA tasks, BACPAC/DACPAC, DMS migrations and data movement options.",
     AGENT / "toolu_vrtx_0199fa7yQcAy7CcSCkeAH4pm__vscode-1779227169263" / "content.txt"),
]

COURSE_TITLE_LIKE = 'DP-300%'
FINAL_EXAM_TITLE = 'Lesson 3: Exam'
DATA_MODULE_PREFIX = '_dp300_data_l'


def parse_agent_output(text: str):
    m_l = re.search(r'^\s*===LESSON_HTML===\s*$', text, flags=re.MULTILINE)
    m_q = re.search(r'^\s*===QUESTIONS===\s*$', text, flags=re.MULTILINE)
    if not (m_l and m_q):
        raise ValueError("missing markers")
    # Use the FIRST ===END=== that occurs AFTER ===QUESTIONS===, since some
    # agents emit a stray ===END=== between the lesson HTML and the questions.
    m_e = re.search(r'^\s*===END===\s*$', text[m_q.end():], flags=re.MULTILINE)
    if not m_e:
        raise ValueError("missing END marker after QUESTIONS")
    end_abs = m_q.end() + m_e.start()
    lesson_html = text[m_l.end():m_q.start()].strip()
    # Trim any stray closing markers from the lesson body
    lesson_html = re.sub(r'\n?\s*===(?:LESSON_HTML|END)===\s*$', '', lesson_html).strip()
    questions_src = text[m_q.end():end_abs].strip()
    questions = ast.literal_eval(questions_src)
    if not isinstance(questions, list) or len(questions) != 8:
        raise ValueError(f"expected 8 questions, got {len(questions) if hasattr(questions,'__len__') else '?'}")
    for i, q in enumerate(questions):
        if not (isinstance(q, tuple) and len(q) == 4):
            raise ValueError(f"q{i}: expected 4-tuple")
        _, _, opts, _ = q
        if len(opts) != 4 or sum(int(o[1]) for o in opts) != 1:
            raise ValueError(f"q{i}: need 4 options with exactly 1 correct")
    return lesson_html, questions_src


CODE_BLOCK_RE = re.compile(
    r'(<pre><code class="language-[a-zA-Z0-9_-]+">)(.*?)(</code></pre>)',
    flags=re.DOTALL,
)


def escape_code_blocks(html: str) -> str:
    def _esc(m):
        inner = m.group(2)
        inner = inner.replace('&', '&amp;').replace('<', '&lt;').replace('>', '&gt;')
        return m.group(1) + inner + m.group(3)
    return CODE_BLOCK_RE.sub(_esc, html)


def write_data_modules():
    for num, _topic, _qdesc, path in SPEC:
        text = path.read_text(encoding='utf-8')
        lesson_html, questions_src = parse_agent_output(text)
        safe_html = lesson_html.replace('"""', '\\"\\"\\"')
        out = WORKSPACE / f"{DATA_MODULE_PREFIX}{num}.py"
        body = (
            '# Auto-generated by _build_dp300.py\n'
            f'LESSON_HTML = """\n{safe_html}\n"""\n\n'
            f'QUESTIONS = {questions_src}\n'
        )
        out.write_text(body, encoding='utf-8')
        modname = out.stem
        if modname in sys.modules:
            importlib.reload(sys.modules[modname])
        else:
            importlib.import_module(modname)
        print(f"wrote {out.name}  (lesson {len(lesson_html)} chars, {len(questions_src)} qsrc chars)")


def upsert():
    with app.app_context():
        course = Course.query.filter(Course.title.like(COURSE_TITLE_LIKE)).first()
        if not course:
            print(f'{COURSE_TITLE_LIKE} course not found.')
            return
        final = Lesson.query.filter_by(course_id=course.id, title=FINAL_EXAM_TITLE).first()
        if final:
            final.order = 999
            db.session.flush()
            print(f'parked final exam lesson {final.id} at order 999')
        next_order = 4
        for num, topic, qdesc, _path in SPEC:
            modname = f'{DATA_MODULE_PREFIX}{num}'
            data = importlib.reload(sys.modules[modname]) if modname in sys.modules else importlib.import_module(modname)
            lesson_html = escape_code_blocks(data.LESSON_HTML)
            questions = data.QUESTIONS

            ltitle = f'Lesson {num}: {topic}'
            qtitle = f'Lesson {num} Quiz \u2014 {topic}'

            lesson = Lesson.query.filter_by(course_id=course.id, title=ltitle).first()
            if lesson:
                lesson.content = lesson_html
                lesson.content_type = 'lesson'
                lesson.order = next_order
                lesson.points = 1.0
                print(f'updated content lesson {lesson.id} ({ltitle}) order={next_order}')
            else:
                lesson = Lesson(
                    title=ltitle, content=lesson_html, course_id=course.id,
                    content_type='lesson', order=next_order, points=1.0,
                )
                db.session.add(lesson)
                db.session.flush()
                print(f'inserted content lesson {lesson.id} ({ltitle}) order={next_order}')
            next_order += 1

            quiz = Quiz.query.filter_by(course_id=course.id, title=qtitle).first()
            if not quiz:
                quiz = Quiz(course_id=course.id, title=qtitle, description=qdesc)
                db.session.add(quiz)
                db.session.flush()
                print(f'  inserted quiz {quiz.id}')
            else:
                quiz.description = qdesc
                for q in list(quiz.questions):
                    db.session.delete(q)
                db.session.flush()
                print(f'  rebuilt quiz {quiz.id}')

            for qtype, qhtml, opts, feedback in questions:
                q = Question(
                    quiz_id=quiz.id, question_type=qtype, question_html=qhtml,
                    points=1.0, feedback=feedback,
                )
                db.session.add(q)
                db.session.flush()
                for i, (ohtml, correct) in enumerate(opts):
                    db.session.add(QuestionOption(
                        question_id=q.id, option_html=ohtml,
                        is_correct=bool(correct), order=i,
                    ))

            exam = Lesson.query.filter_by(
                course_id=course.id, title=qtitle, content_type='exam',
            ).first()
            if exam:
                exam.quiz_id = quiz.id
                exam.order = next_order
                exam.points = 1.0
                print(f'  updated exam lesson {exam.id} order={next_order}')
            else:
                exam = Lesson(
                    title=qtitle, content='', course_id=course.id,
                    content_type='exam', quiz_id=quiz.id,
                    order=next_order, points=1.0,
                )
                db.session.add(exam)
                db.session.flush()
                print(f'  inserted exam lesson {exam.id} order={next_order}')
            next_order += 1

        if final:
            final.order = next_order
            print(f'restored final exam lesson {final.id} to order {next_order}')
        db.session.commit()
        print('done.')


if __name__ == '__main__':
    print('--- Writing data modules ---')
    write_data_modules()
    print('--- Upserting into DB ---')
    upsert()
