"""Build GH-300 (GitHub Copilot) Lessons 3-8 + quizzes from agent outputs."""
import ast
import importlib
import re
import sys
from pathlib import Path

from app import app, db, Course, Lesson, Quiz, Question, QuestionOption

WORKSPACE = Path(__file__).resolve().parent
AGENT = Path(r"c:\Users\hp\AppData\Roaming\Code\User\workspaceStorage\25f723a0a07d7e81c8ab2371048eef31\GitHub.copilot-chat\chat-session-resources\7cdafd4c-d586-4bc9-9b47-be8b70ffb17b")

SPEC = [
    (3, "Use GitHub Copilot Responsibly",
     "Practise responsible AI principles, validation of Copilot output, IP/licensing, audit logs and when not to use Copilot.",
     AGENT / "toolu_vrtx_01UPZqHgV1vvViAKQ6qJYzuy__vscode-1779227169325" / "content.txt"),
    (4, "Use GitHub Copilot Features",
     "Practise Copilot in IDEs, Copilot Chat, CLI, Agent Mode, MCP, Sub-Agents, Spaces, Spark, Code Review, org policies and the REST API.",
     AGENT / "toolu_vrtx_011atKG2MqoAqRtidhpi6AFi__vscode-1779227169326" / "content.txt"),
    (5, "Understand GitHub Copilot Data and Architecture",
     "Practise Copilot's request lifecycle, data handling, plan-level retention, models and network architecture.",
     AGENT / "toolu_vrtx_01CQJ3YrrFYsBmvvLAZnfgmS__vscode-1779227169327" / "content.txt"),
    (6, "Apply Prompt Engineering and Context Crafting",
     "Practise effective prompt design, context engineering, instruction/prompt/agent files and iterative refinement.",
     AGENT / "toolu_vrtx_01LNbcPetBZL198wgiks2utH__vscode-1779227169328" / "content.txt"),
    (7, "Improve Developer Productivity with GitHub Copilot",
     "Practise productivity and quality workflows, test/security use cases, Copilot Metrics API and team patterns.",
     AGENT / "toolu_vrtx_015imoU364Z9tHEjSXE2i8Hk__vscode-1779227169329" / "content.txt"),
    (8, "Configure Privacy, Content Exclusions, and Safeguards",
     "Practise privacy settings, content exclusions, safeguards, audit logs, troubleshooting and compliance.",
     AGENT / "toolu_vrtx_01HGhzaC3ZjkHnvKswQhkMz2__vscode-1779227169330" / "content.txt"),
]

COURSE_TITLE_LIKE = 'GH-300%'
DATA_MODULE_PREFIX = '_gh300_data_l'


def parse_agent_output(text: str):
    m_l = re.search(r'^\s*===LESSON_HTML===\s*$', text, flags=re.MULTILINE)
    m_q = re.search(r'^\s*===QUESTIONS===\s*$', text, flags=re.MULTILINE)
    if not (m_l and m_q):
        raise ValueError("missing markers")
    m_e = re.search(r'^\s*===END===\s*$', text[m_q.end():], flags=re.MULTILINE)
    if not m_e:
        raise ValueError("missing END marker after QUESTIONS")
    end_abs = m_q.end() + m_e.start()
    lesson_html = text[m_l.end():m_q.start()].strip()
    lesson_html = re.sub(r'\n?\s*===(?:LESSON_HTML|END)===\s*$', '', lesson_html).strip()
    questions_src = text[m_q.end():end_abs].strip()
    questions = ast.literal_eval(questions_src)
    if not isinstance(questions, list) or len(questions) != 8:
        raise ValueError(f"expected 8 questions, got {len(questions) if hasattr(questions,'__len__') else '?'}")
    for i, q in enumerate(questions):
        if not (isinstance(q, tuple) and len(q) == 4):
            raise ValueError(f"q{i}: expected 4-tuple")
        _, _, opts, _ = q
        if len(opts) != 4 or sum(int(o[1]) for o in opts) != 1:
            raise ValueError(f"q{i}: need 4 options with exactly 1 correct")
    return lesson_html, questions_src


CODE_BLOCK_RE = re.compile(
    r'(<pre><code class="language-[a-zA-Z0-9_-]+">)(.*?)(</code></pre>)',
    flags=re.DOTALL,
)


def escape_code_blocks(html: str) -> str:
    def _esc(m):
        inner = m.group(2)
        inner = inner.replace('&', '&amp;').replace('<', '&lt;').replace('>', '&gt;')
        return m.group(1) + inner + m.group(3)
    return CODE_BLOCK_RE.sub(_esc, html)


def write_data_modules():
    for num, _topic, _qdesc, path in SPEC:
        if not path.exists():
            print(f"!! MISSING agent output for L{num}: {path}")
            continue
        text = path.read_text(encoding='utf-8')
        lesson_html, questions_src = parse_agent_output(text)
        safe_html = lesson_html.replace('"""', '\\"\\"\\"')
        out = WORKSPACE / f"{DATA_MODULE_PREFIX}{num}.py"
        body = (
            '# Auto-generated by _build_gh300.py\n'
            f'LESSON_HTML = """\n{safe_html}\n"""\n\n'
            f'QUESTIONS = {questions_src}\n'
        )
        out.write_text(body, encoding='utf-8')
        modname = out.stem
        if modname in sys.modules:
            importlib.reload(sys.modules[modname])
        else:
            importlib.import_module(modname)
        print(f"wrote {out.name}  (lesson {len(lesson_html)} chars, {len(questions_src)} qsrc chars)")


def upsert():
    with app.app_context():
        course = Course.query.filter(Course.title.like(COURSE_TITLE_LIKE)).first()
        if not course:
            print(f'{COURSE_TITLE_LIKE} course not found.')
            return
        next_order = 4
        for num, topic, qdesc, _path in SPEC:
            modname = f'{DATA_MODULE_PREFIX}{num}'
            data = importlib.reload(sys.modules[modname]) if modname in sys.modules else importlib.import_module(modname)
            lesson_html = escape_code_blocks(data.LESSON_HTML)
            questions = data.QUESTIONS

            ltitle = f'Lesson {num}: {topic}'
            qtitle = f'Lesson {num} Quiz \u2014 {topic}'

            lesson = Lesson.query.filter_by(course_id=course.id, title=ltitle).first()
            if lesson:
                lesson.content = lesson_html
                lesson.content_type = 'lesson'
                lesson.order = next_order
                lesson.points = 1.0
                print(f'updated content lesson {lesson.id} ({ltitle}) order={next_order}')
            else:
                lesson = Lesson(
                    title=ltitle, content=lesson_html, course_id=course.id,
                    content_type='lesson', order=next_order, points=1.0,
                )
                db.session.add(lesson)
                db.session.flush()
                print(f'inserted content lesson {lesson.id} ({ltitle}) order={next_order}')
            next_order += 1

            quiz = Quiz.query.filter_by(course_id=course.id, title=qtitle).first()
            if not quiz:
                quiz = Quiz(course_id=course.id, title=qtitle, description=qdesc)
                db.session.add(quiz)
                db.session.flush()
                print(f'  inserted quiz {quiz.id}')
            else:
                quiz.description = qdesc
                for q in list(quiz.questions):
                    db.session.delete(q)
                db.session.flush()
                print(f'  rebuilt quiz {quiz.id}')

            for qtype, qhtml, opts, feedback in questions:
                q = Question(
                    quiz_id=quiz.id, question_type=qtype, question_html=qhtml,
                    points=1.0, feedback=feedback,
                )
                db.session.add(q)
                db.session.flush()
                for i, (ohtml, correct) in enumerate(opts):
                    db.session.add(QuestionOption(
                        question_id=q.id, option_html=ohtml,
                        is_correct=bool(correct), order=i,
                    ))

            exam = Lesson.query.filter_by(
                course_id=course.id, title=qtitle, content_type='exam',
            ).first()
            if exam:
                exam.quiz_id = quiz.id
                exam.order = next_order
                exam.points = 1.0
                print(f'  updated exam lesson {exam.id} order={next_order}')
            else:
                exam = Lesson(
                    title=qtitle, content='', course_id=course.id,
                    content_type='exam', quiz_id=quiz.id,
                    order=next_order, points=1.0,
                )
                db.session.add(exam)
                db.session.flush()
                print(f'  inserted exam lesson {exam.id} order={next_order}')
            next_order += 1

        db.session.commit()
        print('done.')


if __name__ == '__main__':
    print('--- Writing data modules ---')
    write_data_modules()
    print('--- Upserting into DB ---')
    upsert()
