# Auto-generated by _build_dp300.py
LESSON_HTML = """
<h2>Implement a Secure Environment in Azure SQL Database</h2>

<h3>Authentication in Azure SQL Database</h3>
<p>Authentication verifies the identity of users connecting to Azure SQL Database. Microsoft Azure offers multiple authentication methods to support various security requirements.</p>

<p><strong>SQL Authentication</strong> uses a username and password stored in the database. While simple to implement, SQL authentication requires careful password management and does not integrate with Azure AD infrastructure. <strong>Microsoft Entra (Azure AD) Authentication</strong> leverages your organization's identity provider, providing single sign-on (SSO), multi-factor authentication (MFA), and centralized access control. This is the recommended approach for enterprise environments.</p>

<p><strong>Managed Identities</strong> eliminate the need to store credentials in application code. System-assigned identities are created automatically for resources, while user-assigned identities can be shared across multiple resources. Applications authenticate using the managed identity without storing secrets.</p>

<p><strong>Contained Users</strong> are database-level accounts that authenticate directly to the database without a corresponding login at the server level. They simplify portability and disaster recovery but should be used carefully in production environments.</p>

<h3>Authorization: Roles and Permissions</h3>
<p>Authorization determines what authenticated users can do. Azure SQL Database implements role-based access control (RBAC) at both the server and database levels.</p>

<p><strong>Server-Level Principals:</strong> Logins created at the server level control who can connect. <strong>Fixed Server Roles</strong> like sysadmin, securityadmin, and serveradmin grant permissions across all databases. Sysadmin has unrestricted control and should be assigned sparingly.</p>

<p><strong>Database-Level Principals:</strong> Users are database-level accounts mapped to server logins. Fixed database roles include db_owner (full database control), db_securityadmin (managing permissions), db_datareader (read access), and db_datawriter (insert/update/delete). For least-privilege access, create custom database roles granting only necessary permissions.</p>

<p>Use <strong>GRANT</strong> to assign permissions, <strong>DENY</strong> to explicitly revoke access, and <strong>REVOKE</strong> to remove previously granted permissions. Example:</p>

<pre><code class="language-sql">GRANT SELECT, INSERT ON Sales.Orders TO [AppUser];
DENY DELETE ON Sales.Orders TO [AppUser];
CREATE ROLE OrderProcessor;
GRANT SELECT, INSERT ON Sales.Orders TO OrderProcessor;</code></pre>

<h3>Network Security</h3>
<p><strong>Firewall Rules</strong> control network access. Server-level firewall rules apply to all databases and are managed by administrators. Database-level rules apply only to specific databases and can be delegated. Both allow or deny IP ranges.</p>

<p><strong>Virtual Network Service Endpoints</strong> restrict access to a specific VNet, ensuring traffic stays within Azure. <strong>Private Link / Private Endpoint</strong> provides a private IP address within your VNet, eliminating exposure to the public internet entirely. This is the most secure option for applications running in Azure.</p>

<p>Best practice: disable public endpoint access when possible, enforce VNet or Private Endpoint connections, and use firewall rules to restrict remaining public traffic.</p>

<h3>Data Protection and Encryption</h3>
<p><strong>Transparent Data Encryption (TDE)</strong> encrypts the database at rest. Service-managed keys are handled by Azure, while customer-managed keys (BYOK) stored in Azure Key Vault give you full control and meet compliance requirements.</p>

<p><strong>Always Encrypted</strong> encrypts data in the application before sending it to the database. <strong>Deterministic encryption</strong> produces the same ciphertext for the same plaintext, enabling comparisons but reducing security. <strong>Randomized encryption</strong> produces different ciphertext each time, offering stronger security but preventing queries on encrypted columns.</p>

<table>
<tr>
<th>Feature</th>
<th>TDE</th>
<th>Always Encrypted</th>
</tr>
<tr>
<td>Encryption Scope</td>
<td>Entire database</td>
<td>Individual columns</td>
</tr>
<tr>
<td>Where Encryption Occurs</td>
<td>Database engine</td>
<td>Application/driver</td>
</tr>
<tr>
<td>Key Management</td>
<td>Service or BYOK</td>
<td>Always BYOK (client-side)</td>
</tr>
<tr>
<td>Query Encrypted Data</td>
<td>Yes (decrypted)</td>
<td>Limited (depends on encryption type)</td>
</tr>
</table>

<p><strong>Dynamic Data Masking (DDM)</strong> hides sensitive data in query results without modifying stored data. It is NOT encryption; it is for audit and reporting scenarios only. Always combine DDM with other protections like encryption and RLS for sensitive data.</p>

<p><strong>Row-Level Security (RLS)</strong> filters rows returned in queries based on user identity. Apply predicate functions to tables, enabling applications to return different results per user without application logic changes.</p>

<p><strong>SQL Auditing</strong> logs database operations to Azure Storage, Log Analytics, or Event Hubs. Use auditing to track privileged operations, detect threats, and meet compliance requirements.</p>

<h3>Microsoft Defender for SQL</h3>
<p>Microsoft Defender for SQL (formerly Advanced Data Security) provides threat protection and vulnerability management. <strong>Vulnerability Assessment</strong> scans databases for security misconfigurations and recommends remediation. <strong>Threat Protection</strong> detects anomalous database activity, SQL injection attempts, and unauthorized access patterns, sending alerts for investigation.</p>
"""

QUESTIONS = [
  ("multiple_choice", "Your organization uses Azure SQL Database for a business-critical application. Which approach is <em>most</em> recommended for production authentication?", [("SQL authentication with a strong password policy", False), ("Microsoft Entra (Azure AD) authentication with MFA", True), ("Contained users for all database access", False), ("Mixed SQL and Entra authentication", False)], "Entra authentication integrates with organizational identity management and supports MFA, providing better security and centralized access control compared to SQL authentication."),
  ("multiple_choice", "A database contains a table with encrypted columns using Always Encrypted. You need to query for all records where SSN &lt;= '999-99-9999'. Which encryption type must you use?", [("Randomized encryption", False), ("Service-managed TDE", False), ("Deterministic encryption", True), ("Dynamic Data Masking", False)], "Deterministic encryption produces the same ciphertext for identical plaintext, enabling equality and range comparisons. Randomized encryption would prevent this type of query."),
  ("multiple_choice", "You want to restrict network access to an Azure SQL Database so traffic never traverses the public internet. Which solution is <em>most</em> appropriate?", [("Server-level firewall rule allowing your IP range", False), ("Virtual Network Service Endpoint", False), ("Private Endpoint with a private IP in your VNet", True), ("Database-level firewall rule", False)], "Private Endpoint creates a private IP address within your VNet and removes public endpoint exposure entirely, providing the strongest network isolation."),
  ("multiple_choice", "What is the primary limitation of Dynamic Data Masking (DDM)?", [("It only works with Entra authentication", False), ("It does not encrypt data; it is a display-only mechanism and not suitable as sole protection for sensitive data", True), ("It cannot be applied to numeric columns", False), ("It requires BYOK with Azure Key Vault", False)], "DDM masks values in query results but stores unencrypted data. It must be combined with encryption, RLS, and auditing for proper sensitive data protection."),
  ("multiple_choice", "Review this T-SQL code:\n&lt;code&gt;ALTER ROLE db_datareader ADD MEMBER [ContractorAccount];\nGRANT DELETE ON Sales.Orders TO [ContractorAccount];&lt;/code&gt;\nWhat is the security concern?", [("The user now has excessive permissions; contractors should not have DELETE on Orders", True), ("Entra authentication is required for this operation", False), ("Database roles cannot include external users", False), ("The GRANT statement should use DENY instead", False)], "Adding the contractor to db_datareader grants SELECT permission, then explicitly GRANTing DELETE violates least-privilege. Create a minimal custom role instead."),
  ("multiple_choice", "You must protect sensitive customer data at rest and during transmission. Transparent Data Encryption (TDE) with service-managed keys is deployed. What additional encryption should you implement for columns containing payment card numbers?", [("Additional TDE with customer-managed keys", False), ("Always Encrypted with randomized encryption", True), ("SQL Auditing to Log Analytics", False), ("Dynamic Data Masking with strong rules", False)], "Always Encrypted encrypts payment data before it leaves the application, providing end-to-end protection independent of TDE. Randomized encryption is appropriate for data that does not need column-level queries."),
  ("multiple_choice", "Which feature of Microsoft Defender for SQL directly identifies security misconfigurations and missing security controls in your database?", [("Threat Protection alerts", False), ("Vulnerability Assessment", True), ("Row-Level Security (RLS)", False), ("SQL Auditing", False)], "Vulnerability Assessment scans the database configuration for security gaps and best-practice violations. Threat Protection detects active attacks."),
  ("multiple_choice", "A distributed team works on a shared database. You need Row-Level Security (RLS) to return sales data only for each employee's region. What does RLS require?", [("Separate database per region", False), ("A security predicate function that filters rows based on user identity, plus table bindings configured per region", True), ("Always Encrypted on the Region column", False), ("Disabling public endpoint access", False)], "RLS uses security predicates (functions) that filter query results dynamically based on the current user. Combined with table bindings, RLS returns different data per user without application code changes.")
]
