# Auto-generated by _build_dp300.py
LESSON_HTML = """
<h2>Lesson 3: Plan and Implement Data Platform Resources</h2>

<h3>Azure Deployment Options for SQL Workloads</h3>
<p>Microsoft Azure provides multiple deployment options for SQL Server and open-source database workloads, each offering different levels of management responsibility, control, and compatibility. Choosing the right option depends on your application requirements, compliance needs, and operational capabilities.</p>

<h3>Infrastructure-as-a-Service (IaaS): SQL Server on Azure Virtual Machines</h3>
<p><strong>SQL Server on Azure VMs</strong> provides the highest degree of control and compatibility with on-premises SQL Server deployments. You provision Windows or Linux virtual machines with pre-installed SQL Server, giving you full access to the operating system, file system, and database engine. This option is ideal when you need:</p>
<ul>
<li>SQL Agent for scheduled jobs and automated tasks</li>
<li>Cross-database queries and complex linked server configurations</li>
<li>Custom extensions or third-party tools</li>
<li>Specific SQL Server editions or versions not available in managed services</li>
</ul>
<p>However, you are responsible for OS patching, security updates, SQL Server maintenance, backup strategy, and high availability configuration.</p>

<h3>Platform-as-a-Service (PaaS): Azure SQL Database</h3>
<p><strong>Azure SQL Database</strong> is a fully managed relational database service. Microsoft handles all patching, backups, and infrastructure management. Azure SQL Database is available in three deployment models:</p>
<ul>
<li><strong>Single Database</strong>: A standalone database with dedicated resources, ideal for single-tenant applications.</li>
<li><strong>Elastic Pool</strong>: A collection of databases sharing a pooled set of resources, cost-effective for multi-tenant scenarios where workloads are unpredictable.</li>
<li><strong>Managed Instance</strong>: A near-100% compatible SQL Server environment with native VNet support, useful for migration of complex workloads requiring SQL Agent, cross-database queries, and T-SQL features.</li>
</ul>

<h3>Service Tiers and Pricing Models</h3>
<p>Azure SQL Database supports two purchasing models:</p>
<p><strong>DTU (Database Transaction Unit) Model:</strong> A bundled measure of CPU, memory, and I/O. Compute and storage are tightly coupled. Suitable for predictable, moderate workloads. Examples: Standard, Premium tiers.</p>
<p><strong>vCore (Virtual Core) Model:</strong> Decouples compute and storage, offering more flexibility. Choose hardware generation, number of cores, and storage independently. Recommended for new deployments and complex workloads.</p>

<h3>Service Tiers (vCore Model)</h3>
<ul>
<li><strong>General Purpose</strong>: Balanced compute, memory, and storage. Good for most business workloads. Supports both provisioned and serverless compute.</li>
<li><strong>Business Critical</strong>: High-performance tier with premium SLA (99.95%), in-memory OLTP, and fast failover. For mission-critical applications.</li>
<li><strong>Hyperscale</strong>: Scales up to 100 TB with high performance. Designed for large, dynamic workloads requiring rapid scaling.</li>
<li><strong>Serverless Compute</strong>: Auto-pauses when inactive, resuming on demand. Billed only for actual compute used. Ideal for development/testing and bursty workloads.</li>
</ul>

<h3>Azure Databases for Open Source</h3>
<ul>
<li><strong>Azure Database for PostgreSQL</strong>: Available in Single Server and Flexible Server (recommended). Fully managed, with automated backups, point-in-time restore, and HA options.</li>
<li><strong>Azure Database for MySQL</strong>: Available in Flexible Server deployment model. High availability and automated failover capabilities.</li>
</ul>

<h3>Comparison: IaaS vs. PaaS Deployment Models</h3>
<table border="1" cellpadding="8" cellspacing="0" style="border-collapse: collapse;">
<tr>
<th>Aspect</th>
<th>SQL Server on VM (IaaS)</th>
<th>Azure SQL Database (PaaS)</th>
<th>SQL Managed Instance</th>
</tr>
<tr>
<td>Control Level</td>
<td>Full</td>
<td>Limited</td>
<td>Medium</td>
</tr>
<tr>
<td>SQL Server Compatibility</td>
<td>100%</td>
<td>95% (some features unsupported)</td>
<td>99% (near-complete compatibility)</td>
</tr>
<tr>
<td>OS Access</td>
<td>Yes</td>
<td>No</td>
<td>No</td>
</tr>
<tr>
<td>Patching Responsibility</td>
<td>You (manual or auto-scheduled)</td>
<td>Microsoft (automatic)</td>
<td>Microsoft (automatic)</td>
</tr>
<tr>
<td>Scaling</td>
<td>Manual (resize VM)</td>
<td>Automatic (elastic pools) or manual (single DB)</td>
<td>Manual (change tier)</td>
</tr>
<tr>
<td>Cost Model</td>
<td>Compute and storage by hour</td>
<td>DTU or vCore purchase plans</td>
<td>vCore purchase plans</td>
</tr>
</table>

<h3>Migration Planning and Assessment</h3>
<p>Before migrating to Azure, assess your on-premises SQL Server workload using these tools:</p>
<ul>
<li><strong>Data Migration Assistant (DMA)</strong>: Evaluates SQL Server compatibility, identifies breaking changes, and recommends Azure SQL Database features.</li>
<li><strong>Azure SQL Migration Extension</strong>: Provides end-to-end migration experience with discovery, assessment, and schema/data migration capabilities.</li>
<li><strong>Azure Migrate</strong>: Broader assessment tool for entire environments including compute, storage, and databases.</li>
</ul>

<h3>Networking and Security Considerations</h3>
<p>Configure connectivity options to meet security and access requirements:</p>
<ul>
<li><strong>Public Endpoint</strong>: Accessible from the internet with IP-based firewall rules. Convenient but requires strong authentication and TLS encryption.</li>
<li><strong>Private Endpoint</strong>: VNet-integrated, accessible only within your virtual network, providing network isolation and enhanced security without public internet exposure.</li>
</ul>

<h3>Region Selection and Disaster Recovery</h3>
<p>Choose a primary region based on data residency regulations, application latency, and compliance requirements. Pair your primary region with a secondary region for disaster recovery and business continuity planning. Azure provides paired regions within the same geographic boundary to meet data residency mandates while enabling rapid failover.</p>
"""

QUESTIONS = [
    (
        "multiple_choice",
        "Your organization has a SQL Server workload that requires SQL Agent for scheduled jobs and performs frequent cross-database queries. Which Azure deployment option best supports these requirements?",
        [
            ("Azure SQL Database (single database)", 0),
            ("Azure SQL Database Managed Instance", 1),
            ("SQL Server on Azure Virtual Machines", 0),
            ("Azure Database for PostgreSQL", 0),
        ],
        "SQL Managed Instance provides near-complete SQL Server compatibility including SQL Agent and cross-database query support, while remaining a managed service."
    ),
    (
        "multiple_choice",
        "You need to deploy Azure SQL Database for a new application with unpredictable resource requirements. Which purchasing model provides better flexibility to scale compute and storage independently?",
        [
            ("DTU model", 0),
            ("vCore model", 1),
            ("DTU and vCore are equivalent", 0),
            ("Serverless model only", 0),
        ],
        "The vCore model decouples compute and storage, allowing independent scaling, while DTU bundles them together."
    ),
    (
        "multiple_choice",
        "Your company requires a SQL database that can scale up to 100 TB and handle dynamic workload increases with minimal latency. Which service tier should you choose?",
        [
            ("General Purpose", 0),
            ("Business Critical", 0),
            ("Hyperscale", 1),
            ("Serverless", 0),
        ],
        "Hyperscale tier is specifically designed for large databases requiring rapid elastic scaling up to 100 TB."
    ),
    (
        "multiple_choice",
        "You are setting up a development environment using Azure SQL Database serverless compute tier. What happens when the database is idle for the configured auto-pause delay?",
        [
            ("The database remains running but billing is reduced by 50 percent", 0),
            ("The database is automatically paused and you incur no compute charges until activity resumes", 1),
            ("The database is deleted after 24 hours", 0),
            ("Manual intervention is required to pause the database", 0),
        ],
        "Serverless compute automatically pauses inactive databases, billing only for storage during idle periods, and resumes when queries arrive."
    ),
    (
        "multiple_choice",
        "Your SaaS application serves 500 customers with varying database workload patterns. How does an Azure SQL Database elastic pool provide cost savings?",
        [
            ("Databases share a pooled set of resources, absorbing unpredictable peak loads from different customers without over-provisioning", 1),
            ("It reduces backup costs by 75 percent", 0),
            ("It eliminates the need for redundancy and failover", 0),
            ("It automatically migrates inactive databases to cold storage", 0),
        ],
        "Elastic pools allow multiple databases to share resources efficiently, saving costs when customer workloads peak at different times."
    ),
    (
        "multiple_choice",
        "Before migrating a complex on-premises SQL Server workload to Azure, you need to identify breaking changes and unsupported features. Which tool should you use?",
        [
            ("Azure SQL Migration Extension only", 0),
            ("Azure Resource Manager templates", 0),
            ("Data Migration Assistant (DMA)", 1),
            ("SQL Server Management Studio (SSMS)", 0),
        ],
        "Data Migration Assistant specifically evaluates SQL Server compatibility, identifies breaking changes, and recommends Azure SQL options."
    ),
    (
        "multiple_choice",
        "You are planning database deployment for an application requiring high availability and disaster recovery across geographic regions. What primary consideration should guide your region selection?",
        [
            ("Choose a primary region based on data residency, latency, and compliance, with a secondary region paired for disaster recovery", 1),
            ("Always select the cheapest region regardless of location", 0),
            ("All Azure regions are interchangeable for database deployment", 0),
            ("Select only regions that support Hyperscale tier", 0),
        ],
        "Region selection must balance data sovereignty, application latency requirements, and compliance needs, with disaster recovery region pairing."
    ),
    (
        "multiple_choice",
        "Your mission-critical application requires a 99.95% SLA, premium performance with in-memory OLTP, and prioritized infrastructure resources. Which Azure SQL Database service tier meets these requirements?",
        [
            ("Business Critical", 1),
            ("General Purpose", 0),
            ("Hyperscale", 0),
            ("Basic DTU tier", 0),
        ],
        "Business Critical tier provides the 99.95% SLA, premium performance, and dedicated resources needed for mission-critical workloads."
    ),
]
