# Auto-generated by _build_dp300.py
LESSON_HTML = """
<h2>Lesson 5: Monitor, Configure, and Optimize Database Resources</h2>

<h3>Overview</h3>
<p>Effective database administration requires comprehensive monitoring, configuration, and optimization strategies. Azure Database Administrators must leverage both cloud-native monitoring tools and SQL Server-specific utilities to maintain performance, identify bottlenecks, and proactively resolve issues before they impact applications.</p>

<h3>Azure Monitoring Tools</h3>
<p><strong>Azure Monitor</strong> provides centralized monitoring for Azure SQL Database and SQL Server on Azure VMs. It collects metrics (CPU percentage, DTU usage, connection count) and logs (diagnostic logs, Query Store data) from your database resources.</p>
<p><strong>Log Analytics Workspace</strong> is the central repository for log data. You configure <strong>diagnostic settings</strong> at the database level to route logs to Log Analytics, enabling advanced querying with Kusto Query Language (KQL).</p>
<p><strong>Activity Log</strong> tracks resource-level management operations (user who created/deleted a database, when backups occurred), while <strong>Resource Logs</strong> capture database performance events, SQL errors, and Query Store runtime statistics.</p>
<p><strong>Alerts and Action Groups</strong> allow automatic responses when metrics exceed thresholds. For example, alert when CPU &gt; 80% for 5 minutes, triggering an action group that sends email or invokes a runbook.</p>
<p>The <strong>Azure SQL Analytics</strong> solution provides pre-built dashboards and KQL queries for common performance scenarios, including top SQL statements by duration and blocking relationships.</p>

<h3>SQL Server Monitoring Tools</h3>
<p><strong>Dynamic Management Views (DMVs)</strong> offer real-time visibility into SQL Server internals:</p>
<ul>
<li><strong>sys.dm_exec_requests</strong> — shows active queries, their status (running, suspended), CPU/IO time, and wait type</li>
<li><strong>sys.dm_os_wait_stats</strong> — aggregates wait types (PAGEIOLATCH, WRITELOG, CXPACKET), indicating IO contention, log throughput limits, or parallelism bottlenecks</li>
<li><strong>sys.dm_db_index_usage_stats</strong> — tracks index usage (seeks, scans, updates), helping identify unused or underutilized indexes</li>
</ul>

<p><strong>Query Store</strong> is the preferred tool for query performance troubleshooting. It operates in three modes: <em>Off</em> (disabled), <em>Read-Only</em> (collects data but doesn't enforce plans), and <em>Read/Write</em> (full functionality). Key capabilities include identifying regressed queries (performance degradation over time), forcing a known-good execution plan with <strong>FORCE_LAST_GOOD_PLAN</strong>, and viewing execution plans and metrics without running queries.</p>

<p><strong>Intelligent Insights and Performance Recommendations</strong> use machine learning to detect anomalies. Combined with Azure Advisor, they suggest specific actions such as enabling auto-tuning or investigating missing indexes.</p>

<p><strong>Extended Events</strong> should replace SQL Profiler for production monitoring. Extended Events are lightweight, server-side tracing tools that capture specific events (SQL batch completion, deadlocks, wait types) with minimal overhead, storing results in files or memory targets.</p>

<h3>Performance Tuning Strategies</h3>

<p><strong>Identifying Expensive Queries</strong> — Use Query Store or sys.dm_exec_query_stats to find queries with high CPU, duration, or logical reads. Focus optimization efforts on queries with the largest impact.</p>

<p><strong>Index Strategies</strong>:</p>
<ul>
<li><strong>Clustered Index</strong> — physically orders table rows; one per table. Primary key is usually clustered.</li>
<li><strong>Nonclustered Index</strong> — separate structure pointing to data. Add <em>included columns</em> to cover frequent queries without table lookups.</li>
<li><strong>Filtered Indexes</strong> — index subset of rows (e.g., WHERE Status = 'Active'), reducing size and maintenance cost.</li>
<li><strong>Columnstore Indexes</strong> — compress column data; ideal for analytical queries scanning large datasets.</li>
</ul>

<p><strong>Statistics Management</strong> — Ensure <em>AUTO_CREATE_STATISTICS</em> and <em>AUTO_UPDATE_STATISTICS</em> are enabled. For high-volume workloads, enable <em>AUTO_UPDATE_STATISTICS_ASYNC</em> to prevent query delays during statistics updates.</p>

<p><strong>Index Fragmentation Maintenance</strong>:</p>
<table border="1" cellpadding="8">
<tr><th>Fragmentation Level</th><th>Action</th></tr>
<tr><td>&lt; 5%</td><td>No action needed</td></tr>
<tr><td>5% to 30%</td><td>REORGANIZE (online, minimal logging)</td></tr>
<tr><td>&gt; 30%</td><td>REBUILD (offline by default, or ONLINE with Enterprise Edition)</td></tr>
</table>

<pre><code class="language-sql">-- Check index fragmentation
SELECT OBJECT_NAME(ips.object_id) AS TableName,
       i.name AS IndexName,
       ips.avg_fragmentation_in_percent
FROM sys.dm_db_index_physical_stats(DB_ID(), NULL, NULL, NULL, 'LIMITED') ips
INNER JOIN sys.indexes i ON ips.object_id = i.object_id
  AND ips.index_id = i.index_id
WHERE ips.avg_fragmentation_in_percent > 5
  AND ips.page_count > 1000;

-- Reorganize index
ALTER INDEX IX_TableName_Column ON TableName REORGANIZE;</code></pre>

<p><strong>Resource Configuration</strong> — Set <em>max degree of parallelism (MAXDOP)</em> to control query parallelism; MAXDOP 1 disables parallelism, MAXDOP 4 limits to 4 cores. Adjust <em>cost threshold for parallelism</em> to prevent small queries from using expensive parallel plans. In Azure SQL Database, these are managed via automatic tuning.</p>

<p><strong>TempDB Configuration</strong> — Create multiple tempdb data files (one per core up to 8) to reduce contention. Place tempdb on fast storage separate from user databases when possible.</p>

<p><strong>Automatic Tuning</strong> — Enable automatic tuning to automatically enforce <em>FORCE_LAST_GOOD_PLAN</em>, <em>CREATE_INDEX</em>, or <em>DROP_INDEX</em> recommendations without manual intervention.</p>
"""

QUESTIONS = [
    ("multiple_choice", "What is the primary use case for Query Store in Azure SQL Database?", [("To store user data in a distributed cache", False), ("To capture, store, and analyze query execution plans and performance metrics over time", True), ("To manage security policies and access controls", False), ("To replicate data across geographic regions", False)], "Query Store is specifically designed for query performance troubleshooting and regression detection."),
    ("multiple_choice", "When should you use REBUILD instead of REORGANIZE for an index?", [("When fragmentation is between 5% and 15%", False), ("When fragmentation is greater than 30%", True), ("Only on weekend maintenance windows", False), ("When the index has fewer than 100 pages", False)], "REBUILD is required for fragmentation above 30%; REORGANIZE is sufficient for 5-30%."),
    ("multiple_choice", "Which index type should you use for analytical queries scanning millions of rows across multiple columns?", [("Clustered index", False), ("Hash index", False), ("Columnstore index", True), ("Spatial index", False)], "Columnstore indexes compress column data and significantly improve performance for analytical workloads."),
    ("multiple_choice", "Which DMV shows active queries currently executing on the SQL Server instance?", [("sys.dm_os_wait_stats", False), ("sys.dm_exec_requests", True), ("sys.dm_db_index_usage_stats", False), ("sys.dm_exec_query_stats", False)], "sys.dm_exec_requests displays real-time data on actively executing queries, including wait types and CPU time."),
    ("multiple_choice", "What does setting MAXDOP to 1 accomplish?", [("Enables parallel execution on one core only", False), ("Disables parallel query execution entirely", True), ("Doubles query throughput", False), ("Increases tempdb usage", False)], "MAXDOP 1 forces serial query execution, useful for preventing resource contention in specific scenarios."),
    ("multiple_choice", "When using automatic tuning in Azure SQL Database, what does the FORCE_LAST_GOOD_PLAN action do?", [("Creates a new index to improve query speed", False), ("Reverts to a previously known-good execution plan when a regression is detected", True), ("Immediately deletes underused indexes", False), ("Migrates data to a different storage tier", False)], "FORCE_LAST_GOOD_PLAN is an automatic tuning action that enforces a known-good plan to recover from performance regressions."),
    ("multiple_choice", "Why should Extended Events be preferred over SQL Profiler for production monitoring?", [("Extended Events supports more event types than Profiler", False), ("Extended Events is a lightweight server-side tool with minimal overhead", True), ("Profiler is only available in older SQL Server versions", False), ("Extended Events automatically optimizes index fragmentation", False)], "Extended Events are optimized for production use, offering server-side tracing with negligible performance impact."),
    ("multiple_choice", "What does a high count of PAGEIOLATCH wait type typically indicate?", [("CPU bottleneck or missing indexes causing scans", False), ("Disk I/O contention or storage performance issues", True), ("Memory pressure and excessive paging", False), ("Network latency between client and server", False)], "PAGEIOLATCH waits indicate the query is blocked waiting for a page read from disk, suggesting I/O performance problems.")
]
