# Auto-generated by _build_gh300.py
LESSON_HTML = """
<h2>Lesson 5: Understand GitHub Copilot Data and Architecture</h2>

<h3>System Architecture Overview</h3>
<p>GitHub Copilot operates as a distributed system connecting your IDE to Microsoft-hosted models through a multi-layered architecture. The client-side extension runs within your IDE (VS Code, JetBrains, Visual Studio, or Neovim), communicating with the Copilot service backend via HTTPS. This service layer acts as an intermediary, aggregating requests, enforcing policies, and routing to appropriate model backends hosted on Azure infrastructure. The architecture separates concerns: your IDE never directly contacts model inference servers; all communication flows through the service layer for security, auditing, and policy enforcement.</p>

<p>The core path is: <strong>IDE Extension → GitHub Copilot Service (LSP server) → Microsoft Azure Model Endpoints (GPT-4, Claude, Gemini variants) → Response → Client Display</strong>. Each layer has distinct responsibilities: the extension handles context gathering and UI rendering, the service manages authentication, rate-limiting, and data retention policies, and the model endpoints perform inference. This design isolates model updates from client updates and allows Microsoft to scale infrastructure independently.</p>

<h3>Prompt Assembly and Transmission</h3>
<p>When you trigger Copilot (by typing in an editor or requesting a completion), the extension collects context in milliseconds: the current file's content, surrounding code, open tabs, language mode, and cursor position. The extension constructs a structured prompt that includes:</p>
<ul>
  <li><strong>File metadata:</strong> language, file path, name</li>
  <li><strong>Code context:</strong> preceding and following lines (configurable window, typically 500–2000 tokens)</li>
  <li><strong>Cursor position:</strong> exact location where completion is requested</li>
  <li><strong>User preferences:</strong> model selection, style hints, temperature</li>
  <li><strong>Session identifiers:</strong> correlation IDs for tracking and logging</li>
</ul>

<p>The extension applies client-side filters before transmission: excluding secrets (API keys, tokens), filtering content flagged as sensitive, and checking against local blocklists. The prepared prompt is serialized as JSON and transmitted via HTTPS POST to the Copilot service endpoint. Typical prompt payload: 2–15 KB depending on context size. The service receives the request, logs it (according to your plan's retention policy), performs server-side filtering, selects the appropriate model backend based on your subscription tier, and dispatches the request to the LLM.</p>

<h3>Data Handling and Collection</h3>
<p>GitHub Copilot collects multiple types of data:</p>
<ul>
  <li><strong>Prompts and Suggestions:</strong> The code context you send and completions returned.</li>
  <li><strong>User Interactions:</strong> Which suggestions you accepted, rejected, or edited; latency measurements.</li>
  <li><strong>Telemetry:</strong> Extension version, IDE type, feature flags, error rates, performance metrics.</li>
  <li><strong>Authentication:</strong> User identity, organization membership, seat allocation.</li>
  <li><strong>Audit Logs:</strong> API calls, configuration changes (for Enterprise).</li>
</ul>

<p>Data retention and usage differ significantly by subscription plan. <strong>Individual/Free plans:</strong> Microsoft may retain prompts and suggestions for up to 30 days for service improvement and model training. <strong>Business plans:</strong> Prompts and suggestions are NOT retained for training; they are deleted after processing (typically within 24 hours). Telemetry is retained for 90 days for performance monitoring. <strong>Enterprise plans:</strong> Extend Business protections with GDPR data residency options, longer audit log retention (up to 2 years), and custom retention policies. No plan retains credentials or secrets if detected.</p>

<h3>Data Flow Diagrams (Conceptual Paths)</h3>

<p><strong>Request Path:</strong> User keyboard input → Extension context gathering (300 ms typical) → Client-side PII/secret filtering → Prompt serialization → HTTPS transmission → Service authentication & rate-limit check → Server-side content filtering (checking for adult/malware/etc.) → Public code matching (checking if snippet exists in public repos) → Model selection based on user's plan and system load → LLM inference → Response generation.</p>

<p><strong>Response Path:</strong> Model returns ranked suggestions (beam search, top-k sampling) → Server-side filtering re-applied to suggestions → Latency measurement logged → Response serialized with metadata → HTTPS transmission back to client → Extension applies local display filters → Syntax highlighting applied → Inline suggestion shown to user. Full round-trip: 500 ms to 3 seconds depending on network and model backend load.</p>

<p><strong>Content Filtering Pipeline:</strong> Prompts and suggestions are scanned at transmission and response stages using multiple techniques: heuristic keyword matching (profanity, known malware signatures), ML-based content classifiers, and public code dataset matching (to identify code licensed under GPL or other viral licenses, informing the user of potential licensing implications). Enterprise customers can add custom filters (e.g., company-proprietary code detection).</p>

<p><strong>Public Code Matching:</strong> When Copilot generates a suggestion, it queries a database of publicly visible code (from public GitHub repositories, Stack Overflow, etc.). If the suggestion closely matches public code, Copilot can flag it with an "X% match to public code" label, allowing developers to review licensing. This is especially important for GPL-licensed code, where including it without attribution could create legal issues.</p>

<h3>Lifecycle of a Copilot Suggestion</h3>

<table>
  <thead>
    <tr>
      <th>Stage</th>
      <th>Duration</th>
      <th>Activity</th>
      <th>Data Collected</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>1. Triggering</td>
      <td>Instantaneous</td>
      <td>User types or invokes completion command; extension detects trigger event.</td>
      <td>Keystroke timestamp, cursor position, trigger type (auto vs. manual).</td>
    </tr>
    <tr>
      <td>2. Context Gathering</td>
      <td>100–200 ms</td>
      <td>Extension reads file buffer, surrounding code, open tabs, syntax tree.</td>
      <td>File content (up to context window), language identifier, file path (for filtering).</td>
    </tr>
    <tr>
      <td>3. Prompt Construction</td>
      <td>50–100 ms</td>
      <td>Extension assembles JSON request; applies local PII/secret detection.</td>
      <td>Prompt text, metadata (IDE, file type, user preferences), session ID.</td>
    </tr>
    <tr>
      <td>4. Transmission</td>
      <td>100–500 ms (network RTT)</td>
      <td>HTTPS POST to Copilot service; service logs request according to retention policy.</td>
      <td>Full prompt payload, user ID, organization ID, timestamp.</td>
    </tr>
    <tr>
      <td>5. Server Processing</td>
      <td>50–200 ms</td>
      <td>Service authenticates request, checks rate limits, applies server-side filters, routes to model.</td>
      <td>Filtered prompt, model selection decision, rate-limit status.</td>
    </tr>
    <tr>
      <td>6. LLM Inference</td>
      <td>500–2000 ms (varies by model &amp; load)</td>
      <td>Model backend generates multiple suggestions via beam search or sampling.</td>
      <td>Raw model output (not typically logged for retention), generation parameters.</td>
    </tr>
    <tr>
      <td>7. Post-Processing &amp; Filtering</td>
      <td>50–150 ms</td>
      <td>Suggestions re-filtered for content policies; ranked by confidence score; public code matched.</td>
      <td>Filtered suggestions, confidence scores, public code match metadata.</td>
    </tr>
    <tr>
      <td>8. Response Transmission</td>
      <td>100–500 ms (network RTT)</td>
      <td>Suggestions sent to client via HTTPS; client extension receives and renders.</td>
      <td>Suggestion text, metadata (confidence, match info), response timestamp.</td>
    </tr>
    <tr>
      <td>9. Display &amp; User Interaction</td>
      <td>Up to 30 seconds (user interaction window)</td>
      <td>Inline suggestion shown; user accepts, rejects, edits, or ignores.</td>
      <td>User action (accept/reject/edit), time to interaction, edited text if applicable.</td>
    </tr>
    <tr>
      <td>10. Analytics Logging</td>
      <td>Asynchronous (after interaction)</td>
      <td>Extension sends telemetry: user action, latency, suggestion quality signal.</td>
      <td>Interaction outcome, latency breakdown, error flags if any.</td>
    </tr>
  </tbody>
</table>

<h3>Available Models (2026)</h3>
<p>GitHub Copilot supports multiple LLM backends, allowing selection based on use case, cost, and latency requirements:</p>
<ul>
  <li><strong>GPT-4 (OpenAI):</strong> Most capable general-purpose model; highest latency (~2–3 seconds); used for complex multi-line generations and refactoring. Default for Enterprise in 2026.</li>
  <li><strong>GPT-4 Turbo (OpenAI):</strong> Faster than base GPT-4; still high quality; recommended for production code.</li>
  <li><strong>Claude 3.5 (Anthropic):</strong> Strong performance on code generation and reasoning; competitive latency; increasingly used for custom instructions and complex logic.</li>
  <li><strong>Gemini Advanced (Google):</strong> Multimodal capabilities; lower latency than GPT-4; preferred for non-code context (diagrams, design descriptions).</li>
  <li><strong>Copilot Lite (Internal fine-tuned smaller model):</strong> Fast (~500 ms), optimized for single-line completions; default for free/Individual plans.</li>
</ul>

<p>Users on Business and Enterprise plans can toggle the model picker to switch between available backends. Default model selection varies: Free/Individual users see Copilot Lite by default, Business/Enterprise can set org-wide defaults or allow per-developer choice. Model selection is persisted in user preferences and sent with each request to ensure consistent behavior.</p>

<h3>Limitations and Constraints</h3>

<table>
  <thead>
    <tr>
      <th>Constraint</th>
      <th>Individual Plan</th>
      <th>Business Plan</th>
      <th>Enterprise Plan</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><strong>Context Window (tokens)</strong></td>
      <td>4,096–8,192</td>
      <td>8,192–16,384</td>
      <td>16,384–32,768 (model dependent)</td>
    </tr>
    <tr>
      <td><strong>Request Rate Limit</strong></td>
      <td>50 req/min per user</td>
      <td>100 req/min per user (configurable)</td>
      <td>Custom (typically 500+ req/min org-wide)</td>
    </tr>
    <tr>
      <td><strong>Latency Target</strong></td>
      <td>1–5 sec (best-effort)</td>
      <td>500 ms–2 sec (prioritized)</td>
      <td>500 ms–1.5 sec (prioritized with SLA)</td>
    </tr>
    <tr>
      <td><strong>Supported Languages</strong></td>
      <td>35+ languages (varying quality)</td>
      <td>50+ languages</td>
      <td>60+ languages + custom language support</td>
    </tr>
    <tr>
      <td><strong>Code Snippets per Request</strong></td>
      <td>Up to 100 lines context</td>
      <td>Up to 500 lines context</td>
      <td>Up to 2000 lines context</td>
    </tr>
    <tr>
      <td><strong>Concurrent Requests (per org)</strong></td>
      <td>N/A (per-user basis)</td>
      <td>Up to 1000 concurrent</td>
      <td>Up to 5000 concurrent + custom scaling</td>
    </tr>
  </tbody>
</table>

<p>All plans are subject to content policy violations (blocked suggestions include: malware, GPL code without disclosure, hardcoded credentials, adult content). Language quality varies: Python, JavaScript, TypeScript, Java, C#, C++, and Go are tier-1 supported with excellent completion accuracy (&gt;80% user acceptance). Languages like Haskell, Rust, and Kotlin are tier-2 with good support (~60–75% acceptance). Esoteric languages like COBOL or Fortran receive tier-3 support (best-effort; lower accuracy).</p>

<h3>Data Storage, Retention, and Access</h3>

<p><strong>Where Data Is Stored:</strong> GitHub Copilot infrastructure runs on Microsoft Azure in multiple geographic regions (US East, EU West, and others based on GDPR residency requirements). User session data (prompts, suggestions, logs) is stored in encrypted Azure SQL Database and Azure Blob Storage. Audit logs and usage metrics are stored separately in Azure Monitor/Log Analytics. Keys and credentials are managed via Azure Key Vault.</p>

<p><strong>Who Can Access Data:</strong> Microsoft employees with Role-Based Access Control (RBAC) limited roles (engineering, support, security) can access logs for troubleshooting and security investigations. Contractors sign strict NDAs and have time-limited access. GitHub customer support can retrieve metadata (request counts, error rates) but not prompt/suggestion content without explicit customer authorization. Automated systems monitor logs for security threats and policy violations.</p>

<p><strong>Data Retention by Plan:</strong></p>
<ul>
  <li><strong>Individual/Free:</strong> Prompts and suggestions retained up to 30 days for model improvement. Telemetry retained 90 days. After retention window, data is securely deleted.</li>
  <li><strong>Business:</strong> Prompts and suggestions deleted within 24 hours; NOT used for training. Telemetry retained 90 days. Audit logs retained 30 days. Satisfies GDPR Article 17 "right to be forgotten" for prompt data.</li>
  <li><strong>Enterprise:</strong> Extends Business protections. Audit logs retained up to 2 years (configurable). Data residency options (EU data stays in EU; no transfer to US). Custom retention policies per customer contract. Includes Data Processing Addendum (DPA) compliant with GDPR/CCPA.</li>
</ul>

<p><strong>Key Privacy Differences:</strong> Business and Enterprise plans do NOT allow Microsoft to train future models on your code. Individual/Free users implicitly consent to training use. All plans: IP indemnity is included for Enterprise (if Copilot output matches public code and licensing is violated, Microsoft defends). Business gets limited indemnity; Individual has none.</p>

<h3>Network Architecture and Firewall Configuration</h3>

<p>Copilot communicates over HTTPS/TLS 1.2+ to endpoints in Azure. Outbound traffic from your IDE must reach:</p>

<pre><code class="language-json">{
  "primary_endpoints": [
    "https://api.github.copilot.com",
    "https://copilot.github.com"
  ],
  "model_backends": [
    "https://models.eastus.inference.ai.azure.com",
    "https://models.westeurope.inference.ai.azure.com"
  ],
  "telemetry_endpoints": [
    "https://telemetry.copilot.github.com"
  ],
  "authentication": [
    "https://github.com/login/oauth"
  ]
}</code></pre>

<p>Organizations with strict firewall policies can configure proxy servers; the Copilot extension respects HTTP_PROXY and HTTPS_PROXY environment variables. All traffic is encrypted end-to-end; decryption happens only at the service layer. For Enterprise customers, Microsoft can provision dedicated or dedicated-capacity model backends within a VNET, ensuring data never crosses public internet.</p>

<p><strong>Firewall Allow-Listing:</strong> Admins should allow outbound HTTPS on port 443 to the endpoints above. DNS resolution should work for all domains. If your organization uses a web filter, ensure it does not inspect/decrypt HTTPS traffic from Copilot (decryption breaks authentication). The extension performs certificate pinning for additional security—it will reject invalid or self-signed certificates even if your corporate proxy would normally accept them.</p>

<h3>Plan Comparison: Individual vs. Business vs. Enterprise</h3>

<table>
  <thead>
    <tr>
      <th>Feature</th>
      <th>Individual/Free</th>
      <th>Business</th>
      <th>Enterprise</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><strong>Prompt Retention</strong></td>
      <td>30 days (may be used for training)</td>
      <td>24 hours (NOT used for training)</td>
      <td>Configurable, default 24 hours (NOT used for training)</td>
    </tr>
    <tr>
      <td><strong>Suggestion Retention</strong></td>
      <td>30 days (may be used for training)</td>
      <td>24 hours (NOT used for training)</td>
      <td>Configurable, default 24 hours (NOT used for training)</td>
    </tr>
    <tr>
      <td><strong>Public Code Filter</strong></td>
      <td>Basic matching (public GitHub repos)</td>
      <td>Advanced matching (repos + Stack Overflow + licenses)</td>
      <td>Advanced + custom filters (proprietary code detection)</td>
    </tr>
    <tr>
      <td><strong>IP Indemnity</strong></td>
      <td>None</td>
      <td>Limited (Copilot IP coverage only)</td>
      <td>Full (covers both Copilot IP and Business code)</td>
    </tr>
    <tr>
      <td><strong>Audit Logs</strong></td>
      <td>30-day basic telemetry</td>
      <td>30-day audit logs (API calls, errors)</td>
      <td>Configurable up to 2 years + detailed API logs</td>
    </tr>
    <tr>
      <td><strong>Content Exclusions</strong></td>
      <td>Standard policy (no adult/malware)</td>
      <td>Standard + org-configurable blocklists</td>
      <td>Standard + custom domain/IP/pattern blocklists</td>
    </tr>
    <tr>
      <td><strong>Data Residency</strong></td>
      <td>US by default</td>
      <td>US or EU (customer choice)</td>
      <td>US, EU, or custom (GDPR-compliant)</td>
    </tr>
    <tr>
      <td><strong>Model Selection</strong></td>
      <td>Copilot Lite (fixed)</td>
      <td>All models (org-default or per-user)</td>
      <td>All models + custom fine-tuning option</td>
    </tr>
  </tbody>
</table>

<h3>Security and Compliance Highlights</h3>

<p>All data in transit uses TLS 1.2+. Data at rest is encrypted using AES-256 in Azure. GitHub performs quarterly security audits and penetration testing on Copilot infrastructure. The system is SOC 2 Type II compliant (Individual and Business) and extends to ISO 27001 for Enterprise. For sensitive deployments, Enterprise customers can run Copilot in an air-gapped environment with on-premises model hosting (requires Microsoft partnership and custom licensing).</p>
"""

QUESTIONS = [
    (
        "multiple_choice",
        "When a user requests a Copilot suggestion, the IDE extension first gathers context before sending a request. What is the typical purpose of this context-gathering phase?",
        [
            ("To cache suggestions locally so they can be served without network latency", 0),
            ("To collect surrounding code, file metadata, and cursor position to construct a prompt that will be sent to the service", 1),
            ("To verify that the user has a valid Copilot license before making any server calls", 0),
            ("To automatically accept the best suggestion before displaying options to the user", 0),
        ],
        "Correct. The extension gathers code context (preceding/following lines, file metadata, cursor position) to construct a meaningful prompt for the LLM. This context is then sent to the Copilot service."
    ),
    (
        "multiple_choice",
        "Your organization uses GitHub Copilot Business and wants to ensure that code prompts developers send to Copilot will never be used to train future models. Based on the data retention policies, is this requirement met?",
        [
            ("No. Business plans allow Microsoft to retain prompts for 30 days for model training.", 0),
            ("Yes. Business plans explicitly prevent prompts from being retained for training purposes; prompts are deleted within 24 hours.", 1),
            ("Partially. Business plans retain suggestions but not prompts for training.", 0),
            ("No. All plans allow training on user prompts unless Enterprise is purchased.", 0),
        ],
        "Correct. Business plans ensure that prompts and suggestions are NOT retained for training. They are deleted within 24 hours, meeting strict data governance requirements."
    ),
    (
        "multiple_choice",
        "What happens during the post-processing and filtering stage after the LLM generates a suggestion?",
        [
            ("The suggestion is immediately displayed to the user without any additional checks.", 0),
            ("The suggestion is filtered for content policies, ranked by confidence, and checked against public code datasets to identify potential licensing issues.", 1),
            ("The suggestion is encrypted and sent directly to GitHub for archival.", 0),
            ("The suggestion is discarded if it contains more than 10 lines of code.", 0),
        ],
        "Correct. Post-processing includes: re-filtering for content policies, ranking by confidence score, and matching against public code repositories to flag potential licensing concerns (e.g., GPL code)."
    ),
    (
        "multiple_choice",
        "An Enterprise customer has configured a data residency requirement such that all data must remain within the European Union for GDPR compliance. Which aspect of Copilot infrastructure must be reconfigured to meet this requirement?",
        [
            ("The IDE extension must be modified to block any non-EU model backends.", 0),
            ("The Copilot service must route all requests and data storage to Azure regions within the EU.", 1),
            ("The local machine must run a custom DNS server to intercept Copilot traffic.", 0),
            ("Enterprise plans automatically guarantee EU data residency without any configuration.", 0),
        ],
        "Correct. Enterprise customers can choose data residency. When EU residency is required, the service routes all requests to EU Azure regions and stores data only in EU storage accounts."
    ),
    (
        "multiple_choice",
        "Comparing the three subscription plans (Individual, Business, Enterprise), which plan allows customization of content exclusion filters to detect and block company-proprietary code patterns?",
        [
            ("Individual allows basic blocklists; Business adds Stack Overflow filtering.", 0),
            ("Business includes custom domain blocklists; Individual does not.", 0),
            ("Enterprise offers custom domain, IP, and pattern-based exclusion filters; lower tiers do not.", 1),
            ("All plans support custom filters equally; they are always available regardless of tier.", 0),
        ],
        "Correct. Enterprise customers can configure custom blocklists based on domain, IP, or regex patterns to exclude company-proprietary code from triggering Copilot suggestions."
    ),
    (
        "multiple_choice",
        "A developer at your company receives a Copilot suggestion that includes a code snippet marked with \"87% match to public code (GPL v3)\". What is the most appropriate next action?",
        [
            ("Accept the suggestion immediately; Copilot has already verified licensing compliance.", 0),
            ("Reject the suggestion and request a different completion; using GPL code without understanding license terms could create legal risk.", 1),
            ("Edit the suggestion to change variable names so the license no longer applies.", 0),
            ("Accept it if the file is marked as internal-only; public code policy does not apply to internal files.", 0),
        ],
        "Correct. A public code match, especially with a copyleft license like GPL v3, signals a potential licensing issue. The developer should review the license terms and ensure proper attribution or seek alternatives."
    ),
    (
        "multiple_choice",
        "When configuring a corporate firewall to support Copilot, an administrator must allow outbound traffic to several endpoints. Which of the following is a key consideration for Copilot traffic through a web proxy or firewall?",
        [
            ("HTTP (port 80) must be open; HTTPS is optional for Copilot.", 0),
            ("The extension respects HTTP_PROXY and HTTPS_PROXY environment variables; however, corporate certificate inspection (HTTPS decryption) may break Copilot authentication due to certificate pinning.", 1),
            ("All Copilot traffic can be routed through any generic web filter without special configuration.", 0),
            ("Copilot requires custom UDP protocols; standard HTTPS firewall rules do not apply.", 0),
        ],
        "Correct. The Copilot extension supports proxies and performs certificate pinning for security. If corporate firewalls decrypt HTTPS traffic for inspection, the pinned certificates will fail validation, breaking authentication."
    ),
    (
        "multiple_choice",
        "According to the Copilot suggestion lifecycle, approximately how long does the entire request-to-response cycle typically take from the moment a user triggers a completion?",
        [
            ("50–100 ms, accounting only for prompt assembly.", 0),
            ("500–3000 ms (0.5–3 seconds), including context gathering, transmission, LLM inference, and filtering.", 1),
            ("5–10 seconds, due to encryption overhead.", 0),
            ("Latency is negligible; suggestions appear instantaneously.", 0),
        ],
        "Correct. Total latency is typically 500 ms to 3 seconds, dominated by LLM inference time (500–2000 ms) and network round-trip times, with context gathering and post-processing adding 200–400 ms."
    ),
]
