# Auto-generated by _build_gh300.py
LESSON_HTML = """
<h2>Lesson 4: Use GitHub Copilot Features</h2>

<h3>1. Copilot in the IDE: Inline Completions</h3>

<p>GitHub Copilot provides intelligent code completion directly within popular development environments. In <strong>VS Code, Visual Studio, JetBrains IDEs, Neovim, and Xcode</strong>, Copilot appears as ghost-text suggestions as you type. This section explores IDE-specific features and how to maximize productivity with Copilot's completion capabilities.</p>

<p>Ghost-text completions are context-aware predictions that appear grayed out in your editor. Begin typing a function name, class definition, or comment, and Copilot generates multi-line suggestions based on your project structure, imported libraries, and coding patterns. On Windows and Linux, press <strong>Tab</strong> to accept a suggestion; on Mac, use <strong>Tab</strong> or <strong>Cmd+Shift+\</strong>. Press <strong>Escape</strong> to dismiss.</p>

<p>When a ghost-text suggestion doesn't match your intent, use <strong>Alt+]</strong> (or <strong>Option+]</strong> on Mac) to cycle through alternative suggestions. Each press reveals the next candidate completion. This is particularly valuable when Copilot's first guess doesn't align with your logic. You can also explicitly request suggestions by pressing <strong>Ctrl+Enter</strong> in VS Code to open a completion panel showing multiple options.</p>

<table>
<thead>
<tr>
<th>Editor</th>
<th>Inline Completion</th>
<th>Multi-Line Support</th>
<th>Accept Key</th>
<th>Dismiss Key</th>
<th>Alternatives</th>
</tr>
</thead>
<tbody>
<tr>
<td>VS Code</td>
<td>Yes (ghost-text)</td>
<td>Yes (full methods/classes)</td>
<td>Tab / Cmd+Shift+\</td>
<td>Escape</td>
<td>Alt+] or Ctrl+Enter</td>
</tr>
<tr>
<td>Visual Studio 2022</td>
<td>Yes (ghost-text)</td>
<td>Yes</td>
<td>Tab</td>
<td>Escape</td>
<td>Alt+] / IntelliSense menu</td>
</tr>
<tr>
<td>JetBrains (PyCharm, IntelliJ)</td>
<td>Yes (gray suggestion)</td>
<td>Yes</td>
<td>Tab</td>
<td>Escape</td>
<td>Ctrl+Alt+[ or menu</td>
</tr>
<tr>
<td>Neovim</td>
<td>Yes (via plugin)</td>
<td>Yes</td>
<td>Configurable (default Tab)</td>
<td>Configurable</td>
<td>Dependent on plugin</td>
</tr>
<tr>
<td>Xcode</td>
<td>Yes (inline)</td>
<td>Yes</td>
<td>Tab / Return</td>
<td>Escape</td>
<td>Cmd+Period menu</td>
</tr>
</tbody>
</table>

<h3>2. Copilot Chat in the IDE</h3>

<p>Copilot Chat provides a conversational interface embedded directly in your editor, allowing you to ask questions, request code generation, debug issues, and receive explanations without leaving your IDE. Open the Copilot Chat panel via the chat icon in the sidebar (VS Code) or through the IDE's extension menu.</p>

<p><strong>Core Chat Capabilities:</strong> Ask open-ended questions about code patterns, request implementations, explain existing logic, or discuss architecture decisions. The chat maintains context from your current file and editor state.</p>

<p><strong>Slash Commands:</strong> Prefix messages with a slash to invoke specialized workflows:</p>

<ul>
<li><strong>/explain</strong> — Analyze the selected code and provide a detailed explanation of its logic, parameters, and behavior.</li>
<li><strong>/fix</strong> — Identify and suggest fixes for issues in the selected code, including error handling and edge cases.</li>
<li><strong>/tests</strong> — Generate unit tests for the selected function or class, covering normal cases and edge cases.</li>
<li><strong>/doc</strong> — Create documentation (docstrings, comments) for the selected code block.</li>
</ul>

<p><strong>Context Attachments:</strong> Enhance your questions by attaching specific project context using the <strong>#</strong> symbol:</p>

<ul>
<li><strong>#file</strong> — Reference a specific file to include in the conversation context.</li>
<li><strong>#selection</strong> — Attach your currently selected text.</li>
<li><strong>#codebase</strong> — Include broader codebase context for architectural questions.</li>
<li><strong>#web</strong> — Allow Copilot to search the web for up-to-date information (e.g., API documentation, framework updates).</li>
</ul>

<p><strong>Participants:</strong> Invoke specialized agents using the <strong>@</strong> symbol to direct your question:</p>

<ul>
<li><strong>@workspace</strong> — Analyzes your entire project structure and conventions to provide project-aware suggestions.</li>
<li><strong>@terminal</strong> — Understands shell commands, debugging context, and can suggest CLI operations (GitHub Copilot for CLI integration).</li>
<li><strong>@github</strong> — Accesses your GitHub repository metadata, issues, pull requests, and documentation for contextual assistance.</li>
</ul>

<h3>3. Copilot CLI: Command-Line Usage</h3>

<p>GitHub Copilot CLI extends Copilot's capabilities to your terminal, enabling AI-powered command suggestions and explanations from the shell.</p>

<p><strong>Installation:</strong> Authenticate with GitHub and enable the CLI extension:</p>

<pre><code class="language-bash">gh auth login
gh extension install github/gh-copilot
gh extension upgrade gh-copilot</code></pre>

<p><strong>Core Commands:</strong></p>

<ul>
<li><strong>gh copilot suggest</strong> — Describe a task in natural language and receive shell command recommendations.</li>
<li><strong>gh copilot explain</strong> — Paste a shell command to receive an explanation of what it does.</li>
</ul>

<p><strong>Example Usage:</strong></p>

<pre><code class="language-bash"># Get a command suggestion
gh copilot suggest "Find all Python files modified in the last week"

# Explain an existing command
gh copilot explain "find . -name '*.py' -mtime -7"</code></pre>

<p><strong>Configuring Shell Integration:</strong> Enable alias shortcuts for faster access:</p>

<pre><code class="language-bash"># Add to ~/.bashrc or ~/.zshrc
eval "$(gh copilot alias -- bash)"  # or zsh

# Now use shorthand
copilot-suggest "your task"
copilot-explain "command here"</code></pre>

<p>The CLI integrates with your terminal history, environment variables, and file context, making it ideal for scripting, deployment automation, and DevOps workflows.</p>

<h3>4. Agent Mode: Multi-File Edits and Autonomous Task Completion</h3>

<p>Agent Mode (available in Copilot in VS Code as "Agent" or "Edit" mode depending on subscription tier) enables Copilot to propose coordinated changes across multiple files, executing tasks autonomously with human checkpoint approval.</p>

<p><strong>Edit Mode:</strong> When enabled, Copilot can suggest multi-file refactorings, dependency updates, or structural changes. You review each edit in a unified diff view before accepting or discarding.</p>

<p><strong>Key Features:</strong></p>

<ul>
<li><strong>Tool Use:</strong> Agent Mode accesses project analysis tools (file reading, search, AST parsing) to understand dependencies and ensure consistency.</li>
<li><strong>Checkpoints:</strong> Copilot proposes changes in reviewable stages. Accept or discard each checkpoint independently.</li>
<li><strong>Context Preservation:</strong> The agent maintains project context across interactions, preventing conflicts and regressions.</li>
<li><strong>Autonomous Completion:</strong> For well-scoped tasks (e.g., "add logging to all API handlers"), Copilot can execute the entire workflow with minimal user input.</li>
</ul>

<p><strong>Example Agent Workflow:</strong> Request "Refactor this authentication module to use OAuth 2.0 across all API routes." The agent analyzes your codebase structure, identifies all affected files, proposes changes to authentication middleware, updates route handlers, and suggests environment configuration. You review and approve each stage.</p>

<h3>5. Model Context Protocol (MCP)</h3>

<p>The Model Context Protocol enables Copilot to integrate with external data sources, tools, and services, expanding its contextual awareness beyond your IDE. MCP servers act as bridges between Copilot and external systems.</p>

<p><strong>What MCP Servers Provide:</strong> Database query tools, file system explorers, API clients, documentation lookers, version control integrators, and custom business logic connectors.</p>

<p><strong>Configuring MCP (example: ~/.copilot/config.json):</strong></p>

<pre><code class="language-json">{
  "mcp_servers": [
    {
      "name": "filesystem",
      "command": "python",
      "args": ["-m", "mcp.servers.filesystem"],
      "env": {
        "MCP_FILESYSTEM_ROOT": "/path/to/project"
      }
    },
    {
      "name": "postgresql",
      "command": "node",
      "args": ["/path/to/mcp-postgres-server.js"],
      "env": {
        "DATABASE_URL": "postgres://user:pass@localhost/mydb"
      }
    }
  ]
}</code></pre>

<p><strong>Security Implications:</strong> MCP servers execute in a sandboxed context but have access to credentials passed via environment variables. Follow these practices:</p>

<ul>
<li>Use IAM roles or temporary credentials instead of static secrets.</li>
<li>Restrict MCP server permissions to read-only access where possible.</li>
<li>Audit which servers are configured in your organization.</li>
<li>Disable MCP for untrusted projects.</li>
</ul>

<h3>6. Sub-Agents and Copilot Spaces</h3>

<p><strong>Sub-Agents:</strong> Spawn task-specific agents for narrowly scoped workflows. Unlike the main Agent Mode, sub-agents focus on single responsibilities (e.g., "test generation agent," "documentation agent"). Useful for:</p>

<ul>
<li>Delegating code review automation to a dedicated agent.</li>
<li>Running security scanning agents on pull requests.</li>
<li>Generating compliance reports or architecture diagrams.</li>
</ul>

<p><strong>Copilot Spaces:</strong> Create persistent, scoped contexts for repeated workflows. A Space maintains conversation history, file references, and custom prompts specific to a project or team. For example, a "Frontend Architecture Space" could include design system documentation, component patterns, and team conventions, automatically available to all chat interactions within that space.</p>

<h3>7. Copilot Spark</h3>

<p>Copilot Spark is a lightweight prototyping and app generation tool within Copilot. Describe an application idea or provide a mockup, and Spark generates working prototypes (web apps, scripts, or utilities) with minimal scaffolding. Ideal for:</p>

<ul>
<li>Quick internal tools and dashboards.</li>
<li>Proof-of-concept applications.</li>
<li>Educational projects and learning prototypes.</li>
</ul>

<h3>8. Code Review with Copilot</h3>

<p>Copilot integrates with GitHub pull requests to assist with code review. Features include:</p>

<ul>
<li><strong>Automated Suggestions:</strong> Copilot reviews PR diffs and suggests improvements for performance, security, readability, and testing.</li>
<li><strong>Review Summaries:</strong> Generate a summary of changes across all commits in a PR, highlighting what was modified and why.</li>
<li><strong>Inline Comments:</strong> Copilot can suggest specific comments on code blocks, asking clarifying questions or recommending refactorings.</li>
<li><strong>Test Coverage Analysis:</strong> Identify which new code paths lack test coverage.</li>
</ul>

<h3>9. Organization and Enterprise Policies</h3>

<p>GitHub Copilot administrators control feature availability and security policies at the organization level. Admins can:</p>

<table>
<thead>
<tr>
<th>Policy</th>
<th>Description</th>
<th>Impact</th>
</tr>
</thead>
<tbody>
<tr>
<td>Enable/Disable Copilot Chat</td>
<td>Toggle conversational mode for all users</td>
<td>Users cannot use IDE chat; CLI unaffected</td>
</tr>
<tr>
<td>Enable/Disable CLI</td>
<td>Prevent terminal-based Copilot access</td>
<td>gh copilot commands unavailable</td>
</tr>
<tr>
<td>Enable/Disable MCP</td>
<td>Control external tool integration</td>
<td>Limits data access and security surface</td>
</tr>
<tr>
<td>Public Code Filtering</td>
<td>Exclude suggestions from public repositories</td>
<td>Reduces IP/licensing concerns</td>
</tr>
<tr>
<td>Model Selection</td>
<td>Pin specific Copilot model versions</td>
<td>Ensures consistency, controls feature rollout</td>
</tr>
<tr>
<td>Audit Logging</td>
<td>Enable detailed logs of Copilot activity</td>
<td>Compliance, security investigation</td>
</tr>
</tbody>
</table>

<p><strong>Enforcement:</strong> Organizations can enforce policies via GitHub App manifest or organization settings. Individual users cannot override org policies.</p>

<h3>10. Audit Logs and REST API</h3>

<p><strong>Audit Logs:</strong> GitHub exposes Copilot activity in organization audit logs, including:</p>

<ul>
<li>Chat queries and responses (redacted by default; full logs available to org owners).</li>
<li>CLI invocations and model errors.</li>
<li>Policy changes and feature toggles.</li>
<li>Seat assignments and usage metrics.</li>
</ul>

<p><strong>REST API for Copilot Subscriptions:</strong> Manage Copilot seats and usage programmatically:</p>

<pre><code class="language-bash"># List all users with Copilot access
curl -X GET "https://api.github.com/orgs/{org}/copilot/seats" \
  -H "Authorization: token {token}" \
  -H "Accept: application/vnd.github.copilot-preview+json"

# Response includes user name, assignment date, last activity date, pending cancellation status</code></pre>

<p><strong>Key REST Endpoints:</strong></p>

<ul>
<li><strong>GET /orgs/{org}/copilot/seats</strong> — List all Copilot seat assignments.</li>
<li><strong>POST /orgs/{org}/copilot/seats</strong> — Add a user to Copilot (if seats available).</li>
<li><strong>DELETE /orgs/{org}/copilot/seats/{username}</strong> — Revoke Copilot access.</li>
<li><strong>GET /orgs/{org}/copilot/usage</strong> — Retrieve aggregate usage metrics (chat queries, completions, CLI invocations).</li>
</ul>

<p><strong>Example: Bulk Seat Assignment</strong></p>

<pre><code class="language-bash">#!/bin/bash
ORG="my-org"
TOKEN="github_pat_xxxx"

# Read usernames from file and assign Copilot
while read username; do
  curl -X POST "https://api.github.com/orgs/${ORG}/copilot/seats" \
    -H "Authorization: token ${TOKEN}" \
    -H "Accept: application/vnd.github.copilot-preview+json" \
    -d "{\"username\": \"${username}\"}"
done < users.txt</code></pre>

<h3>11. Best Practices and Integration Patterns</h3>

<p><strong>Productivity Tips:</strong></p>

<ul>
<li>Use comments to guide Copilot; descriptive comments lead to better completions.</li>
<li>Attach context (#file, #selection) strategically in chat to avoid unnecessary noise.</li>
<li>Leverage /tests and /doc commands to maintain code quality alongside feature development.</li>
<li>Use Agent Mode for large refactorings but review each checkpoint carefully.</li>
<li>Integrate MCP servers sparingly; each adds overhead and security considerations.</li>
</ul>

<p><strong>Organizational Integration:</strong></p>

<ul>
<li>Define team guidelines for Copilot usage (chat for architectural questions, CLI for scripting, etc.).</li>
<li>Enable audit logs and review them weekly to understand adoption patterns.</li>
<li>Train teams on context attachment (#codebase for architectural consistency, #web for external APIs).</li>
<li>Use Copilot Spaces to standardize workflows across projects.</li>
</ul>

<h3>12. Common Scenarios and Limitations</h3>

<p><strong>Scenario: Debugging an obscure error message</strong></p>

<p>Use <strong>/fix</strong> command with #selection on the error line and surrounding context. Copilot correlates error patterns with fixes from similar codebases.</p>

<p><strong>Scenario: Implementing a complex algorithm across an unfamiliar codebase</strong></p>

<p>Request Agent Mode with #codebase context, ensuring Copilot understands naming conventions and existing patterns before proposing changes.</p>

<p><strong>Limitations:</strong></p>

<ul>
<li>Copilot cannot execute code directly; Agent Mode generates proposals you must review.</li>
<li>Public code filtering may limit suggestions for common libraries (intentional for IP reasons).</li>
<li>MCP configuration mistakes can expose sensitive credentials; use environment variable scoping.</li>
<li>Chat context windows are finite; very large files may exceed context limits.</li>
</ul>
"""

QUESTIONS = [
    (
        "multiple_choice",
        "Your team uses VS Code and wants to cycle through Copilot completion suggestions to find an alternative to the ghost-text showing. What keyboard shortcut accomplishes this without opening a menu?",
        [
            ("Alt+] to cycle to the next suggestion", 1),
            ("Ctrl+Space to reset suggestions", 0),
            ("Shift+Tab to go backwards", 0),
            ("Cmd+Enter to refresh completions", 0),
        ],
        "Alt+] (or Option+] on Mac) cycles through alternative suggestions in the ghost-text. Ctrl+Enter opens a menu but does not cycle through inline."
    ),
    (
        "multiple_choice",
        "In Copilot Chat, you want to ask a question about debugging a specific function but ensure Copilot understands the broader project architecture. Which context attachment should you include?",
        [
            ("#selection to attach just the function", 0),
            ("#codebase to include project structure and conventions", 1),
            ("#web to search external documentation", 0),
            ("#file to reference one related file", 0),
        ],
        "#codebase is designed for architectural questions and provides Copilot with broader project context. #selection is too narrow; #web is for external info; #file is single-file scoped."
    ),
    (
        "multiple_choice",
        "Your organization has disabled the Copilot CLI feature via policy. Which user workflow is affected?",
        [
            ("VS Code inline completions are disabled", 0),
            ("Copilot Chat in the IDE is disabled", 0),
            ("Terminal commands like gh copilot suggest become unavailable", 1),
            ("Agent Mode cannot propose multi-file edits", 0),
        ],
        "CLI policy controls terminal access (gh copilot suggest/explain). IDE inline completions, chat, and Agent Mode are separate toggles."
    ),
    (
        "multiple_choice",
        "You configure an MCP server to provide database query capabilities to Copilot. What is the primary security concern with this setup?",
        [
            ("MCP servers cannot be sandboxed and have unlimited filesystem access", 0),
            ("Database credentials passed via environment variables could be exposed if the MCP process is compromised", 1),
            ("Copilot can directly execute arbitrary SQL without user review", 0),
            ("MCP servers must run as root to access databases", 0),
        ],
        "MCP servers are sandboxed but receive credentials via env vars. If the server is compromised, those credentials are at risk. Use IAM roles or temporary credentials instead."
    ),
    (
        "multiple_choice",
        "An enterprise admin wants to ensure Copilot suggestions do not include code patterns from public GitHub repositories due to IP concerns. Which policy should be enforced?",
        [
            ("Disable MCP servers", 0),
            ("Enable public code filtering", 1),
            ("Disable Copilot Chat", 0),
            ("Restrict model selection", 0),
        ],
        "Public code filtering is the explicit policy to exclude suggestions from public repos. Disabling chat or MCP affects different features."
    ),
    (
        "multiple_choice",
        "You use Copilot Agent Mode to propose a large refactoring across 12 files. The agent generates changes in stages. What is the primary advantage of this checkpoint-based approach?",
        [
            ("Changes are automatically applied without user review", 0),
            ("It reduces the time needed for the refactoring", 0),
            ("You can review and approve each stage independently, reducing risk of breaking changes", 1),
            ("It allows Copilot to execute code after each checkpoint", 0),
        ],
        "Checkpoints enable staged review, allowing you to accept or discard each block of changes. This maintains control and reduces regression risk."
    ),
    (
        "multiple_choice",
        "Your organization uses the Copilot REST API to manage seat assignments. You want to retrieve the total number of Copilot queries executed by your organization in the past month. Which endpoint should you call?",
        [
            ("GET /orgs/{org}/copilot/seats", 0),
            ("GET /orgs/{org}/copilot/usage", 1),
            ("POST /orgs/{org}/copilot/seats", 0),
            ("DELETE /orgs/{org}/copilot/seats/{username}", 0),
        ],
        "The /usage endpoint provides aggregate metrics including chat queries and completions. /seats endpoints manage seat assignments, not usage metrics."
    ),
    (
        "multiple_choice",
        "In Copilot Chat, you want to ask the @terminal participant for a shell command recommendation. What type of prompt would be most effective?",
        [
            ("@terminal, how do I write code in Python?", 0),
            ("@terminal, suggest a command to find files modified in the last 24 hours", 1),
            ("@terminal, what is the GitHub API?", 0),
            ("@terminal, refactor my React component", 0),
        ],
        "@terminal is specialized for shell commands and DevOps tasks. Python coding, APIs, and React refactoring are better suited to default chat or other participants."
    ),
]
