# Auto-generated by _build_gh300.py
LESSON_HTML = """
<h2>Lesson 6: Apply Prompt Engineering and Context Crafting</h2>

<h3>Introduction: The Power of Clear Prompts</h3>
<p>GitHub Copilot is fundamentally a prediction engine trained on vast code repositories and documentation. Its output quality depends directly on the clarity, specificity, and context of your instructions. A well-crafted prompt can turn Copilot from a random code suggester into a precise coding partner that understands your exact intent. This lesson teaches you how to engineer prompts that reliably produce high-quality completions, whether using inline suggestions or Copilot Chat.</p>

<h3>Why Prompts Matter for Copilot Quality</h3>
<p>Copilot generates code by predicting the most likely next tokens based on:</p>
<ul>
<li>The visible code context (open file, selection, surrounding code)</li>
<li>Your explicit prompt (code comment, function signature, or Chat message)</li>
<li>Workspace and repository instructions</li>
<li>Training patterns from billions of code examples</li>
</ul>
<p>Poor prompts lead to generic, incorrect, or irrelevant suggestions. Strong prompts align Copilot's prediction with your actual intent, dramatically improving the quality of generated code. Prompt engineering is not a "nice-to-have"—it is a core skill for maximizing Copilot's value in production development.</p>

<h3>Inline Completion Prompts: Guiding Code Suggestions</h3>
<p><strong>Code comments</strong> are the primary mechanism for steering inline completions. A well-written comment provides context, intent, and constraints that Copilot uses to generate the next lines of code.</p>

<p><strong>Example 1: Weak vs. Strong Comment Prompts</strong></p>
<pre><code class="language-python">// Weak: Too vague
// process data

// Strong: Clear intent, specific action
// Filter users by age and sort by last login date, newest first
</code></pre>

<p>The strong comment tells Copilot exactly what data transformation is needed, enabling it to generate the correct filtering and sorting logic. Without this specificity, Copilot might guess at your intent or produce incomplete code.</p>

<p><strong>Descriptive function signatures</strong> also serve as prompts. Copilot predicts the function body based on the name, parameters, and return type:</p>
<pre><code class="language-python">// Weak signature
def process(x):
    pass

// Strong signature
def calculate_monthly_recurring_revenue(subscription_list: List[Subscription]) -> float:
    \"\"\"Return total MRR from active subscriptions, excluding trials.\"\"\"
    pass
</code></pre>

<p><strong>Variable and function names matter.</strong> Descriptive names provide semantic context:</p>
<pre><code class="language-python">// Weak
result = f(data, 30)

// Strong
max_retries_exceeded = check_retry_limit(failed_attempts, MAX_ATTEMPTS)
</code></pre>

<p><strong>Surrounding code context.</strong> Copilot examines visible code above and below the cursor. Providing relevant examples or existing patterns dramatically improves suggestions:</p>
<pre><code class="language-python">// If this function exists above:
def validate_email(email: str) -> bool:
    return "@" in email and "." in email.split("@")[1]

// Copilot can infer the same pattern for related validators:
def validate_phone(phone: str) -> bool:
    // Copilot will likely generate a similar validation pattern
    pass
</code></pre>

<h3>Copilot Chat Prompts: Structured Communication</h3>
<p>Chat enables more complex interactions than inline comments. Effective Chat prompts follow a structured approach:</p>

<p><strong>The 4-S Framework for Chat Prompts:</strong></p>
<ol>
<li><strong>Single:</strong> Focus on one primary goal per message. Don't ask Copilot to refactor code AND write tests AND optimize performance in one prompt.</li>
<li><strong>Specific:</strong> Name the exact files, functions, or features involved. "Refactor the login handler" is more specific than "improve the code."</li>
<li><strong>Short:</strong> Keep the core request concise. Long, rambling prompts dilute the signal and increase the chance of hallucination.</li>
<li><strong>Surround:</strong> Provide context through references (#file, #codebase, #web, #terminal) and code snippets. Don't make Copilot guess what code you're talking about.</li>
</ol>

<p><strong>Example: Applying the 4-S Framework</strong></p>
<pre><code class="language-markdown">Weak prompt:
"I need help with my function. It's supposed to process some data but I think it's slow. Can you look at it and make it work better? Also, what about error handling?"

Strong prompt (applying 4-S):
"Optimize the query in #file:src/db.py function `fetch_user_orders()`. It currently loads all orders into memory before filtering. I need to filter by date range first in the database query for a 10,000+ order dataset. Use pagination if needed."
</code></pre>

<p>The strong prompt is single (optimize that query), specific (which file and function), short (one clear goal), and surrounded (describes the problem and constraint).</p>

<h3>Context Engineering: What Counts as Context</h3>
<p>Copilot's predictions depend on available context. Understanding what counts as context allows you to provide exactly what you need:</p>

<table>
<thead>
<tr>
<th>Context Source</th>
<th>Availability</th>
<th>How to Use</th>
</tr>
</thead>
<tbody>
<tr>
<td>Open files</td>
<td>Always visible to Copilot</td>
<td>Keep relevant files open. Copilot weight nearby code more heavily than distant code.</td>
</tr>
<tr>
<td>Current selection</td>
<td>Highest priority when requesting Chat completion of selection</td>
<td>Select specific code blocks before invoking Chat for inline refactoring or explanation.</td>
</tr>
<tr>
<td>#file:path reference</td>
<td>Explicitly included via Chat mention</td>
<td>Use #file:src/api.py to include a specific file in Chat context even if it's not open.</td>
</tr>
<tr>
<td>#codebase reference</td>
<td>Indexes workspace structure and key files</td>
<td>Use #codebase to enable Copilot to search and understand the full project architecture.</td>
</tr>
<tr>
<td>#web reference</td>
<td>Can fetch current web documentation</td>
<td>Use #web to get latest API docs or library examples not in training data.</td>
</tr>
<tr>
<td>#terminal context</td>
<td>Recent commands and outputs</td>
<td>Use #terminal to include error messages, logs, or CLI feedback in Chat prompts.</td>
</tr>
<tr>
<td>Workspace instructions</td>
<td>Automatically loaded if configured</td>
<td>Place copilot-instructions.md in workspace root for persistent context (coding style, patterns, conventions).</td>
</tr>
<tr>
<td>Agent instructions (.agent.md)</td>
<td>Loaded when agent is activated</td>
<td>Define role, capabilities, and behavioral constraints for specialized workflows.</td>
</tr>
</tbody>
</table>

<p><strong>Context tip:</strong> Copilot prioritizes context in this order: current selection > visible code > referenced files (#file) > workspace instructions > general codebase. Maximize signal by being strategic about what you expose.</p>

<h3>Workspace Instructions: Persistent Prompt Engineering</h3>
<p>Rather than repeating coding conventions in every prompt, define them once in workspace instruction files:</p>

<p><strong>copilot-instructions.md</strong> — Automatically loaded in any Copilot context within the workspace:</p>
<pre><code class="language-markdown"># Coding Conventions for Project X

## Language & Framework
- Use TypeScript with strict null checks
- Target ES2020+ (no IE11 support)
- Use React hooks only; no class components

## Code Style
- Prettier formatting with 2-space indents
- ESLint recommended rules enabled
- Use functional components with named exports

## Naming
- PascalCase for React components and classes
- camelCase for functions and variables
- SCREAMING_SNAKE_CASE for constants

## Testing
- Jest for unit tests; Cypress for E2E
- Aim for >80% coverage
- Mock external APIs in unit tests

## Error Handling
- Always include try-catch for async operations
- Use custom AppError class with context
- Never swallow errors; log with context
</code></pre>

<p><strong>.github/copilot/instructions/*.instructions.md</strong> — Scoped to specific file patterns (applyTo):</p>
<pre><code class="language-markdown">---
applyTo:
  - "src/api/**/*.ts"
---

# API Route Handlers

- Validate input with Zod schemas (see src/schemas/)
- Return JSON responses with consistent shape: { success: boolean, data?: T, error?: string }
- All routes must be wrapped with errorHandler middleware
- Use async/await; never use .then() chains
</code></pre>

<p>.prompt.md files store reusable prompt templates:</p>
<pre><code class="language-markdown"># Reusable Prompts

## Refactoring
"Refactor this function for readability. Split long logic into smaller helper functions. Add JSDoc comments. Ensure TypeScript types are strict."

## Testing
"Write Jest unit tests for this function. Cover happy path and error cases. Mock dependencies. Aim for 100% line coverage."

## Documentation
"Write clear JSDoc comments for this function explaining parameters, return value, side effects, and typical usage."
</code></pre>

<p><strong>Custom Agents (.agent.md)</strong> — Define specialized Copilot behavior for specific roles:</p>
<pre><code class="language-markdown">---
name: "Security Reviewer"
description: "Reviews code for security vulnerabilities and compliance"
---

# Security-Focused Code Reviewer

You are a security expert specializing in Web application vulnerabilities (OWASP Top 10, CWE).

## Capabilities
- Identify injection vulnerabilities (SQL, XSS, command injection)
- Flag insecure cryptography and weak random number generation
- Detect authentication and authorization flaws
- Catch sensitive data exposure (credentials, PII in logs)

## Behavior
- Always ask: "Is this input user-controlled?"
- Recommend mitigations with specific code examples
- Reference OWASP standards and CVE precedents
</code></pre>

<h3>Engineering Prompts for Performance</h3>
<p>Complex tasks benefit from strategic prompt engineering patterns:</p>

<p><strong>Chain-of-Thought:</strong> Ask Copilot to think through the problem step-by-step before generating code. This reduces hallucinations for complex logic:</p>
<pre><code class="language-markdown">Weak:
"Write a function that detects if a graph has a cycle."

Strong:
"Design a function to detect if a directed graph has a cycle. First, outline the algorithm (DFS with color marking). Then, implement it. Explain the time complexity."
</code></pre>

<p><strong>Few-Shot Examples:</strong> Show Copilot an example of desired output format before asking it to generate similar code:</p>
<pre><code class="language-markdown">Example input/output:
Input: [1, 3, 5, 7]
Output: { count: 4, sum: 16, average: 4 }

Input: [2, 4, 6]
Output: { count: 3, sum: 12, average: 4 }

Now generate the function that produces this output:

function summarize(numbers: number[]): { count: number; sum: number; average: number } {
    // Implement here
}
</code></pre>

<p><strong>Plan First, Code Second:</strong> For complex features, ask for a plan or pseudocode before implementation:</p>
<pre><code class="language-markdown">Weak:
"Build a real-time data sync system between client and server."

Strong:
"Design a real-time sync system:
1. Outline the architecture (client diff detection, server merge strategy, conflict resolution)
2. Write pseudocode for the three core functions: detectChanges, mergeUpdates, resolveConflict
3. Then implement each function in TypeScript with proper error handling"
</code></pre>

<p><strong>Ask for Tests Upfront:</strong> Request test cases alongside implementation to clarify intent:</p>
<pre><code class="language-markdown">"Write a function to calculate shipping cost. Provide test cases first showing:
- Standard domestic order (5 lbs, $50)
- Oversized item (60 lbs, $500)
- Free shipping threshold ($100+)
- International order (applies 1.5x multiplier)
Then implement the function to pass all tests."
</code></pre>

<h3>Iterating with Chat: Refining Prompts and Outputs</h3>
<p>Copilot Chat enables a dialogue. If the first response isn't right, iterate:</p>

<p><strong>Follow-ups with additional constraints:</strong></p>
<pre><code class="language-markdown">Round 1:
"Generate a sorting function for the User list."

Round 2 (if output is too simple):
"Sort users by created_at descending, then by name ascending. Handle null values. Add TypeScript strict types. Include unit tests."

Round 3 (if performance is a concern):
"The dataset is 1M users. Optimize for memory efficiency. Avoid loading all data into memory at once. Use a streaming sort if possible."
</code></pre>

<p><strong>Providing rejected output as feedback:</strong></p>
<pre><code class="language-markdown">"This approach won't work because we can't call external APIs in middleware. Instead, queue the task and process it asynchronously. Show me how to use Bull job queue for this."
</code></pre>

<p><strong>Asking for alternatives:</strong></p>
<pre><code class="language-markdown">"Show me three different ways to validate that email. One using regex, one using a library, one using an API call. Compare pros and cons of each approach."
</code></pre>

<h3>Prompt Patterns: Templates for Common Tasks</h3>
<p><strong>Persona Pattern:</strong> Define a role for Copilot to adopt, clarifying your expectations:</p>
<pre><code class="language-markdown">"Act as a TypeScript expert focused on performance optimization. Review this function for bottlenecks and suggest improvements with specific metrics (time complexity, memory usage)."
</code></pre>

<p><strong>Task Decomposition Pattern:</strong> Break a large request into ordered subtasks:</p>
<pre><code class="language-markdown">"I need to build user authentication. Break this into:
1. Database schema for users
2. Password hashing and validation
3. JWT token generation and verification
4. Middleware to check authorization
5. Login and logout endpoints

For each step, show schema/code and any dependencies."
</code></pre>

<p><strong>Output Schema Pattern:</strong> Specify the exact format you want:</p>
<pre><code class="language-markdown">"Generate 5 test cases for the payment function. Format each as:
{
  \"name\": \"Test name\",
  \"input\": { /* sample input */ },
  \"expectedOutput\": { /* expected result */ },
  \"reason\": \"Why this test matters\"
}"
</code></pre>

<p><strong>Constraint Pattern:</strong> Explicitly limit the solution space:</p>
<pre><code class="language-markdown">"Write a cache implementation with these constraints:
- Max 1000 items
- LRU eviction
- O(1) get and set operations
- No external libraries (implement from scratch)
- Include unit tests"
</code></pre>

<p><strong>Anti-patterns to avoid:</strong></p>
<ul>
<li><strong>Vague intent:</strong> "Fix the code" vs. "Add null-safety checks using optional chaining and nullish coalescing"</li>
<li><strong>Overloaded requests:</strong> Asking for code, tests, docs, optimization, and edge cases in one message</li>
<li><strong>Leading suggestions:</strong> "I think we need a Map here..." — let Copilot suggest the data structure</li>
<li><strong>Context dumping:</strong> Pasting 500 lines of code without highlighting the relevant section</li>
<li><strong>Passive voice:</strong> "Errors should be handled" vs. "Wrap async operations in try-catch and log errors to logger.error()"</li>
</ul>

<h3>Common Failure Modes and Recovery</h3>
<p><strong>Hallucinated APIs:</strong> Copilot generates code using non-existent functions or libraries:</p>
<pre><code class="language-markdown">Failure:
// Copilot suggested: data.sortBy('name', { locale: 'en' })
// But sortBy doesn't exist on Array

Recovery:
"The .sortBy() method doesn't exist. Use the built-in Array.sort() with Intl.Collator for locale-aware sorting. Show me how."
</code></pre>

<p><strong>Ignored constraints:</strong> Output doesn't respect your requirements:</p>
<pre><code class="language-markdown">Failure:
// You asked for <100 lines; Copilot generated 300-line baroque solution

Recovery:
"This is too complex. Simplify to <100 lines, remove unnecessary abstraction, just solve the core problem directly."
</code></pre>

<p><strong>Off-topic code:</strong> Copilot misunderstands the goal:</p>
<pre><code class="language-markdown">Failure:
// You asked for input validation; Copilot generated database schema

Recovery:
"I need validation that runs on the client before sending to the API, not database constraints. Use Zod to validate the form data shape."
</code></pre>

<p><strong>Recovery strategies:</strong></p>
<ol>
<li>Show the rejected output and explicitly say why it failed</li>
<li>Restate the core constraint or goal more forcefully</li>
<li>Provide a code snippet showing the desired pattern</li>
<li>Reference #web or #codebase to ground Copilot in real examples</li>
<li>Break the task into smaller substeps</li>
<li>Use a different Chat agent or workspace instructions to reset context</li>
</ol>

<h3>Best Practices Summary</h3>
<p>Master prompt engineering through practice:</p>
<ul>
<li><strong>Be specific:</strong> Name variables, functions, constraints, and expected outputs</li>
<li><strong>Provide context:</strong> Use #file, #codebase, #web, and open relevant code</li>
<li><strong>Iterate:</strong> The first response rarely perfects the solution; refine via follow-ups</li>
<li><strong>Explain intent, not just tasks:</strong> "Reduce database queries for 10K+ user datasets" gives Copilot more signal than "optimize this"</li>
<li><strong>Use workspace instructions:</strong> Centralize conventions so you don't repeat them in every prompt</li>
<li><strong>Test output:</strong> Always verify Copilot's code works before shipping; don't blindly trust generated code</li>
<li><strong>Leverage agents and patterns:</strong> Specialized agents and prompt templates speed up common workflows</li>
</ul>
"""

QUESTIONS = [
    (
        "multiple_choice",
        "When writing an inline code comment to guide Copilot's completion, what makes a prompt effective?",
        [
            ("Using technical jargon and abbreviations to be concise", 0),
            ("Describing the intent, specific action, and any constraints in clear language", 1),
            ("Asking a question mark at the end of the comment", 0),
            ("Copying the function signature twice for emphasis", 0),
        ],
        "Effective inline comments are specific, describe intent, and use clear language. Copilot predicts code based on semantic meaning, not jargon or formatting tricks. A comment like 'Filter users by age and sort by last login date, newest first' tells Copilot exactly what to generate."
    ),
    (
        "multiple_choice",
        "Which context source does Copilot prioritize MOST heavily when making predictions?",
        [
            ("Files indexed by #codebase reference", 0),
            ("The current selection and visible code around the cursor", 1),
            ("Workspace instructions in copilot-instructions.md", 0),
            ("Web documentation fetched via #web reference", 0),
        ],
        "Copilot prioritizes: current selection > visible code > #file references > workspace instructions > general codebase. The code immediately surrounding the cursor carries the strongest signal for predictions."
    ),
    (
        "multiple_choice",
        "You ask Copilot Chat: 'Refactor the code and optimize performance and add tests and improve documentation.' What is the problem with this prompt?",
        [
            ("It is too specific and will confuse Copilot", 0),
            ("It violates the Single principle by requesting multiple unrelated tasks in one message", 1),
            ("It uses too many 'and' words and should use commas instead", 0),
            ("It does not reference any files with #file, so Copilot will hallucinate", 0),
        ],
        "The prompt violates the 'Single' principle of the 4-S framework. Each message should focus on one primary goal. Asking for refactoring AND performance optimization AND tests AND documentation dilutes the signal and increases hallucination risk. Send separate, focused prompts for each goal."
    ),
    (
        "multiple_choice",
        "How should you use workspace instructions (.instructions.md or copilot-instructions.md) in prompt engineering?",
        [
            ("To replace every inline comment in your code", 0),
            ("To define persistent coding conventions and patterns so you do not repeat them in every prompt", 1),
            ("To store only error messages and debugging tips", 0),
            ("To configure GitHub Copilot keyboard shortcuts", 0),
        ],
        "Workspace instructions centralize coding conventions, style guides, and project patterns. This reduces prompt boilerplate because Copilot automatically loads these instructions in every context, so you don't repeat 'use TypeScript with strict types' in every Chat message."
    ),
    (
        "multiple_choice",
        "When Copilot generates code using an API method that does not exist (hallucination), what is the BEST recovery strategy?",
        [
            ("Delete the code immediately and never ask Copilot for help again", 0),
            ("Explicitly state the hallucination, explain why it failed, and ask for a corrected version using real methods", 1),
            ("Assume Copilot is always correct and implement the non-existent API yourself", 0),
            ("Paste the error message without context and hope Copilot guesses the fix", 0),
        ],
        "When Copilot hallucinates APIs, iterate by clearly stating the failure ('that method does not exist'), explain the actual constraint, and ask for a revised solution using real methods. Provide a correct example if possible. This feedback helps Copilot recalibrate."
    ),
    (
        "multiple_choice",
        "Which pattern is BEST for requesting complex multi-step implementations like a real-time sync system?",
        [
            ("Ask for the full implementation in a single message", 0),
            ("Ask Copilot to outline the architecture and pseudocode first, then implement each component in separate messages", 1),
            ("Provide no context and let Copilot invent the architecture", 0),
            ("Request the code, tests, and documentation in one message", 0),
        ],
        "The 'Plan First, Code Second' pattern works best for complex features. First, ask Copilot to design the architecture or write pseudocode. Then, implement each component in subsequent messages. This reduces hallucinations and ensures the overall structure is sound before coding begins."
    ),
    (
        "multiple_choice",
        "What is the primary advantage of using few-shot examples in Copilot Chat prompts?",
        [
            ("It guarantees Copilot will never make mistakes", 0),
            ("It shows Copilot the exact input-output format you expect, dramatically improving response accuracy", 1),
            ("It reduces the number of tokens in your prompt", 0),
            ("It prevents Copilot from accessing the codebase", 0),
        ],
        "Few-shot examples demonstrate the desired output format and behavior. When you show Copilot 2-3 examples of input paired with expected output, it learns the pattern and generates subsequent responses matching that format. This is more effective than describing the format in words."
    ),
    (
        "multiple_choice",
        "A Copilot Chat agent (.agent.md file) with applyTo pattern 'src/api/**/*.ts' will be invoked when?",
        [
            ("Only when you manually select 'Security Reviewer' from a dropdown menu", 0),
            ("Automatically when you reference or edit TypeScript files matching the path pattern src/api/*/*.ts", 1),
            ("Never, because .agent.md files are deprecated", 0),
            ("Only when you use the #codebase reference", 0),
        ],
        "Custom agents with applyTo patterns are automatically invoked when you work with files matching the pattern. An agent with applyTo 'src/api/**/*.ts' activates when you reference or edit API route files, providing specialized context and capabilities for that domain."
    ),
]
