# Auto-generated by _build_gh300.py
LESSON_HTML = """
<h2>Lesson 3: Use GitHub Copilot Responsibly</h2>

<h3>Introduction: AI Governance and Developer Responsibility</h3>
<p>GitHub Copilot is a powerful tool powered by large language models (LLMs), but its power brings responsibility. As developers adopt AI-assisted coding, organizations must establish guardrails to ensure Copilot enhances productivity without compromising security, compliance, intellectual property rights, or team quality standards. This lesson explores responsible AI principles, Copilot's inherent limitations, validation strategies, and organizational policies that govern ethical AI use.</p>

<h3>Responsible AI Principles Applied to Copilot</h3>
<p>Microsoft and GitHub have grounded Copilot in six core responsible AI pillars:</p>
<ul>
<li><strong>Fairness:</strong> Ensure Copilot suggestions do not systematically disadvantage particular groups or encode discriminatory logic. Code should be inclusive and non-biased.</li>
<li><strong>Reliability and Safety:</strong> Copilot outputs must be safe, secure, and free from introducing vulnerabilities or runtime errors that could cascade in production.</li>
<li><strong>Privacy and Security:</strong> Code snippets processed by Copilot must respect confidentiality; secrets and sensitive data must never be submitted.</li>
<li><strong>Inclusiveness:</strong> Suggestions should support diverse coding styles, accessible patterns, and culturally aware implementations.</li>
<li><strong>Transparency:</strong> Developers must understand that Copilot is AI-generated, not human-written, and that training data origins may include public open-source repositories.</li>
<li><strong>Accountability:</strong> Teams and organizations remain accountable for code deployed to production, regardless of AI assistance. Human review is non-negotiable.</li>
</ul>

<h3>Limitations of LLM Code Suggestions</h3>
<p>While Copilot accelerates development, it is not perfect. Understanding its limitations is essential for responsible use:</p>
<ul>
<li><strong>Hallucinations:</strong> Copilot can generate code that looks syntactically correct but is functionally nonsensical or calls non-existent APIs. Example: suggesting a method on a library version that has never existed.</li>
<li><strong>Outdated APIs and Patterns:</strong> Training data includes older libraries and deprecated practices. Copilot may suggest outdated patterns rather than modern best practices.</li>
<li><strong>Insecure Patterns:</strong> LLMs learn from public code, which often includes poor security practices. Copilot may suggest hardcoded credentials, weak cryptography, or SQL injection-prone queries.</li>
<li><strong>Biased Completions:</strong> Training data reflects societal biases. Suggestions may inadvertently encode assumptions about gender, nationality, or capability.</li>
<li><strong>Licensing and Attribution Concerns:</strong> Training data includes copyrighted and open-source code. Generated suggestions may inadvertently reproduce substantial portions of licensed code without attribution.</li>
<li><strong>Context Limitations:</strong> Copilot operates on limited context window; it may not grasp your entire codebase architecture or business constraints.</li>
</ul>

<h3>Validating Copilot Output: A Structured Approach</h3>
<p>Never trust Copilot suggestions implicitly. Employ a multi-layered validation strategy:</p>

<table>
<thead>
<tr>
<th>Validation Layer</th>
<th>Method</th>
<th>Focus Area</th>
<th>Tool/Approach</th>
</tr>
</thead>
<tbody>
<tr>
<td>Code Review</td>
<td>Manual peer review of Copilot-assisted code</td>
<td>Logic correctness, security, adherence to standards</td>
<td>Pull request review; explicitly flag AI-assisted sections</td>
</tr>
<tr>
<td>Testing</td>
<td>Unit tests, integration tests, E2E tests</td>
<td>Functional correctness, edge cases, error handling</td>
<td>Jest, pytest, xUnit; aim for &gt;80% coverage</td>
</tr>
<tr>
<td>Security Scanning</td>
<td>SAST (static analysis), dependency scanning</td>
<td>Injection flaws, weak crypto, known CVEs</td>
<td>SonarQube, Snyk, GitHub Advanced Security</td>
</tr>
<tr>
<td>Dependency Checks</td>
<td>License compliance, version audits</td>
<td>GPL conflicts, deprecated libraries, supply chain risk</td>
<td>Software Composition Analysis (SCA) tools</td>
</tr>
<tr>
<td>Public Code Matching</td>
<td>Citation and reference checking</td>
<td>Whether suggestion is a near-verbatim copy of public code</td>
<td>Copilot's built-in reference panel; manual GitHub search</td>
</tr>
</tbody>
</table>

<h3>Operating Copilot Responsibly: Best Practices</h3>
<p><strong>Keep Human-in-the-Loop:</strong> Always review Copilot output before committing. Treat suggestions as a starting point, not a finished solution.</p>
<p><strong>Prefer Small, Focused Suggestions:</strong> Request specific, narrow prompts (e.g., "write a Python function to validate email") rather than vague ones. Narrow prompts produce more predictable, safer results.</p>
<p><strong>Label AI-Assisted Pull Requests:</strong> Use commit messages and PR descriptions to flag where Copilot contributed, e.g., "feat: add user auth (Copilot-assisted)". This supports accountability and allows reviewers to heighten scrutiny.</p>
<p><strong>Follow Team and Organizational Policies:</strong> Organizations may restrict Copilot use in certain contexts (regulated code, security-critical paths). Adhere to your team's guidelines.</p>
<p><strong>Verify for Edge Cases and Error Handling:</strong> LLMs tend to generate happy-path code. Manually add error handling, null checks, and defensive programming constructs.</p>

<h3>Example: Validating a Copilot Suggestion</h3>
<p>Scenario: Copilot suggests a function to parse and validate a payment amount:</p>
<pre><code class="language-python">def parse_amount(amount_str):
    return float(amount_str)
</code></pre>
<p><strong>Issues:</strong> No validation, no error handling, no protection against NaN or infinity. A responsible developer would enhance this:</p>
<pre><code class="language-python">import decimal
import logging

def parse_amount(amount_str: str) -> decimal.Decimal:
    \"\"\"Parse and validate a payment amount. Raises ValueError if invalid.\"\"\"
    try:
        amount = decimal.Decimal(amount_str)
        if amount &lt; 0:
            raise ValueError("Amount cannot be negative")
        if amount &gt; decimal.Decimal("999999.99"):
            raise ValueError("Amount exceeds maximum allowed value")
        return amount
    except (decimal.InvalidOperation, ValueError) as e:
        logging.error(f"Invalid amount: {amount_str}, error: {e}")
        raise
</code></pre>

<h3>Intellectual Property and Licensing</h3>
<p><strong>Public Code Filter:</strong> Copilot Business includes a public code filter (opt-in in Free/Pro) that flags suggestions matching large blocks from public repositories. When enabled, it reduces but does not eliminate the risk of reproducing licensed code.</p>
<p><strong>Content Exclusions:</strong> Copilot's training data does not include private repositories. However, if your organization uses GitHub Enterprise with custom training data, be aware of what has been included.</p>
<p><strong>Attribution and Citation:</strong> If Copilot suggests code closely matching public code, GitHub's reference panel shows the source repository. Review and attribute appropriately. If using GPL-licensed code in a proprietary project, ensure compliance (often not possible; avoid the suggestion).</p>
<p><strong>Organizational Policy:</strong> Many organizations require developers to avoid Copilot in code that directly incorporates third-party algorithms or to limit its use to scaffolding and boilerplate. Clarify your organization's stance.</p>

<h3>Bias, Sensitive Content, and Content Filters</h3>
<p>Copilot Chat and code completion have built-in safety measures to reduce harmful outputs:</p>
<ul>
<li><strong>Bias Detection:</strong> When prompts or code context contain biased terms or stereotypes, Copilot may refuse or provide a note. However, subtle biases can slip through.</li>
<li><strong>Sensitive Content Filters:</strong> Copilot is trained to decline requests to generate code for illegal activities, weapons, or explicit content.</li>
<li><strong>Developer Responsibility:</strong> Filters are not foolproof. If you receive a biased or concerning suggestion, report it and do not use it. Copilot's behavior improves through feedback.</li>
<li><strong>Inclusive Code Practices:</strong> Be intentional: use inclusive variable names ("owner" vs. gendered terms), avoid stereotype-laden examples, and design algorithms to be fair to all users.</li>
</ul>

<h3>Auditability: Copilot Business and Enterprise</h3>
<p>Organizations using Copilot Business or Enterprise have access to audit and analytics features:</p>
<ul>
<li><strong>Audit Logs:</strong> GitHub Enterprise administrators can view logs of Copilot usage (which users, when, approval status). This enables accountability and compliance tracking.</li>
<li><strong>What Is Logged:</strong> Typically: user identity, timestamp, organization, acceptance/rejection of suggestions, and optionally, feature engagement metrics. Code snippets themselves are generally not logged for privacy.</li>
<li><strong>Retention:</strong> Audit logs are retained according to your organization's data retention policy, often 90–365 days depending on tier and configuration.</li>
<li><strong>Compliance Use Cases:</strong> Financial services, healthcare, and government organizations use audit logs to demonstrate that code underwent human review and to detect unusual patterns of AI-assisted development.</li>
</ul>

<h3>When NOT to Use Copilot</h3>
<p>There are scenarios where Copilot should be restricted or avoided entirely:</p>
<ul>
<li><strong>Regulated Code:</strong> HIPAA, PCI-DSS, FISMA, and SOX compliance may restrict or require explicit approval for AI-assisted code. Verify with your compliance officer.</li>
<li><strong>Secrets and Sensitive Data:</strong> Never paste API keys, passwords, private keys, or customer data into Copilot Chat. Even in code completion, be vigilant; Copilot may have learned patterns from leaked secrets in public repos.</li>
<li><strong>Untrusted Execution Contexts:</strong> Using Copilot in a shared or compromised environment (public computer, malware-suspected system) risks exposing your suggestions or your organization's data.</li>
<li><strong>Critical Security Algorithms:</strong> Cryptographic implementations, authentication mechanisms, and core security logic should be implemented by domain experts and peer-reviewed extensively. Copilot is a poor substitute here.</li>
<li><strong>When Team Policy Forbids It:</strong> Some organizations or projects prohibit Copilot outright. Respect organizational governance.</li>
</ul>

<h3>Responsible Copilot Use: Policy Checklist</h3>
<p>Organizations should establish clear policies addressing:</p>
<ul>
<li>Which code domains permit Copilot use (frontend scaffolding: yes; authentication: no)?</li>
<li>Mandatory PR labels and comments for AI-assisted code?</li>
<li>Secrets screening and pre-commit hooks to prevent credential leakage?</li>
<li>Audit log review frequency and escalation procedures?</li>
<li>Training requirements for developers on Copilot limitations and security?</li>
<li>License scanning and compliance gates (e.g., block GPL suggestions if proprietary)?</li>
<li>Incident response: what to do if a security issue arises from Copilot-assisted code?</li>
</ul>

<h3>Summary: The Responsible AI Developer</h3>
<p>Using GitHub Copilot responsibly means embracing these core practices: <strong>always review</strong> before committing, <strong>test extensively</strong>, <strong>scan for security</strong> and compliance, <strong>understand your tools' limitations</strong>, <strong>respect IP and licensing</strong>, <strong>document AI involvement</strong>, and <strong>follow organizational policies</strong>. Copilot amplifies productivity—but humans remain accountable for every line of code deployed. By maintaining this mindset, you harness Copilot's power while upholding quality, security, and ethical standards.</p>
"""

QUESTIONS = [
    (
        "multiple_choice",
        "You are a developer at a fintech startup. Your team is building a payment processing system. A colleague used Copilot to generate a credit card validation function. The code looks reasonable but has not been tested or reviewed. What should you do?",
        [
            ("Approve and merge immediately; Copilot is trusted by GitHub", 0),
            ("Require peer code review, unit tests, and security scanning before approval, and label the PR as Copilot-assisted", 1),
            ("Only test it locally, then deploy to production", 0),
            ("Ask Copilot to write the test cases as well and skip manual review", 0),
        ],
        "In regulated domains like fintech, AI-assisted code requires heightened scrutiny: code review (for logic and security), testing (to catch hallucinations and edge cases), and security scanning (to detect vulnerabilities). Copilot is a tool, not a guarantee; responsibility lies with the development team. Labeling Copilot involvement enables transparency and audit trails."
    ),
    (
        "multiple_choice",
        "Copilot suggests this code snippet for your authentication module: if password == correct_password: authenticate_user(). What responsible action should you take?",
        [
            ("Use it as-is; it is concise and clear", 0),
            ("Recognize that it lacks error handling and is prone to timing attacks; rewrite using constant-time comparison and add logging", 1),
            ("Deploy to production immediately to ship faster", 0),
            ("Ask Copilot Chat to add crypto; trust its response without further review", 0),
        ],
        "Authentication and cryptography are security-critical domains. Simple string comparison is vulnerable to timing attacks. Responsible use means improving Copilot's suggestions with proper error handling, secure comparison functions (e.g., hmac.compare_digest()), and logging. Security code should be reviewed by domain experts."
    ),
    (
        "multiple_choice",
        "Your code includes a line with a database query generated by Copilot: query = 'SELECT * FROM users WHERE id = ' + user_input. What is the responsible concern here?",
        [
            ("None; it is a simple query", 0),
            ("It is vulnerable to SQL injection; Copilot learned this pattern from public repositories with poor practices", 1),
            ("It will not run on any database", 0),
            ("Copilot always generates secure code, so no review is needed", 0),
        ],
        "LLMs learn from public code, which often includes poor security practices like SQL injection. Copilot may suggest concatenated queries despite the security risk. Responsible validation means checking for injection vulnerabilities, using parameterized queries, and security scanning. This is a key limitation to guard against."
    ),
    (
        "multiple_choice",
        "You are asked to use Copilot to write code for a healthcare application handling patient medical records. Your organization is HIPAA-regulated. What is the most responsible approach?",
        [
            ("Use Copilot freely; no restrictions apply", 0),
            ("Avoid using Copilot with patient data, check organizational policy and compliance team approval, and ensure code is security-reviewed and logged for audit", 1),
            ("Use Copilot but do not label the code as AI-assisted to avoid scrutiny", 0),
            ("Use public code suggestions from Copilot, as they are already vetted", 0),
        ],
        "HIPAA-regulated code has strict audit and security requirements. Copilot should not be used with actual patient data. Code involving regulated data requires organizational approval, heightened review, audit logging, and compliance verification. Transparency (labeling AI involvement) is essential, not something to hide."
    ),
    (
        "multiple_choice",
        "Copilot suggests a code snippet that closely matches a GPL-licensed project shown in the reference panel. Your company ships proprietary software. What should you do?",
        [
            ("Use it anyway; GPL code is always free to use", 0),
            ("Reject the suggestion and rewrite independently; GPL and proprietary licenses are incompatible. Use the reference panel to understand context, then diverge significantly or find a compatible alternative", 1),
            ("Attribute the source but use it as-is", 0),
            ("Ignore the reference panel and assume it is safe", 0),
        ],
        "Copilot's reference panel flags potential GPL matches. GPL is copyleft; incorporating GPL code into proprietary software violates the license. The responsible approach: reject Copilot's suggestion, rewrite independently, or choose a permissive license (MIT, Apache 2.0). IP compliance is non-negotiable."
    ),
    (
        "multiple_choice",
        "During code review, you notice a teammate's PR is filled with Copilot-assisted code but contains no indication of this in the commit message or PR description. The code is functional but not well-tested. What should you do?",
        [
            ("Approve it and mention Copilot later", 0),
            ("Request labeling of AI involvement, require additional tests and security checks before approval, and establish a team norm for transparency", 1),
            ("Reject the entire PR", 0),
            ("Assume it was human-written and review it normally without special scrutiny", 0),
        ],
        "Responsible AI governance requires transparency. Labeling Copilot involvement allows reviewers to heighten scrutiny, supports audit trails, and builds team trust. Establishing norms (commit messages like 'Copilot-assisted: ...') ensures accountability and enables better risk assessment."
    ),
    (
        "multiple_choice",
        "You are configuring Copilot Business for your organization. Which audit and governance features are most important for compliance tracking?",
        [
            ("Only code completion metrics", 0),
            ("Audit logs showing user identity, timestamp, acceptance/rejection, and retention policies; usage analytics; and approval workflows for sensitive code domains", 1),
            ("User names only", 0),
            ("No audit logs; Copilot is trusted", 0),
        ],
        "Copilot Business provides audit logs enabling compliance verification, accountability, and risk management. Key attributes: who used Copilot, when, and whether suggestions were accepted. Logs support regulated environments (HIPAA, PCI, SOX) and help organizations defend their governance posture."
    ),
    (
        "multiple_choice",
        "A developer on your team used Copilot to write an internal API endpoint without disclosing it and without appropriate security testing. How should your organization respond?",
        [
            ("No action; Copilot is trustworthy", 0),
            ("Use this as a teaching moment: conduct a security review, establish policies on Copilot use for APIs, require audit log checks, and provide training on validation and labeling", 1),
            ("Fire the developer", 0),
            ("Disable Copilot for the entire organization", 0),
        ],
        "Responsible AI governance is not punitive but educational. Incidents reveal gaps in policy or training. The organization should: verify the endpoint is secure, clarify policies (e.g., APIs require code review, testing, security scanning regardless of origin), review audit logs, and train the team on responsible use, validation, and transparency."
    ),
]
