# Auto-generated by _build_gh300.py
LESSON_HTML = """
<h2>Lesson 7: Improve Developer Productivity with GitHub Copilot</h2>

<h3>Overview</h3>
<p>GitHub Copilot has matured beyond code completion into a comprehensive platform for improving developer productivity, code quality, and team velocity. This lesson explores practical use cases, measurement strategies, team workflows, and the critical balance between automation and sustainable development practices.</p>

<h3>Productivity Use Cases: Eliminating Toil</h3>
<p>The most immediate value from Copilot comes from reducing repetitive, low-value coding tasks. By automating boilerplate, language translation, and documentation generation, teams reclaim capacity for higher-impact work.</p>

<p><strong>Boilerplate Generation:</strong> Copilot excels at scaffolding new files with standard patterns. When you start a new component, module, or configuration file, Copilot can generate 70–90% of the structure, eliminating context-switching between documentation and your editor.</p>

<pre><code class="language-javascript">// Prompt: "Create a React functional component with useState hook, PropTypes, and export"
import React, { useState } from 'react';
import PropTypes from 'prop-types';

const MyComponent = ({ title, onSubmit }) => {
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState(null);

  const handleSubmit = async (data) => {
    setIsLoading(true);
    setError(null);
    try {
      const result = await onSubmit(data);
      return result;
    } catch (err) {
      setError(err.message);
    } finally {
      setIsLoading(false);
    }
  };

  return (
    &lt;div&gt;
      &lt;h1&gt;{title}&lt;/h1&gt;
      {error && &lt;p style={{ color: 'red' }}&gt;{error}&lt;/p&gt;}
    &lt;/div&gt;
  );
};

MyComponent.propTypes = {
  title: PropTypes.string.isRequired,
  onSubmit: PropTypes.func.isRequired,
};

export default MyComponent;
</code></pre>

<p><strong>Language Translation:</strong> Converting logic between languages—Python to JavaScript, SQL to ORM, regex patterns across flavors—is error-prone and time-consuming. Copilot can translate code while maintaining intent and idioms of the target language.</p>

<p><strong>Regular Expressions and SQL:</strong> Writing correct regex and SQL is cognitively expensive. Copilot can generate patterns from natural-language descriptions, dramatically reducing syntax errors and test cycles.</p>

<pre><code class="language-sql">-- Prompt: "Find customers who purchased over $500 in the last 30 days, grouped by region"
SELECT 
  c.region,
  COUNT(DISTINCT c.customer_id) AS customer_count,
  SUM(o.amount) AS total_spent
FROM customers c
JOIN orders o ON c.customer_id = o.customer_id
WHERE o.order_date >= CURRENT_DATE - INTERVAL '30 days'
  AND o.amount > 500
GROUP BY c.region
ORDER BY total_spent DESC;
</code></pre>

<p><strong>Documentation and Comments:</strong> Copilot can generate docstrings, README sections, and inline comments. This is especially valuable when onboarding to legacy codebases or when creating reference documentation after the fact.</p>

<p><strong>Commit Messages and PR Summaries:</strong> Copilot can analyze diffs and generate meaningful commit messages and PR descriptions, reducing context overhead and improving repository history quality.</p>

<h3>Quality Use Cases: Shifting Left on Testing</h3>
<p>Copilot can significantly accelerate test coverage and help teams catch edge cases before production. By generating test suites and prompting for mutation thinking, Copilot shifts quality assurance earlier in the development lifecycle.</p>

<p><strong>Unit Test Generation:</strong> Copilot can generate test cases for functions, covering happy paths, edge cases, and error conditions. This accelerates test-driven development and reduces test debt.</p>

<pre><code class="language-python">import unittest
from datetime import datetime

def calculate_age(birth_date):
    \"\"\"Calculate age in years from a birth date.\"\"\"
    today = datetime.today()
    return today.year - birth_date.year - ((today.month, today.day) < (birth_date.month, birth_date.day))

class TestCalculateAge(unittest.TestCase):
    def test_age_simple(self):
        birth = datetime(2000, 1, 15)
        self.assertEqual(calculate_age(birth), 26)
    
    def test_age_before_birthday_this_year(self):
        birth = datetime(1995, 12, 25)
        self.assertEqual(calculate_age(birth), 30)
    
    def test_age_after_birthday_this_year(self):
        birth = datetime(1990, 3, 10)
        self.assertEqual(calculate_age(birth), 36)
    
    def test_edge_case_leap_year(self):
        birth = datetime(2000, 2, 29)
        age = calculate_age(birth)
        self.assertGreater(age, 0)
    
    def test_age_same_year(self):
        current_year = datetime.today().year
        birth = datetime(current_year - 1, 6, 15)
        self.assertEqual(calculate_age(birth), 1)

if __name__ == '__main__':
    unittest.main()
</code></pre>

<p><strong>Integration and API Tests:</strong> Copilot can scaffold integration test suites for REST APIs, databases, and microservices, including mock setup and assertion patterns.</p>

<p><strong>Edge Case Discovery:</strong> Prompting Copilot with "What edge cases might this function miss?" can surface boundary conditions, null checks, and error paths that code review often catches too late.</p>

<p><strong>Mutation Thinking:</strong> Ask Copilot to suggest mutations (small, deliberate bugs) that tests should catch. This accelerates the development of robust test suites.</p>

<h3>Security Use Cases: Proactive Risk Mitigation</h3>
<p>Copilot can assist with security scanning, dependency review, and secure coding patterns. However, security is where guardrails are most critical—Copilot is a tool for developers, not a replacement for AppSec expertise.</p>

<p><strong>Vulnerability Scanning Prompts:</strong> Ask Copilot to review code for common vulnerabilities (SQL injection, XSS, CSRF, hardcoded secrets). Copilot can flag patterns and suggest mitigations.</p>

<p><strong>Dependency Review with Copilot:</strong> When integrating new libraries, prompt Copilot to highlight security considerations, recent CVEs, and licensing implications. Always verify with official security advisories.</p>

<p><strong>Secret Scanning Awareness:</strong> Educate teams to ask Copilot to review code for exposed credentials, API keys, and tokens. Use pre-commit hooks alongside Copilot guidance.</p>

<p><strong>Secure Coding Patterns:</strong> Copilot can demonstrate secure alternatives—e.g., parameterized queries instead of string concatenation, content-security-policy headers, or HTTPS-only configurations.</p>

<h3>Measuring Productivity: Metrics, Not Vanity</h3>
<p>Quantifying Copilot's impact requires thoughtful metrics. Raw acceptance rate is misleading; meaningful measurement focuses on velocity, quality, and time-to-value.</p>

<table>
  <thead>
    <tr>
      <th>Metric</th>
      <th>Definition</th>
      <th>Interpretation</th>
      <th>Caution</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>Acceptance Rate</td>
      <td>% of Copilot suggestions accepted by user</td>
      <td>Relative relevance of Copilot output; higher is better</td>
      <td>Does NOT measure productivity; low rates may reflect strong developer preferences</td>
    </tr>
    <tr>
      <td>Lines Suggested / Accepted</td>
      <td>Code volume generated per day / week</td>
      <td>Raw throughput; use with quality metrics</td>
      <td>Vanity metric if not paired with defect rate and test coverage</td>
    </tr>
    <tr>
      <td>Time-to-PR</td>
      <td>Avg. time from task start to PR submission</td>
      <td>Cycle time reduction indicates true velocity gain</td>
      <td>Requires baseline measurement; influenced by task complexity</td>
    </tr>
    <tr>
      <td>DORA Metrics</td>
      <td>Deployment frequency, lead time, MTTR, change failure rate</td>
      <td>Industry-standard DevOps indicators; reflect end-to-end impact</td>
      <td>Requires mature CI/CD infrastructure; Copilot is one lever among many</td>
    </tr>
    <tr>
      <td>Code Review Cycles</td>
      <td>Avg. number of review rounds per PR</td>
      <td>Fewer rounds suggest higher-quality initial code</td>
      <td>May indicate stricter reviews or different reviewer pool</td>
    </tr>
    <tr>
      <td>Test Coverage %</td>
      <td>% of codebase exercised by tests</td>
      <td>Higher coverage with Copilot-generated tests is strong signal</td>
      <td>Measure alongside test quality (not just count)</td>
    </tr>
  </tbody>
</table>

<p><strong>Copilot Metrics API:</strong> GitHub's Metrics API exposes aggregated Copilot usage data at the organization level, enabling data-driven adoption strategies.</p>

<pre><code class="language-bash">curl -X GET \
  https://api.github.com/orgs/YOUR_ORG/copilot/usage \
  -H "Authorization: Bearer YOUR_TOKEN" \
  -H "Accept: application/vnd.github+json"

# Response includes:
# - seats_created_this_cycle
# - seats_inactive_this_cycle
# - active_users
# - total_suggestions_count
# - total_acceptances_count
# - total_lines_suggested
# - total_lines_accepted
# - total_active_users
</code></pre>

<p><strong>Pitfalls of Vanity Metrics:</strong> Beware of optimizing for acceptance rate at the expense of quality. A developer accepting 95% of suggestions may be rubber-stamping poor code. Pair quantitative metrics with qualitative feedback (team surveys, code review sentiment) and security/defect trends.</p>

<h3>Team Workflows: Scaling Copilot Adoption</h3>
<p>Individual developers gain immediate value from Copilot. Teams multiply that value through shared practices, prompt libraries, and code review integration.</p>

<p><strong>Shared Instruction Files (.instructions.md / .copilot-instructions.md):</strong> Teams can create repository-level instruction files that guide Copilot's behavior. These enforce coding standards, architecture patterns, and naming conventions across PRs and pair sessions.</p>

<pre><code class="language-bash">Example .instructions.md for a Python project:

# Code Style
- Use Black for formatting (88-char line length)
- Use type hints on all function signatures
- Follow PEP 257 for docstrings (Google style)

# Architecture
- All database queries use SQLAlchemy ORM (no raw SQL except migrations)
- Async operations use asyncio; no threading
- Error handling: raise custom exceptions in domain/ package

# Testing
- Unit tests in tests/unit/; integration tests in tests/integration/
- Minimum 80% coverage; use pytest-cov
- Mock external APIs with unittest.mock

# Security
- Never log PII; use hash_pii() for user identifiers
- Validate all user input with Pydantic models
- Store secrets in env vars; never commit .env
</code></pre>

<p><strong>Prompt Libraries:</strong> Teams can maintain a shared library of effective prompts for common tasks (API schema generation, test templates, migration scaffolding). This reduces cognitive load and improves consistency.</p>

<p><strong>Code Review with Copilot in PRs:</strong> Copilot can analyze diffs directly in GitHub PRs, offering suggestions for refactoring, test coverage, and security improvements. This augments human review, not replaces it.</p>

<p><strong>Copilot Workspace / Spaces:</strong> For recurring, well-defined tasks (API scaffolding, data pipeline generation), teams can use Copilot Workspace to create guided, multi-file workflows that enforce patterns and reduce decision fatigue.</p>

<h3>Reducing Toil: Automation for Infrastructure and Maintenance</h3>
<p>Beyond feature code, Copilot accelerates infrastructure tasks and reduces maintenance burden.</p>

<p><strong>Scaffolding New Files:</strong> Generate new service classes, database models, API endpoints, and configuration files with minimal manual editing.</p>

<p><strong>Database Migrations:</strong> Copilot can draft Alembic (Python), Flyway, or custom migration scripts when you describe the schema change. Always review migrations before applying to production.</p>

<p><strong>CI/CD Configuration:</strong> GitHub Actions workflows, Docker files, and deployment scripts can be auto-generated from prompts like "Create a GitHub Actions workflow to run pytest on Python 3.9 and 3.11, then publish coverage to Codecov."</p>

<p><strong>Mock Generation:</strong> Unit tests often require mocks. Copilot can generate realistic mock objects, fixtures, and test doubles for complex dependencies.</p>

<p><strong>Legacy Code Refactoring:</strong> When modernizing older codebases (e.g., Python 2 → 3, callbacks → async/await), Copilot can batch-generate refactored versions for validation and incremental rollout.</p>

<h3>Pair-Programming Patterns</h3>
<p>Effective Copilot use mirrors the best practices of human pair programming.</p>

<p><strong>Explain Then Code:</strong> Before asking Copilot to write code, describe the intent, constraints, and expected behavior. This primes Copilot for better suggestions and forces clarity in your own thinking.</p>

<p><strong>Tests First:</strong> Write test cases or acceptance criteria before asking Copilot to implement. This ensures the generated code aligns with requirements.</p>

<p><strong>Review My Diff:</strong> Treat Copilot suggestions as first drafts. Read every line, verify logic, and refactor for clarity and performance.</p>

<h3>Limits and Risks: Sustainable Productivity</h3>
<p>Copilot is powerful but not a silver bullet. Understanding its limitations is essential for maintaining code quality and team health.</p>

<p><strong>Over-Reliance:</strong> Teams may depend on Copilot for trivial tasks, atrophying core skills. Encourage developers to reason through simple problems before invoking Copilot.</p>

<p><strong>Skill Atrophy:</strong> Junior developers may internalize Copilot output without understanding algorithms, data structures, or design patterns. Pair Copilot use with mentoring and code review.</p>

<p><strong>Quality Regression:</strong> Accepting suggestions without scrutiny leads to accumulated technical debt. Bugs in boilerplate or tests propagate silently. Enforce code review discipline alongside Copilot adoption.</p>

<p><strong>Drift Between Code and Tests:</strong> If Copilot generates both implementation and tests, they may satisfy each other without reflecting actual requirements. Always validate generated tests against the specification.</p>

<p><strong>Domain Knowledge Gaps:</strong> Copilot excels at general patterns but may miss domain-specific optimizations, regulatory requirements, or architectural constraints. Provide rich context in prompts and instructions.</p>

<p><strong>Hallucinations and Security Gaps:</strong> Copilot may generate code that appears correct but introduces vulnerabilities or inefficiencies. Always run security scanners, linters, and performance profilers on Copilot-generated code.</p>

<h3>Summary</h3>
<p>GitHub Copilot accelerates developer productivity across boilerplate, testing, security, and maintenance. Success requires thoughtful measurement (beyond vanity metrics), shared team practices, and disciplined code review. When balanced with human judgment and integrated into mature development workflows, Copilot multiplies team velocity and code quality.</p>
"""

QUESTIONS = [
    (
        "multiple_choice",
        "Your team is evaluating Copilot adoption. A stakeholder points to a 72% acceptance rate and claims the tool is a huge productivity win. What should you verify before claiming success?",
        [
            ("Check if the acceptance rate aligns with industry benchmarks for similar teams", 0),
            ("Measure whether time-to-PR, DORA metrics, and code quality indicators have improved, not just acceptance rate", 1),
            ("Conduct a survey asking developers if they feel more productive", 0),
            ("Compare Copilot usage against lines of code written per developer per month", 0),
        ],
        "Acceptance rate alone does not indicate productivity gains. Pair it with cycle time, defect rate, and team velocity metrics to draw meaningful conclusions."
    ),
    (
        "multiple_choice",
        "A junior developer on your team is using Copilot to generate all test cases for critical payment processing code. They accept most suggestions without modification. What is the most important risk to address first?",
        [
            ("Copilot-generated tests can mirror the generated implementation, producing tests that always pass but do not reflect the real business requirements", 1),
            ("The acceptance rate will be artificially high, inflating the team Copilot metrics", 0),
            ("Payment processing is a domain where Copilot training data is insufficient", 0),
            ("The IDE will become slower because Copilot is invoked too often during test authoring", 0),
        ],
        "Drift between generated code and generated tests is the critical risk: tests written against the same suggestion will pass trivially without validating the real payment requirements. Human-authored or human-reviewed tests are essential for critical paths."
    ),
    (
        "multiple_choice",
        "You are setting up a team .instructions.md file to guide Copilot behavior across your Python repository. Which directive is most effective for improving code consistency?",
        [
            ("List all acceptable Python packages; Copilot will only suggest imports from that list", 0),
            ("Specify code style (formatter, line length, type hints), architecture patterns (ORM usage, async model), and testing standards (framework, coverage threshold)", 1),
            ("Instruct Copilot to always generate verbose comments explaining every function", 0),
            ("Require Copilot to generate docstrings in NumPy style instead of Google style", 0),
        ],
        "Effective instructions focus on architectural decisions, code style, and testing patterns—not low-level syntax. These guide Copilot without micromanaging implementation."
    ),
    (
        "multiple_choice",
        "Your team is using Copilot to refactor legacy code from callbacks to async/await. What validation step should you prioritize to avoid regressions?",
        [
            ("Increase the Copilot acceptance rate threshold to ensure high-quality suggestions", 0),
            ("Run existing unit tests and integration tests against refactored code; measure coverage and behavior parity", 1),
            ("Have Copilot generate new tests for the refactored code and accept all suggestions", 0),
            ("Compare the number of lines in the original vs. refactored code to ensure no features were dropped", 0),
        ],
        "Existing tests are the gold standard for validating refactoring. They verify behavior is preserved. New Copilot-generated tests alone cannot catch regressions if both implementation and tests have drifted from original intent."
    ),
    (
        "multiple_choice",
        "A developer asks Copilot to generate a SQL query for a complex reporting task. The query returns results quickly in testing but performs poorly in production with 50M+ rows. What is a likely root cause and how should the team mitigate?",
        [
            ("Copilot generated a suboptimal query; always run EXPLAIN PLAN on generated SQL and test with production-scale data before deployment", 1),
            ("The production database has different indexes than the test environment; this is not Copilot's fault", 0),
            ("The developer did not provide enough context in the prompt; regenerating the query will fix performance", 0),
            ("Performance issues with large datasets indicate Copilot should not be trusted for SQL generation", 0),
        ],
        "Copilot is not a query optimizer. Generated SQL may be functionally correct but inefficient at scale. Always analyze execution plans, test with representative data volumes, and involve a DBA for complex queries."
    ),
    (
        "multiple_choice",
        "Your org has adopted shared Copilot instruction files and prompt libraries. What is the primary benefit of this approach?",
        [
            ("It reduces the time developers spend reading documentation and architectural guidelines", 0),
            ("It enforces consistency across PRs, accelerates onboarding, and ensures domain knowledge and patterns are baked into Copilot suggestions", 1),
            ("It guarantees that all Copilot-generated code will pass code review without human changes", 0),
            ("It eliminates the need for architecture review; Copilot will enforce all patterns automatically", 0),
        ],
        "Shared instructions and libraries scale team practices through Copilot. They do not eliminate code review—human judgment remains essential—but they accelerate convergence on standards and reduce cognitive load."
    ),
    (
        "multiple_choice",
        "A security-focused code review flags a Copilot-generated SQL query that concatenates user input directly into the query string. The developer argues they provided the prompt with no context about parameterization. What should the team do?",
        [
            ("Accept the code since the developer followed Copilot's output faithfully", 0),
            ("Reject the code, refactor it to use parameterized queries, and add a team instruction that all database queries must use parameterized syntax", 1),
            ("Report a bug to GitHub stating Copilot generated insecure code", 0),
            ("Use this as an example to discourage developers from using Copilot for SQL generation", 0),
        ],
        "Copilot generates code based on prompts and training data. It does not automatically know your security standards. Secure coding patterns must be encoded in .instructions.md and enforced in code review."
    ),
    (
        "multiple_choice",
        "You are using the Copilot Metrics API to track adoption. Which metric combination best indicates that Copilot is delivering real productivity value, not just adoption theater?",
        [
            ("High active_users and total_lines_accepted counts", 0),
            ("Increasing acceptance rates over time and growing total_suggestions_count", 0),
            ("High acceptance rate paired with a decrease in code review cycles, faster time-to-PR, and stable defect rates", 1),
            ("Total_acceptances_count growing faster than total_active_users, indicating more mature Copilot usage", 0),
        ],
        "True productivity gains are reflected in faster cycle times, shorter review cycles, and maintained (or improved) quality. Raw volume metrics without cycle time and quality context are vanity metrics."
    ),
]
