# Auto-generated by _build_pl300.py
LESSON_HTML = """
<h2>Lesson 8: Security, Governance, and Performance</h2>

<h3>Licensing Models and Capabilities</h3>
<p>Power BI offers multiple licensing tiers, each unlocking different capabilities for data analysis and sharing:</p>

<table>
<tr>
<th>License</th>
<th>Key Capabilities</th>
<th>Use Case</th>
</tr>
<tr>
<td><strong>Power BI Free</strong></td>
<td>Personal reports, Power BI Desktop, limited cloud storage (10 GB)</td>
<td>Individual exploration and learning</td>
</tr>
<tr>
<td><strong>Power BI Pro</strong></td>
<td>Workspace sharing, publishing apps, 10 GB capacity per user</td>
<td>Teams collaborating within an organization</td>
</tr>
<tr>
<td><strong>Premium Per User</strong></td>
<td>Large datasets, paginated reports, XMLA endpoints</td>
<td>Power users requiring advanced features</td>
</tr>
<tr>
<td><strong>Premium Capacity / Fabric Capacity</strong></td>
<td>Dedicated hardware, unlimited users viewing published content, enterprise features</td>
<td>Organization-wide deployments, governed environments</td>
</tr>
</table>

<p><strong>Key distinction:</strong> Premium capacity users can view published content without individual licenses, making it cost-effective for large-scale dashboards. Paginated reports require at least Premium Per User licensing.</p>

<h3>Row-Level Security (RLS)</h3>
<p>RLS restricts data access based on user identity. <em>Static roles</em> assign predefined filters to user groups; <em>dynamic roles</em> evaluate filters at query time using user properties.</p>

<p><strong>Dynamic RLS Example:</strong> Using the DAX function <code>USERPRINCIPALNAME()</code> returns the logged-in user's email. Combine this with a dimension table to filter data:</p>

<pre><code class="language-dax">[Sales Amount] IF SalesManager[Email] = USERPRINCIPALNAME()</code></pre>

<p>For Azure AD scenarios, <code>USEROBJECTID()</code> retrieves the user's Azure AD object ID from the directory, enabling more granular control in multi-tenant environments.</p>

<h3>Object-Level Security (OLS)</h3>
<p>OLS controls which tables and columns users can see in a semantic model, independent of data filtering. This prevents sensitive column metadata from being visible to certain users.</p>

<h3>Sharing and Collaboration</h3>
<p>Power BI supports multiple sharing patterns:</p>
<ul>
<li><strong>Workspace Access:</strong> Direct role assignment (Admin, Member, Contributor, Viewer) for collaborative editing</li>
<li><strong>App Publishing:</strong> Package reports and dashboards for broad organizational distribution with role-based viewing</li>
<li><strong>Report and Dashboard Sharing:</strong> Direct links to individuals or groups with granular permissions</li>
<li><strong>Shared Links:</strong> Public or organization-only links for read-only access without requiring Power BI licenses for viewers</li>
</ul>

<h3>Sensitivity Labels and Data Loss Prevention</h3>
<p>Microsoft Purview Information Protection integrates sensitivity labels into Power BI to classify and protect sensitive content. Administrators define labels (e.g., Public, Internal, Confidential) with associated governance rules.</p>

<p>When a sensitivity label is applied:</p>
<ul>
<li>Export restrictions can prevent downloading to Excel or PDF</li>
<li>Data Loss Prevention (DLP) policies prevent unauthorized sharing of labeled content</li>
<li>Labels persist through Power BI exports and downstream analytics tools</li>
</ul>

<h3>Tenant Settings and Admin Governance</h3>
<p>The Power BI Admin Portal provides tenant-level controls managed by administrators:</p>
<ul>
<li><strong>Capacity settings:</strong> Premium capacity allocation and max queries per second</li>
<li><strong>Feature flags:</strong> Enable/disable R/Python visuals, external data connectors, and XMLA endpoints</li>
<li><strong>User experience:</strong> Default storage location, export settings, and publishing permissions</li>
<li><strong>Admin API:</strong> Programmatic access to tenant configuration, usage metrics, and capacity monitoring</li>
</ul>

<h3>Audit and Activity Logging</h3>
<p>Power BI maintains comprehensive audit trails. The <em>Office 365 Audit Log</em> (accessed via the Microsoft 365 Compliance Center) records all Power BI activities: dataset refreshes, report views, sharing actions, and admin changes. Activity logs can be queried via the Admin Activity API for real-time monitoring and compliance reporting.</p>

<h3>Performance Optimization</h3>
<p><strong>Performance Analyzer:</strong> A built-in Power BI Desktop tool that profiles DAX query duration and visual rendering time.</p>

<p><strong>DAX Studio / VertiPaq Analyzer:</strong> External tools enabling deep DAX profiling and memory analysis of semantic models.</p>

<p><strong>Optimization techniques:</strong></p>
<ul>
<li><strong>Aggregations:</strong> Pre-calculated summaries for frequently queried dimensions, accelerating dashboard queries</li>
<li><strong>Reduce visuals per page:</strong> Fewer visuals mean fewer simultaneous queries; consider pagination or drill-through</li>
<li><strong>Query reduction:</strong> Remove unused columns, disable auto-sync for slicers on slow data sources</li>
</ul>

<h3>Troubleshooting Refresh Failures</h3>
<p>Refresh failures often stem from connectivity, timeout, or permission issues. Check the dataset settings for credentials, gateway status for on-premises sources, and Power Query timeout settings. The refresh history in the admin portal logs errors; cross-reference with capacity activity logs for resource constraints.</p>
"""

QUESTIONS = [
  ("multiple_choice", "What licensing requirement applies to paginated reports?", [("Power BI Free", False), ("Power BI Pro with add-on", False), ("Premium Per User or Premium Capacity", True), ("Any license allows paginated reports", False)], "Paginated reports are a Premium feature and require at least Premium Per User or Premium Capacity licensing."),
  ("multiple_choice", "In dynamic RLS, how do you filter data based on the logged-in user's email address?", [("Use USEROBJECTID() and a user table", False), ("Use USERPRINCIPALNAME() to retrieve the user's principal name", True), ("Manually assign each user to a static role", False), ("Apply OLS at the column level", False)], "USERPRINCIPALNAME() returns the email address of the logged-in user, enabling dynamic role filtering against a dimension table."),
  ("multiple_choice", "What is the primary difference between OLS and RLS?", [("RLS filters rows; OLS restricts table and column visibility", True), ("OLS applies only to Premium Capacity; RLS applies to all licenses", False), ("They are the same feature with different names", False), ("RLS is for sharing; OLS is for performance", False)], "OLS (Object-Level Security) hides tables and columns from users, while RLS (Row-Level Security) filters which rows users can see within accessible tables."),
  ("multiple_choice", "What is the primary purpose of applying sensitivity labels in Power BI?", [("To improve query performance", False), ("To classify and protect sensitive content with governance rules and export controls", True), ("To reduce file size when exporting", False), ("To automatically create new workspaces", False)], "Sensitivity labels classify content and trigger DLP policies that prevent unauthorized sharing or restrict exports of sensitive data."),
  ("multiple_choice", "Which performance optimization technique involves pre-calculating frequently queried summaries?", [("Query reduction", False), ("Reducing visuals per page", False), ("Using aggregations", True), ("Enabling XMLA endpoints", False)], "Aggregations store pre-summarized data to accelerate queries; this is a key technique for improving dashboard performance on large datasets."),
  ("multiple_choice", "Where are Power BI activities (dataset refreshes, report views, sharing actions) logged?", [("Power BI Admin Portal only", False), ("The Office 365 Audit Log accessed via the Microsoft 365 Compliance Center", True), ("A local .csv file on the user's machine", False), ("Power BI Desktop Event Viewer", False)], "The Office 365 Audit Log in the Compliance Center provides the comprehensive audit trail for Power BI tenant activities for compliance and monitoring."),
  ("multiple_choice", "Which sharing method allows users without Power BI licenses to view published content in Premium Capacity?", [("Workspace access with Viewer role", False), ("App publishing to the organization", True), ("Direct report sharing via email", False), ("Shared links for Free license users", False)], "Premium Capacity allows viewers without individual licenses to see published apps; this is a cost-effective way to scale dashboards across large audiences."),
  ("multiple_choice", "What does the Admin Activity API enable administrators to do?", [("Query tenant configuration, usage metrics, and capacity activity in real time", True), ("Design Power BI reports programmatically", False), ("Export all user data to Azure Data Lake", False), ("Automatically create RLS roles for new users", False)], "The Admin Activity API provides programmatic access to audit logs and capacity monitoring, enabling automation of governance and compliance tasks.")
]
