# Auto-generated by _build_pl300.py
LESSON_HTML = """
<h2>Lesson 5: DAX Fundamentals</h2>

<h3>Introduction to DAX</h3>
<p>DAX (Data Analysis Expressions) is the formula language used in Power BI, Analysis Services, and Power Pivot. It enables you to create dynamic calculations and measures that respond to user filters and selections. Unlike traditional spreadsheet formulas, DAX understands relational data models and works with entire columns and tables rather than individual cells.</p>

<h3>DAX Syntax Basics</h3>
<p>DAX syntax resembles Excel formulas but operates on a larger scale. Every DAX formula begins with an equals sign and can reference columns, tables, and functions. Functions in DAX are case-insensitive, but column references are sensitive to capitalization. A simple measure might look like:</p>
<pre><code class="language-dax">Total Sales = SUM(Sales[Amount])</code></pre>
<p>This measure sums all values in the Amount column of the Sales table, automatically adjusting when filters are applied.</p>

<h3>Row Context vs Filter Context</h3>
<p>Understanding context is critical in DAX. <strong>Row context</strong> refers to the current row being evaluated, typically within a SUMX or similar iterator. <strong>Filter context</strong> is the set of all filters applied to the data—from slicers, row/column labels in a visual, or report-level filters. Most standard aggregation functions (SUM, AVERAGE, COUNT) operate in filter context only.</p>

<table>
<tr>
<th>Concept</th>
<th>Row Context</th>
<th>Filter Context</th>
</tr>
<tr>
<td>Definition</td>
<td>The current row in an iterator function</td>
<td>All active filters on the model</td>
</tr>
<tr>
<td>Functions</td>
<td>SUMX, AVERAGEX, COUNTX</td>
<td>SUM, AVERAGE, COUNTROWS</td>
</tr>
<tr>
<td>Column References</td>
<td>Column can be directly referenced</td>
<td>Requires relationship or full path</td>
</tr>
<tr>
<td>Recalculation</td>
<td>For each row in table</td>
<td>Once per filter combination</td>
</tr>
</table>

<h3>Implicit vs Explicit Measures</h3>
<p><strong>Implicit measures</strong> are quick calculations created by dragging fields to the Values area in a visual (e.g., Sum of Sales). <strong>Explicit measures</strong> are defined in the model using the Measure button and written with full DAX formulas. Explicit measures are recommended because they are reusable, appear in the Field list, and allow complex logic.</p>

<h3>Common Aggregation Functions</h3>
<p>DAX provides several aggregation functions. <strong>SUM</strong> adds numeric values; <strong>AVERAGE</strong> calculates the mean; <strong>COUNTROWS</strong> counts non-blank rows in a table; and <strong>DISTINCTCOUNT</strong> counts unique values in a column. For example:</p>
<pre><code class="language-dax">Unique Customers = DISTINCTCOUNT(Sales[CustomerID])</code></pre>

<h3>CALCULATE and Filter Context Modification</h3>
<p>CALCULATE is the most powerful function in DAX. It evaluates an expression in a modified filter context. You can replace, add, or preserve existing filters:</p>
<pre><code class="language-dax">Sales This Year = CALCULATE(SUM(Sales[Amount]), YEAR(Sales[Date]) = 2024)</code></pre>
<p>CALCULATE clears all existing row context and applies new filter arguments, making it essential for conditional measures.</p>

<h3>FILTER and Iterators</h3>
<p>The FILTER function returns a table of rows that meet a condition. It introduces row context for each row being tested:</p>
<pre><code class="language-dax">High Value Orders = COUNTROWS(FILTER(Sales, Sales[Amount] > 1000))</code></pre>
<p>SUMX, AVERAGEX, and similar iterators evaluate an expression row-by-row. SUMX is often used when you need custom row-level logic that SUM cannot provide.</p>

<h3>ALL, ALLEXCEPT, and KEEPFILTERS</h3>
<p><strong>ALL</strong> removes all filters from one or more columns. <strong>ALLEXCEPT</strong> removes all filters except those specified. <strong>KEEPFILTERS</strong> preserves the existing filter context while adding new filters. These are crucial for calculating totals, percentages, and comparisons across filter boundaries.</p>

<h3>Variables (VAR/RETURN) and Time Intelligence</h3>
<p>Variables improve readability and performance by storing intermediate results. The syntax is:</p>
<pre><code class="language-dax">Sales Ratio = VAR Total = SUM(Sales[Amount]) VAR Filtered = CALCULATE(SUM(Sales[Amount]), Sales[Region] = "North") RETURN DIVIDE(Filtered, Total)</code></pre>
<p>Time intelligence functions like TOTALYTD, SAMEPERIODLASTYEAR, and DATEADD enable year-over-year comparisons and running totals. DIVIDE handles division by zero gracefully.</p>

<h3>Error Handling</h3>
<p>Use <strong>DIVIDE(numerator, denominator, alternate_value)</strong> instead of the / operator to avoid errors when the denominator is zero. Quick Measures in Power BI automate common calculations like year-to-date and running averages.</p>
"""

QUESTIONS = [
    ("multiple_choice", "What is the primary difference between &lt;strong&gt;row context&lt;/strong&gt; and &lt;strong&gt;filter context&lt;/strong&gt; in DAX?", [
        ("Row context applies filters from slicers, while filter context applies only within iterator functions.", False),
        ("Row context is the current row in an iterator function, while filter context is the set of all active filters on the model.", True),
        ("Filter context occurs only in PivotTables, while row context occurs in Power BI visuals.", False),
        ("They are interchangeable terms used synonymously in Power BI.", False)
    ], "Row context operates per-row inside iterators like SUMX, whereas filter context encompasses all active model filters."),
    
    ("multiple_choice", "Which function is used to evaluate an expression in a &lt;strong&gt;modified filter context&lt;/strong&gt;?", [
        ("SUM", False),
        ("FILTER", False),
        ("CALCULATE", True),
        ("SUMMARIZE", False)
    ], "CALCULATE is the primary function for explicitly modifying and replacing the filter context."),
    
    ("multiple_choice", "What will the following DAX formula return? &lt;code&gt;Total = SUM(Sales[Amount])&lt;/code&gt;", [
        ("The sum of all amounts in the current row only.", False),
        ("The sum of all amounts in the Sales table, adjusted by the current filter context.", True),
        ("The sum of amounts greater than 1000.", False),
        ("The average amount across all rows.", False)
    ], "SUM operates in filter context, so it respects all active slicers and filters applied to the report."),
    
    ("multiple_choice", "When should you use &lt;strong&gt;SUMX&lt;/strong&gt; instead of &lt;strong&gt;SUM&lt;/strong&gt;?", [
        ("When you need to sum a single column without any complex logic.", False),
        ("When you need row-by-row logic or calculations that depend on context-sensitive expressions.", True),
        ("When the column contains text values.", False),
        ("When you want to improve formula performance.", False)
    ], "SUMX is an iterator that evaluates an expression for each row, enabling row-specific calculations that SUM cannot perform."),
    
    ("multiple_choice", "What does this DAX formula do? &lt;code&gt;YTD Sales = TOTALYTD(SUM(Sales[Amount]), Calendar[Date])&lt;/code&gt;", [
        ("Calculates the total sales for the last year.", False),
        ("Calculates the running total of sales from the start of the calendar year to the current date.", True),
        ("Calculates the average sales per day in the current month.", False),
        ("Filters sales to show only the current year.", False)
    ], "TOTALYTD is a time intelligence function that returns a year-to-date cumulative total, resetting at each year boundary."),
    
    ("multiple_choice", "Which function should you use to safely divide two numbers when the denominator might be zero?", [
        ("Use the / operator and wrap in IFERROR.", False),
        ("Use AVERAGE to avoid division.", False),
        ("Use DIVIDE with an alternate value for zero denominators.", True),
        ("Use IF to check if the denominator is 1.", False)
    ], "DIVIDE allows you to specify an alternate value or error message when division by zero would occur."),
    
    ("multiple_choice", "What is the primary benefit of using &lt;strong&gt;VAR/RETURN&lt;/strong&gt; syntax in DAX?", [
        ("It automatically applies all filters to the calculation.", False),
        ("It improves readability and can improve performance by storing intermediate results.", True),
        ("It eliminates the need for CALCULATE.", False),
        ("It converts implicit measures to explicit measures.", False)
    ], "VAR/RETURN allows you to break complex formulas into named steps, making them easier to understand and potentially faster."),
    
    ("multiple_choice", "When evaluating the formula &lt;code&gt;CALCULATE(SUM(Sales[Amount]), ALL(Sales[Region]))&lt;/code&gt;, what does ALL accomplish?", [
        ("It sums amounts only for the current region selected in a filter.", False),
        ("It removes all filters on the Region column, so the sum includes all regions regardless of current filters.", True),
        ("It sums amounts for all tables in the model.", False),
        ("It requires you to manually select which regions to include.", False)
    ], "ALL clears filters from the specified column(s), allowing the calculation to ignore region-based slicers or filters.")
]
