# Auto-generated by _build_pl300.py
LESSON_HTML = """
<h2>Deploy and Maintain Power BI Assets</h2>

<h3>Power BI Service Workspaces</h3>
<p>Power BI Service provides two primary workspace types for organizing and sharing content. <strong>My Workspace</strong> is a personal area where you develop and test reports and dashboards—content here cannot be shared with others in a managed way. <strong>Collaborative workspaces</strong> enable teams to work together, with role-based access control determining what each member can do.</p>

<h3>Workspace Roles and Permissions</h3>
<p>Each collaborative workspace supports four distinct roles:</p>
<ul>
<li><strong>Admin:</strong> Full control—can manage workspace membership, edit content, create apps, and configure settings.</li>
<li><strong>Member:</strong> Can create, edit, and delete content; publish apps; but cannot manage workspace access or settings.</li>
<li><strong>Contributor:</strong> Can create and edit content but cannot publish apps or delete items created by others.</li>
<li><strong>Viewer:</strong> Read-only access to reports, dashboards, and apps; cannot edit or publish.</li>
</ul>

<h3>Deployment Pipelines and Content Lifecycle</h3>
<p>Deployment pipelines enforce a controlled release process across three environments: <strong>Development</strong>, <strong>Test</strong>, and <strong>Production</strong>. Content (reports, dashboards, semantic models) flows left-to-right through these stages. Pipelines automatically handle backward compatibility for semantic models, preventing breaking changes when datasets are updated in production. This ensures stability and minimizes downtime for consumers.</p>

<h3>Power BI Apps</h3>
<p>Apps package and distribute workspace content to end users with a tailored, read-only interface. Members and Admins can publish apps; Viewers cannot. Apps support <strong>audiences</strong>—a feature allowing you to deliver different versions of the same app to different groups based on organizational roles or regions. This single-app, multi-audience approach simplifies maintenance and ensures users see only relevant content.</p>

<h3>Semantic Models and Datasets</h3>
<p><strong>Semantic models</strong> (formerly called datasets) are the semantic layer connecting raw data to reports. Power BI Service distinguishes between import models (data stored in memory) and DirectQuery models (live connections). Semantic models can be shared across workspaces using shared datasets, promoting reuse and consistency. When promoting or certifying a semantic model, you signal its reliability and readiness for enterprise use.</p>

<h3>On-Premises Data Gateway</h3>
<p>Organizations with on-premises data sources or on-premises Power BI Report Server must use a data gateway to securely bridge cloud Power BI Service and on-premises systems.</p>
<table border="1" cellpadding="8">
<tr>
<th>Gateway Type</th>
<th>Mode</th>
<th>Use Case</th>
<th>User Limit</th>
</tr>
<tr>
<td>Personal Gateway</td>
<td>Personal</td>
<td>Development and testing; single user</td>
<td>1 user</td>
</tr>
<tr>
<td>Standard Gateway</td>
<td>Standard or Enterprise</td>
<td>Production; shared across teams</td>
<td>Unlimited</td>
</tr>
</table>
<p>Production deployments require a Standard Gateway due to its high availability, redundancy, and support for multiple users. Personal Gateways are suitable only for personal development.</p>

<h3>Scheduled Refresh and Refresh Limits</h3>
<p>Scheduled refresh allows automatic data updates on a schedule. However, licensing imposes limits:</p>
<ul>
<li><strong>Pro License:</strong> 8 refreshes per day per semantic model.</li>
<li><strong>Premium or PPU License:</strong> 48 refreshes per day per semantic model.</li>
</ul>
<p>For high-frequency updates, consider <strong>incremental refresh</strong>, which appends only new or changed data rather than replacing the entire model. This reduces bandwidth, accelerates refresh time, and enables real-time or near-real-time scenarios.</p>

<h3>Dataflows and Data Preparation</h3>
<p><strong>Dataflows (Gen1)</strong> are cloud-based data preparation pipelines using Power Query online; they store intermediate data in Azure Data Lake Storage. <strong>Dataflows Gen2</strong> offer enhanced scalability and tighter integration with the modern Power BI fabric. Both reduce redundant ETL work by allowing multiple semantic models to consume the same prepared data.</p>

<h3>Managing Parameters Across Environments</h3>
<p>Parameters enable dynamic values in queries and calculations. When deploying a semantic model from Dev to Test to Prod, update parameters (such as database server names or date ranges) to reflect each environment. Many organizations use tools like Tabular Editor or ALM Toolkit to automate parameter updates during deployment, ensuring reports point to the correct data sources in each stage.</p>

<h3>Endorsement: Promoted vs. Certified</h3>
<p><strong>Promoted</strong> items are flagged by workspace members as recommended but informal endorsements. <strong>Certified</strong> items have passed rigorous validation by designated admins or data governance teams and carry organizational trust. Certified items appear with a badge and are preferred in discovery searches, signaling to users that the content meets enterprise standards.</p>

<h3>Best Practices for Content Lifecycle</h3>
<p>Effective Power BI governance includes: (1) Using consistent naming conventions and descriptions across environments; (2) Documenting lineage and ownership; (3) Scheduling regular refresh intervals aligned with business needs; (4) Archiving or retiring stale content to reduce clutter; (5) Monitoring refresh failures and gateway health; and (6) Establishing a review cadence for endorsement status to keep certifications current.</p>
"""

QUESTIONS = [
  (
    "multiple_choice",
    "Which workspace roles can publish Power BI apps?",
    [
      ("Admin and Member", True),
      ("Only Admin", False),
      ("Admin, Member, and Contributor", False),
      ("Any role with workspace access", False)
    ],
    "Contributor role can create and edit content but cannot publish apps. Viewer roles cannot publish. Only Admin and Member have app publishing rights."
  ),
  (
    "multiple_choice",
    "Your organization is moving a semantic model to production and requires high availability and support for multiple concurrent users. Which gateway type should you use?",
    [
      ("Personal Gateway in Personal mode", False),
      ("Standard Gateway", True),
      ("Personal Gateway in Enterprise mode", False),
      ("Any gateway with automatic failover enabled", False)
    ],
    "Personal Gateways support only one user and are unsuitable for production. Standard Gateways provide redundancy, high availability, and support unlimited users."
  ),
  (
    "multiple_choice",
    "How many scheduled refreshes per day does a Power BI Pro license allow per semantic model?",
    [
      ("4", False),
      ("16", False),
      ("8", True),
      ("Unlimited", False)
    ],
    "Pro licenses allow a maximum of 8 refreshes per day per semantic model. Premium and PPU licenses allow up to 48."
  ),
  (
    "multiple_choice",
    "Your dataset contains five years of historical sales data, but you only need to refresh the last three months daily. What technique reduces refresh time and bandwidth usage?",
    [
      ("Dataflow Gen2 storage optimization", False),
      ("Incremental refresh", True),
      ("Direct Query mode conversion", False),
      ("Parameter management", False)
    ],
    "Incremental refresh appends only new or changed data, dramatically reducing refresh duration and data transfer. It is ideal for large historical datasets with frequent updates to recent data."
  ),
  (
    "multiple_choice",
    "What is the primary purpose of a deployment pipeline in Power BI Service?",
    [
      ("To compress and archive old reports automatically", False),
      ("To enforce a controlled release process across Dev, Test, and Production environments while maintaining backward compatibility", True),
      ("To automatically scale Premium capacity based on user load", False),
      ("To encrypt all semantic models in transit", False)
    ],
    "Deployment pipelines move content through staged environments, ensuring testing occurs before production release and preventing breaking changes to datasets."
  ),
  (
    "multiple_choice",
    "What is the difference between Promoted and Certified endorsement in Power BI?",
    [
      ("Promoted items are certified by admins; Certified items are informal recommendations", False),
      ("Promoted is informal recommendation by workspace members; Certified requires validation by designated governance teams and carries organizational trust", True),
      ("Certified items appear only in the current workspace; Promoted items are visible organization-wide", False),
      ("There is no functional difference; they are aliases for the same feature", False)
    ],
    "Promoted endorsement is informal and user-driven. Certified endorsement signifies rigorous validation by admins or governance teams and is the stronger organizational stamp of approval."
  ),
  (
    "multiple_choice",
    "What is the primary benefit of using app audiences in Power BI?",
    [
      ("To limit the number of users who can access an app", False),
      ("To deliver different versions of the same app to different groups, simplifying maintenance and ensuring role-specific content", True),
      ("To encrypt audience data separately from other app content", False),
      ("To schedule when specific audiences can view the app", False)
    ],
    "App audiences allow a single published app to display tailored content and layouts for different user groups, reducing the need to maintain multiple separate apps."
  ),
  (
    "multiple_choice",
    "You are developing a semantic model that will be shared by multiple teams and deployed to production. Which of the following is a best practice for managing parameters across Dev, Test, and Prod environments?",
    [
      ("Use hardcoded server names and update them manually each deployment", False),
      ("Store parameters in the Power Query script and update them manually in each environment", False),
      ("Use parameterized queries and automate updates via ALM Toolkit or Tabular Editor during deployment", True),
      ("Deploy the semantic model once and have all environments query from the same database server", False)
    ],
    "Automating parameter updates ensures consistency, reduces manual errors, and enforces environment-specific data sources at deployment time without manual intervention."
  )
]
